- backend/Dockerfile
- backend/README.md
- backend/api/Program.cs
- backend/api/Startup.cs
- backend/api/appsettings.json
- docker-compose.yml
- openshift/templates/secrets/README.md
Update healthchecksui config to match.
Note: This change forces the api to run on port 8080. This already appears to be the case when the api is running on openshift, so it shouldn't change anything there. Let me know if there are concerns - in theory we could just override the appsettings using an openshift configmap, then my change to 8080 wouldn't be necessary.
> PIMS-1250: Update local docker/api to run more similarly to openshift.

- backend/api/Areas/Admin/Controllers/ParcelController.cs
- backend/api/Controllers/ParcelController.cs
- backend/api/Models/BuildingModel.cs
- backend/api/Models/EvaluationModel.cs
- backend/api/Models/ParcelModel.cs
- backend/api/Models/Parts/ParcelBuildingModel.cs
- backend/api/Profiles/BuildingProfile.cs
- backend/api/Profiles/EvaluationProfile.cs
- backend/api/Profiles/ParcelProfile.cs
- backend/dal/PIMSContext.cs
- backend/dal/Services/Concrete/ParcelService.cs
Automap Evaluations
Move logic from controller to DAL
> PIMS-1220, PIMS-1221, PIMS-1222

- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- backend/test/Controllers/Admin/UserControllerTest.cs
- backend/test/Controllers/Keycloak/UserControllerTest.cs
- backend/test/Routes/Keycloak/UserControllerTest.cs
When making a request for properties with a parent agency it makes more sense to also include the sub-agencies.
This isn't technically a bug, but a user-experience issue.
> PIMS-1339 Including sub-agencies in filter

- docker-compose.yml
- frontend/Dockerfile
As of version 3.4.1, react-scripts exits after start-up which causes the container to exit.
```
Attaching to frontend-app
frontend-app   |
frontend-app   | > frontend@0.1.0 start /usr/app
frontend-app   | > react-scripts start
frontend-app   |
frontend-app   | [HPM] Proxy created: /  -> http://backend:8080/
frontend-app   | [HPM] Subscribed to http-proxy events: [ 'proxyReq', 'error', 'close' ]
frontend-app   | ℹ ｢wds｣: Project is running at http://172.19.0.6/
frontend-app   | ℹ ｢wds｣: webpack output is served from
frontend-app   | ℹ ｢wds｣: Content not from webpack is served from /usr/app/public
frontend-app   | ℹ ｢wds｣: 404s will fallback to /
frontend-app   | Starting the development server...
frontend-app   |
frontend-app exited with code 0
```
Turning on **interactive mode** resolves …
> Fix frontend container crash

- backend/api/Startup.cs
- scripts/gen-env-files.sh
HealthCheckUI is causing the API to fail.  As it is not a required dependency I am temporarily removing it.  A feature that is supposed to assist in the health of the API shouldn't be bringing down the API (regardless of why).  It should fail and let the API continue, but it doesn't.  It needs to be extracted and run on its own container.
I've also fixed our setup script that generates our `.env` files.
> Removing HealthCheckUI from API.

- backend/dal/Helpers/Extensions/IdentityExtensions.cs
- backend/dal/Services/Concrete/UserService.cs
Currently when activating users it uses their first name as their username.  This isn't correct and will lead to issues where users have the same first name.
This fix correctly applies their username to their account.
> Fix /auth/activate endpoint

- backend/api/Areas/Property/Controllers/SearchController.cs
- backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
- backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
- backend/api/Areas/Property/Models/Search/PropertyModel.cs
- backend/api/Areas/Reports/Controllers/PropertyController.cs
- backend/api/Areas/Reports/Mapping/Property/PropertyMap.cs
- backend/api/Areas/Reports/Models/Property/PropertyModel.cs
- backend/api/Controllers/LookupController.cs
- backend/api/Helpers/Constants/ContentTypes.cs
- backend/api/Helpers/Reporting/ReportHelper.cs
- backend/core/Helpers/CsvHelper.cs
- backend/core/Helpers/XmlHelper.cs
- backend/core/Pims.Core.csproj
- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- backend/dal/Services/Concrete/PropertyService.cs
- backend/dal/Services/IPropertyService.cs
- backend/entities/PropertyTypes.cs
- backend/entities/Views/Property.cs
- backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
- backend/tests/unit/api/Controllers/Reports/PropertyControllerTest.cs
- backend/tests/unit/api/Routes/Property/SearchControllerTest.cs
- backend/tests/unit/api/Routes/Reports/PropertyControllerTest.cs
- backend/tests/unit/dal/Services/PropertyServiceTest.cs
- frontend/src/constants/API.tsx
- frontend/src/pages/Test.tsx
- frontend/src/router.tsx
- frontend/src/utils/download.tsx
The API now supports the ability to export properties in both CSV and Excel format!
**Endpionts**
- GET /api/reports/properties
- POST /api/reports/properties/filter
**HTTP Request Header**
The endpoints require you to include the HTTP Request Header 'Accept' as one of the following;
- text/csv
- application/vnd.ms-excel
- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
**HTTP Request Query Parameters**
> All of the existing filters apply
**Testing**
I have created a test page as a temporary example when this is deployed.  This test page can be removed later, or used for other purposes.
- [DEV](pims-dev.pathfinder.gov.bc.ca/test)
**Notes**
I have moved the root `PropertyController` into its own area `/Areas/Property/SearchController`.  This is to improve organization.
> PIMS-1541 Adding Excel Export Report

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-react.yml
- codecov.yml
For some reason the api code coverage report wasn't working.
Using GitHub secrets to keep the CodeCov token outside of source.
> PIMS-1685 Fixing api coverage and secret

- codecov.yml
- frontend/package.json
Trying to determine why coverage reports for a mono-repo with different stacks is failing to report correctly.
> PIMS-1685 Code Coverage

- frontend/src/forms/subforms/BuildingForm.tsx
Thought I was just missing this claim locally so manually added it myself to test. But turns out it is supposed to be admin-properties!
> Changing claim to appropriate name

- backend/dal/Migrations/20200514194159_Initial.Designer.cs
- backend/dal/Migrations/20200514194159_Initial.cs
- backend/dal/Migrations/Initial/PostDeploy/01-Users.sql
- backend/dal/Migrations/PimsContextModelSnapshot.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/entities/User.cs
We have system user accounts that exists for backend relationships that shouldn't be returned as users that can be managed.  This update will hide them from the UI.
This only solves one of the two problems, but it's a start.
Regrettably it requires a DB refresh.
> DB Migration - System Accounts

- .github/workflows/api-dotnetcore.yml
- backend/tests/unit/api/coverlet.runsettings
- backend/tests/unit/dal/coverlet.runsettings
- openshift/pipelines/Jenkinsfile.cicd
- Follow recommended `coverlet` approach on CI servers
- Exclude migrations from code coverage
- Restore GitHub action
- Update Jenkins pipeline
> Re-enable API code coverage on CI servers

- frontend/src/forms/ParcelDetailForm.test.tsx
- frontend/src/forms/subforms/BuildingForm.tsx
- frontend/src/forms/subforms/EvaluationForm.tsx
There was something strange going on with the classification values being passed when adding a new building (it would default to the property's classification). Causing [this problem.](https://pimsteam.atlassian.net/browse/PIMS-2038?atlOrigin=eyJpIjoiMGJlM2E2MTEzOGQ3NDU5MmE1M2VlZGE3NzllNTdiMjUiLCJwIjoiaiJ9). Now the user is defaulted to no value in the building classification and when selected the values pass through correctly.
There is also another bug that the City appears to be auto filled (when adding a new building) but is not actually sending a value. I will address this after I get my remaining stories done.
> PIMS-2038, 1838, 1708

- backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
- backend/api/Areas/Property/Models/Search/PropertyModel.cs
- backend/dal/Migrations/Initial/PostDeploy/01-ViewProperties.sql
- backend/entities/Views/Property.cs
Adds the `ParcelId` to the results so that buildings can include a link to their parent parcel.
Note - This will require either refreshing your DB or manually running the SQL script.
> PIMS-1420 Adding ParcelId to Properties

- frontend/src/forms/subforms/BuildingForm.tsx
- frontend/src/forms/subforms/PidPinForm.tsx
Project Number now editable on the Parcel Detail Form when the user has the `admin-properties` claim.
Just wanted to do this while I thought of it.
> Enabling Project Number

- maintenance/README.md
- openshift/templates/backup/BACKUP.md
- openshift/templates/backup/deploy.yaml
Fix syntax for memory requests in backup dc config.
Fix typo in maintenance readme.
Add missing step to backup documentation.
Add all flags to backup documentation that are likely to change per-environment.
Add a tip related to BACKUP_VOLUME_SIZE
> Documentation updates to maintenance and backup readmes.

- frontend/src/components/maps/BuildingPopupView.test.tsx
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/features/projects/dispose/components/columns.tsx
- frontend/src/pages/SubmitProperty.test.tsx
- frontend/src/pages/SubmitProperty.tsx
- SRES now able to edit any property
- updating corresponding tests 
- restrict classification options to surplus active and surplus encumbered (still working on unit tests)
> PIMS-2410, 2411, 2397

- backend/dal/Services/Concrete/ProjectService.cs
Fixing issue where updating a project with incomplete tasks and trying to change the status at the same time would throw a validation error.  The fix will compare the requested update tasks completion state as well as in the database.
> PIMS-2443 Fixing validation on incomplete tasks.

- backend/tools/keycloak/sync/realm.json
Only the SRES role should currently have the `dispose-approve` claim.
> PIMS-2438 Correct permission issue in roles

- frontend/src/components/common/form/DisplayCurrency.scss
- frontend/src/components/common/form/DisplayCurrency.tsx
- frontend/src/components/common/form/FastCurrencyInput.tsx
- frontend/src/components/common/form/index.ts
- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/__snapshots__/ParcelPopupView.test.tsx.snap
- frontend/src/forms/ParcelDetailForm.test.tsx
- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/forms/subforms/BuildingForm.test.tsx
- frontend/src/forms/subforms/EvaluationForm.tsx
- frontend/src/forms/subforms/SumFinancialsForm.tsx
- frontend/src/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
Display clickable Project Number on property pins that belong to a project. Only visible to owning agency and SRES
Update Assessed Value tables. `ParcelDetailForm` now has `Land`, `Improvements`, and `Total` columns. Building  Assessed Value table remains the same; however, the value entered there is reflected under `Improvments` on the `ParcelDetailForm`
> PIMS-2175, 2193

- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/forms/subforms/EvaluationForm.tsx
As appraised information is now controlled whether to be shown or not some of the old validation was still firing causing an error while trying to update properties/buildings
> Update Parcel Bug

- backend/api/Mapping/Lookup/CodeMap.cs
- backend/api/Mapping/Lookup/LookupMap.cs
- backend/api/Models/CodeModel.cs
The Lookup endpoints will now include `ParentId` for agencies.
> Adding ParentId to Agency endpoint

- openshift/pipelines/Jenkinsfile.cicd
- openshift/pipelines/Jenkinsfile.test-to-prod
- openshift/pipelines/scripts/common.groovy
- openshift/pipelines/scripts/notify.groovy
- openshift/player.sh
- openshift/scripts/common.sh
- openshift/scripts/envars
- openshift/scripts/oc-backup.sh
- openshift/scripts/oc-build.sh
- openshift/scripts/oc-deploy.sh
- openshift/templates/jenkins/generic-pipeline.yaml
This PR refactors our CI/CD pipeline to:
- Ask for a version tag to apply to successful builds. The version is optional for dev builds but **mandatory** for master builds
- Use external shell scripts to build and deploy instead of Jenkins-specific groovy code.
It also provides a PROD pipeline that:
- Asks for a version to deploy (which was provided in the CI/CD build for master builds)
- Brings up the maintenance page
- Performs a DB backup
- Deploys the tagged version to PRODUCTION
- Takes down the maintenance page and re-routes traffic to PROD server
**NOTE** - the `generic-pipeline.yaml` file has been updated with relevant env vars required by the updated pipelines
> PIMS-2188 Develop production Deployment Configuration process

- frontend/src/features/projects/dispose/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/dispose/forms/ReviewApproveForm.tsx
- frontend/src/features/projects/dispose/forms/ReviewProjectForm.tsx
- frontend/src/features/projects/dispose/forms/disposalYupSchema.ts
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.tsx
- frontend/src/features/projects/dispose/steps/ReviewProjectStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/properties/components/forms/ParcelDetailForm.scss
Allow users to save during review approve step without the validation. Validation now only fires on submission (approval button). Fix city input alignment, and spelling of referal -> referral
> PIMS-2628, and other minor fixes

- frontend/package-lock.json
- frontend/package.json
- frontend/sonar-project.properties
- openshift/pipelines/Jenkinsfile.cicd
- openshift/pipelines/Jenkinsfile.test-to-prod
- openshift/pipelines/scripts/common.groovy
Initial PR that runs SonarQube scans for React/JavaScript in the CI/CD. 
The backend scan will be added in my next PR.
**NOTE** - this PR also fixes a bug in the build pipelines where they are running in "dry run" mode without actually deploying new code.
> PIMS-2816 DevOps - Add SonarQube to pipeline

- backend/api/Areas/Admin/Controllers/AgencyController.cs
- backend/api/Areas/Admin/Mapping/Agency/AgencyMap.cs
- backend/api/Areas/Admin/Models/Agency/AgencyModel.cs
- backend/dal/Security/Permissions.cs
- backend/dal/Services/Admin/Concrete/AgencyService.cs
- backend/dal/Services/Admin/IAgencyService.cs
- backend/tools/keycloak/sync/Models/UserModel.cs
- backend/tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
- backend/tools/keycloak/sync/SyncFactory.cs
A fix for the annoying issue where running the keycloak sync tool throws an error if an agency doesn't exist.
It will now ignore the missing agencies and provide a summary of the sync at the end of the log.
> Fixing keycloak sync error

- openshift/pipelines/Jenkinsfile.cicd
Pipeline line is failing when running backend tests.
- Extending timeout
- Updating stage names to be more descriptive
> Extending timeout for tests

- .editorconfig
- backend/api/Areas/Tools/Controllers/GeocoderController.cs
- backend/api/Areas/Tools/Mapping/Geocoder/PidsMap.cs
- backend/api/Areas/Tools/Models/Geocoder/SitePidsResponseModel.cs
- backend/geocoder/GeocoderService.cs
- backend/geocoder/IGeocoderService.cs
- backend/geocoder/Models/SitePidsResponseModel.cs
- backend/tests/unit/api/Controllers/Tools/GeocoderControllerTest.cs
- backend/tests/unit/api/Routes/Tools/GeocoderControllerTest.cs
This is the API portion of the Geocoder PID integration
New API endpoint:
`/api/tools/geocoder/parcels/pids/{siteId}`
^ this mirrors the geocoder API endpoint for consistency in case we add more endpoints later.
You get a `siteId` as part of the response for a valid address in `api/tools/geocoder/addresses`
New unit tests that cover the new feature
> PIMS-2621 API - Integrate with DataBC Geocoder - PID

- Makefile
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/hooks/useApi.ts
This PR adds frontend logic to integrate with the API geocoder PID endpoint. 
In the SubmitProperty form, when a valid address is selected (and if that address returns a non-empty `siteId`) the frontend will request the PIDs associated with that `siteId`. If no `siteId` is supplied, the PID field is cleared in the form.
**NOTE** - there is an outstanding bug that makes the PID not show until you focus on the PID input and then select another field. Some code seems to be running only `onBlur`. There's a separate issue filed to deal with that so the fix is not part of this PR. Until that bug is resolved, you will need to select the PID field and then another field to verify a value has been set from the geocoder request. 😞
> PIMS-2621 Integrate with DataBC Geocoder - PID

- backend/api/Areas/Notification/Controllers/QueueController.cs
- backend/api/Areas/Project/Controllers/DisposeController.cs
- backend/api/Pims.Api.csproj
- backend/api/appsettings.Development.json
- backend/api/appsettings.Local.json
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Migrations/Initial/PostDeploy/01-NotificationTemplates.sql
- backend/dal/Options/NotificationOptions.cs
- backend/dal/Options/PimsOptions.cs
- backend/dal/Pims.Dal.csproj
- backend/dal/Services/Concrete/NotificationQueueService.cs
- backend/dal/Services/Concrete/NotificationTemplateService.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/dal/Services/INotificationQueueService.cs
- backend/dal/Services/INotificationService.cs
- backend/dal/Services/IProjectService.cs
- backend/notifications/Configuration/NotificationOptions.cs
- backend/notifications/Extensions/ServiceCollectionExtensions.cs
- backend/notifications/INotificationService.cs
- backend/notifications/NotificationService.cs
- backend/notifications/Pims.Notifications.csproj
- backend/tests/unit/api/Controllers/Notification/QueueControllerTest.cs
- backend/tests/unit/api/Controllers/Project/DisposeControllerTest.cs
- backend/tests/unit/dal/Libraries/NotificationServiceTest.cs
- backend/tests/unit/dal/Services/NotificationTemplateServiceTest.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
Updated notifications to send one when the shared notes are changed.
> Requires DB Refresh to get the latest notification templates
Notifications by default will not throw exceptions, however local and development configuration will throw exceptions (to help with debugging).  This should improve the user experience if notifications fail in production.
> PIMS-2861 Adding notification for shared note.

- backend/Dockerfile.migrations
- openshift/templates/migrations/build.yaml
- openshift/templates/migrations/migration-job.yaml
This PR sets up the ground work for running EF migrations from within the CI pipeline. 
The main idea here is to create a custom build with `dotnet-ef` bundled. Then a migration job "pod" will be created in CI builds to migrate the database.
```bash
oc process -f migration-job.yaml -p ENV_NAME=prod -p IMAGE_TAG=master -o yaml | oc -n jcxjin-prod create -f - 
```
> PIMS-2822 OpenShift templates for DB migration job

- auth/keycloak/Dockerfile
- auth/keycloak/README.md
- backend/dal/Services/Concrete/UserService.cs
- tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
- tools/keycloak/sync/README.md
- tools/keycloak/sync/RealmFactory.cs
- tools/keycloak/sync/SyncFactory.cs
Cleaning up Keycloak Sync Tool code.
Updating documentation.
Updating Keycloak docker container version.
The original reason for this story was to simplify the Keycloak Sync Tool when run the first time.  However Keycloak does not have a Service Account available until you manually create one.  Which means as long as the **import** feature in Keycloak is broken, we'll simply need to manually create the Service Account the first time.
> PIMS-1657 Updating Keycloak Sync Tool

- backend/dal/Configuration/AgencyConfiguration.cs
- backend/dal/Services/Admin/Concrete/ProjectService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- backend/entities/Agency.cs
- backend/tests/unit/dal/Services/ParcelServiceTest.cs
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/PagedBuildingForms.test.tsx
- frontend/src/features/properties/components/forms/subforms/PagedBuildingForms.tsx
- frontend/src/features/properties/submit/SubmitProperty.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- openshift/templates/pims-api/deploy.yaml
- tools/import/appsettings.Production.json
- tools/keycloak/sync/appsettings.json
- tools/keycloak/sync/realm.json
Provide a way to allow agencies to view and edit buildings they own when they don't own the parcel.
Adding `Geocoder` Secret to Deployment Configuration.
Fixing possible bug in production when adding projects.
Updating Keycloak configuration for production.
> PIMS-2489 Allowing building ownership

- docs/DEVOPS.md
- openshift/pipelines/Jenkinsfile.test-to-prod
- openshift/player.sh
- openshift/scripts/common.sh
- openshift/scripts/oc-migrate.sh
New bash script created `oc-migrate.sh` that will run a pod that has `dotnet ef` installed - in a similar fashion as you would do `docker run ...`
The `oc` command returns the exit code from the migration process:
- If successful the CI pipeline continues building. 
- If the migration cannot be applied, an error code is returned and the CI pipeline aborts
Once this is merged we will need to test success and failure scenarios to get ready to launch in production.
> PIMS-2822 Run migrations in CI build

- frontend/src/features/properties/components/forms/subforms/EvaluationForm.tsx
A recent update to the EvaluationForm broke validation for all parcels with future evaluation dates, because those future assessed values were being filtered from display, but still being validated. This ensures those values aren't displayed and aren't validated.
> Do not validate assessed values that are filtered out of the display.

- frontend/src/features/properties/components/forms/subforms/PagedBuildingForms.tsx
When adding new buildings to a parcel they will by default have the same address as the parcel.
> PIMS-2686 Copy parcel address to new building

- maintenance/maintenance.sh
- openshift/pipelines/Jenkinsfile.test-to-prod
Just ran the PROD pipeline and noticed the maintenance page is shown under `https://pims-prod.pathfinder...` instead of the main DNS name. This is due to how routes where named and how the maintenance script expects routes to be named in a certain way.
This PR have modifies `maintenance.sh` to accommodate overriding the name of the route to redirect to the Maintenance Page pod.
**NOTE:** 
This code change will need to make its way to `dev` and then to `master` before it can be fully tested
> Fix maintenance page in production environment

- backend/dal/Services/Concrete/PropertyService.cs
- backend/tests/unit/dal/Services/PropertyServiceTest.cs
Performance memory issues are occurring on the **Property List View** which is resulting in failed requests.
Removing valid `Count` so that it is one less massive scan against the whole table.
This results in not knowing how many pages of results there are, but should be a lot better than a failed request.
> Improving performance of Property List View

- frontend/src/App.scss
The issue with the help tooltip is an issue throughout the application. All of the question icon tooltips I tested had this flickering behaviour.
> fix tooltips in firefox.

- openshift/templates/monitoring/grafana-template.yml
I asked for help on how to integrate Github OAuth credentials, and @stephenhillier says they do not give away the client secret to the `bcdevops` org, so Github OAuth with Grafana is not possible for our case, but using an OAuth Proxy is the best option at the moment
> PA-1035 Integrating with Openshift authentication

- Makefile
- backend/dal/Configuration/ProjectConfiguration.cs
- backend/dal/Migrations/20201016195846_correctAgencies.cs
- backend/dal/Migrations/20201023193301_v01.01.01.Designer.cs
- backend/dal/Migrations/20201023193301_v01.01.01.cs
- backend/dal/Migrations/PimsContextModelSnapshot.cs
- backend/entities/Project.cs
- backend/entities/ProjectSnapshot.cs
- scripts/db-migration.sh
Creating new database migration **v01.01.00** which contains updates to the **Project** and **ProjectSnapshot** tables.
Updating makefile with a few more shortcuts to get things done quicker;
- `make db-add n={migration name}` = create a new migration and auto complete the code changes for scripts
- `make db-drop` = drop the whole database
- `make npm-refresh` = If npm packages change, get the frontend rebuilt and working again
- `make db-remove` = remote the prior migration and files from code and the db
- `make db-migrations` = list all the migrations
- `make db-rollback n={migration name}` = rollback the specified db migration
` `make build n={service name}` = build the specific service
- `make up n={service name}` = spin up the specific service
- `make stop n={service name}` = stop …
> pa-745 & pa-635 - Adding v01.01.00 migration

- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/ParcelService.cs
- backend/dal/Services/Admin/IBuildingService.cs
- backend/dal/Services/Admin/IParcelService.cs
- backend/tests/unit/dal/Services/Admin/BuildingServiceTest.cs
- backend/tests/unit/dal/Services/Admin/ParcelServiceTest.cs
Previously financials values for each each year were being ignored during import.  This update corrects this issue.  Additionally a new endpoint has been created to support only updating property financial values (`/api/tools/import/properties/financials`).  This new endpoint will allow us to rerun the import without overwriting any changes made to inventory in production.
> pa-1270 Fixing import property financials

- backend/dal/Services/Admin/Concrete/ParcelService.cs
An unexpected condition where the import is not able to handle untitled properties (i.e. PID = 000-000-000).  This update will only throw an exception if the property has no titled PID.
> Fixing import for untitled properties

- backend/tests/core/Entities/BuildingHelper.cs
- frontend/src/actions/parcelsActions.ts
- frontend/src/components/maps/BuildingPopupView.scss
- frontend/src/components/maps/BuildingPopupView.test.tsx
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.scss
- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/__snapshots__/BuildingPopupView.test.tsx.snap
- frontend/src/components/maps/__snapshots__/ParcelPopupView.test.tsx.snap
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/features/projects/common/interfaces.ts
- frontend/src/features/properties/components/forms/subforms/BuildingForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/PagedBuildingForms.test.tsx
- frontend/src/features/properties/list/PropertyListView.test.tsx
- frontend/src/features/properties/list/buildings/IProperty.ts
- frontend/src/features/properties/list/interfaces.ts
Replacing `Building.LocalId` with `Building.Name` property.
Updated the following forms by removing **Local ID** and cleaning up the formatting.
- **Map View** - **Parcel Popup**
- **Map View** - **Building Popup**
- **Property Detail View** - **Building Information Section**
The following formatting has changed on the **Parcel Popup** and **Building Popup**
- PID at the top centered for parcels
- Name bolded at top
- Name label removed
- Description displayed if different than the name
- Description label removed
- Address label removed
- View and Update buttons applied the same to both building and parcel
> PA-633 Replacing Local ID

- frontend/src/components/SearchBar/FilterBar.tsx
- frontend/src/components/SearchBar/ParentGroupedFilter.tsx
- frontend/src/components/common/form/Select.tsx
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/components/maps/MapFilterBar.scss
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/features/admin/agencies/AgencyFilterBar.tsx
- frontend/src/features/admin/agencies/EditAgencyPage.scss
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/admin/agencies/ManageAgencies.scss
- frontend/src/features/admin/agencies/ManageAgencies.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/features/properties/list/FilterBar.test.tsx
- frontend/src/features/properties/list/FilterBar.tsx
- frontend/src/features/properties/list/__snapshots__/FilterBar.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/hooks/useRouterFilter.ts
- frontend/src/interfaces/agency.ts
- frontend/src/utils/YupSchema.ts
- frontend/src/utils/utils.ts
Grouped auto complete filter now on map landing page and property list view. Further customization may be needed but this is a good start to get some feedback. 
Bug fixes included in this PR are as follows:
- styling changes so the agency page now scales and doesn't look terrible
- email validation on edit user page
- popup display for when agency has associated buildings while trying to delete
- only select parent agencies where appropriate
- name and code validation when updating or adding an agency 
- agencies now appear in appropriate lists when they are newly added or edited
- parent agency field is locked when it is a parent agency
- leaving the parent agency on the placeholder (blank) will lock that field and change the text to no parent on save
**New since last edit**
- grouped …
> Group autocomplete for filters

- openshift/templates/logging/elasticsearch-template.yml
I was using an old version of Elasticsearch image that did not allow to set a bootstrap password. Solution:
- Upgrade to latest Elastic version
- Create secret for the bootstrap password
- Mount persistent volume to /usr/share/elasticsearch/data for data persistency
> Adding elasticsearch and kibana persistency

- openshift/PIPELINES.md
Note that I did not need to create a new cicd file for this pipeline, nor any new bcs or dcs, I was able to reuse our existing pipeline, bcs, and dcs, configmaps and secrets and just tweak the parameters. Since we aren't committing our params to source, there isn't a whole lot to include with this PR. This shows that the work that we have put into the pipelines into the past is starting to pay off.
The alpha version of the app is running here: https://pims-alpha-dev.pathfinder.gov.bc.ca
note that it is currently reusing the sso pims-app resource, which I think is probably for the best. It is also reusing the database, which needs more discussion.
I think there are use cases for having a separate DB instance for dev-alpha, although I think non-release ready DB changes are probably less …
> Add dev-alpha-pipeline doc.

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Concrete/ProjectReportService.cs
- backend/dal/Services/Concrete/ProjectService.cs
Updated extension methods to handle deserialization when `metadata` is null.
> Fixing deserializing null metadata

- backend/dal/Migrations/Initial/Up/PostUp/01-Workflow.sql
- frontend/src/components/common/Label.tsx
- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/components/maps/MapFilterBar.scss
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/features/projects/common/interfaces.ts
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/utils/utils.ts
Draft PR for now have some bugs I want to fix first but just getting the PR up
- updated map filter bar to have the new agency filter component (clickable headers)
- project statuses can now be multi selected in the project list view (fixing some bugs here in regards to resetting the filter and how the group headings are chosen)
**Update**: can now select parent and it will supply the input with the corresponding statuses as shown in GIF below
> Multiselect + new filter functionality

- frontend/src/actions/parcelsActions.ts
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/PopupView.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/components/maps/leaflet/SelectedPropertyMarker/SelectedPropertyMarker.tsx
- frontend/src/components/maps/leaflet/Spiderfier.ts
- frontend/src/components/maps/leaflet/mapUtils.tsx
- frontend/src/features/mapSideBar/hooks/useQueryParamSideBar.tsx
- frontend/src/hooks/useApi.ts
- frontend/src/utils/testUtils.ts
The supercluster render in the PointCluster component was easy to test, interacting directly with leaflet in the react tests is not any playground. I refactored the component to use react component in the render. 
I used this refactored code to write unit tests, showcasing how we can write more tests in the leaflet component
> Refactoring the Supercluster rendering for easy testing

- frontend/src/App.scss
- frontend/src/components/layout/AppNavBar/AppNavBar.scss
- frontend/src/components/layout/AppNavBar/AppNavBar.test.tsx
- frontend/src/components/layout/AppNavBar/AppNavBar.tsx
- frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.test.tsx.snap
- frontend/src/features/properties/components/GeocoderAutoComplete.scss
Fixed the NavBar unit tests, reordered tests to match ordering on page, added a few tests to cover all menu items.
Also fixed the dropdown styling so they all match
> PA-1968: Group all Disposal Project links under one menu item

- backend/api/Areas/Property/Controllers/SearchController.cs
- backend/dal/Services/Concrete/PropertyService.cs
- backend/dal/Services/IPropertyService.cs
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
The massive request for all properties is killing the DB and API.  Constant `Out of Memory` issues keep showing up.  Which results in a `Gateway Timeout` on the app.
This change reimplements `_.debounce(...)` to reduce the number of requests.  In addition a temporary DAL method that does not incur an additional request for project status information has been created to reduce the load.  In reality we shouldn't be making the project status request in this endpoint anyway, but I don't have time to refactor other features presently.
> Minor improvements to resolve memory issues

- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/ProjectLayout.scss
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/AppraisalCheckListForm.tsx
- frontend/src/features/projects/common/forms/ProjectDraftForm.tsx
- frontend/src/features/projects/common/forms/SelectProjectPropertiesForm.tsx
- frontend/src/features/projects/common/tabs/ProjectInformationTab.tsx
- frontend/src/features/projects/dispose/ProjectDisposeView.scss
- frontend/src/features/projects/dispose/steps/DocumentationStep.tsx
- frontend/src/features/projects/dispose/steps/ProjectDraftStep.tsx
- frontend/src/features/projects/dispose/steps/ReviewProjectStep.tsx
- frontend/src/features/projects/dispose/steps/UpdateInfoStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/DocumentationStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ProjectDraftStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/projects/list/columns.tsx
- frontend/src/features/projects/spl/forms/CloseOutAdjustmentForm.tsx
- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.scss
- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
- frontend/src/features/projects/spl/tabs/SurplusPropertyInformationTab.tsx
Allow notes text boxes to expand in disposal projects
Fix "Net Book" to "Net Book Value" everywhere
> PA-1740, 1771: Allow text boxes to expand, fix Net Book Value

- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/components/maps/providers/FIlterProvider.tsx
- frontend/src/features/properties/map/MapView.tsx
- frontend/src/hooks/useApi.ts
When using the filter using the filter bar the map should zoom to the results. The map will resume the default behavior, zooming and moving. I wrapped the inventory results with a featureGroup so that I can zoom to the bounds of the layers/markers on the group. 
I also remove some dead code in the map component, @devinleighsmith ping me if you have an questions
> PA-2114 Zoom to property when filtering on Map

- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/mocks/filterDataMock.ts
Due to rushing in last minute PRs we broke the map filter bar.  This should resolve those issues.  However I have discovered some other issues along the way that will need to be reviewed.  Regrettably there appears to be inconsistent behaviour which results in the following bugs showing up from time-to-time;
- agencies filter input `undefined` and not functioning
- An infinite loop that results in a React error `Maximum update depth exceeded`
- Pins remaining on the map that shouldn't be there after a filter has been entered
> PA-2234 Fixing map filter

- frontend/src/constants/trueFalse.ts
- frontend/src/features/properties/filter/IPropertyFilter.ts
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useMount.ts
- frontend/src/hooks/useRouterFilter.ts
Organizing the code to be clearer and generic.
I'm not certain ignoring the exhaustive dependencies is ideal, but in this example we would only ever want this to execute the effect on Mount.
> PA-2236 Cleaned Property Filter code

- auth/keycloak/config/realm-export.json
- backend/entities/NoteTypes.cs
- frontend/src/constants/noteTypes.ts
- frontend/src/features/projects/assess/forms/ReviewApproveForm.tsx
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/forms/DocumentationForm.tsx
- frontend/src/features/projects/common/tabs/DocumentationTab.tsx
- frontend/src/features/projects/dispose/testUtils.ts
During assessment of a disposal project an assessor can now capture notes specific to documentation provided.
- Added separate `sresfm` to Keycloak for testing the **SRES Financial Manager** role.
> PA-2211 Added Documentation Note

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
Now subscribing to the map `ondragend` to monitor the map bounds and make API query to load more data. `onzoomend` was too spammy and causing the map to make unnecessary api calls, and infinite loops. 
Also reenabled zoom results after searching
> Fixing map crashing and zoom to results after search

- backend/api/Areas/Property/Controllers/SearchController.cs
- backend/api/Areas/Property/Models/Search/GeoJsonFilterModel.cs
- backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- backend/entities/Models/AllPropertyFilter.cs
- backend/entities/Models/BuildingFilter.cs
- backend/entities/Models/PropertyFilter.cs
- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/components/common/form/Input.tsx
- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/components/common/form/Select.scss
- frontend/src/components/maps/FindMorePropertiesButton.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/API.ts
- frontend/src/features/properties/filter/IPropertyFilter.ts
- frontend/src/features/properties/filter/PropertyFilter.scss
- frontend/src/features/properties/filter/PropertyFilter.test.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/PropertyFilterOptions.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
New filter bar revamp, clicking Find available properties will allow you to search by:
- location
- project number
- Building predominate use
- Building construction type
- Building number of floors
- Net rentable area
- Min/max lot size
- Bare land only
See GIF below for UI:
_**Updated**: Bare Land Only filter now filters out land with buildings on it properly and changed building name -> name so users can search for any property name_
> Filterbar Revamp

- frontend/src/features/projects/common/ApprovalTransitionPage.tsx
- frontend/src/features/projects/common/interfaces.ts
- frontend/src/features/projects/erp/steps/ErpStep.tsx
Projects that go through a few status transitions use the `ApprovalTransitionPage` component.  It wasn't able to handle the latest changes to possible transitions.
> Fixed Disposal Project Status Transition

- frontend/src/features/projects/common/interfaces.ts
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/spl/forms/CloseOutFinancialSummaryForm.tsx
- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
Don't entirely understand the issue that was occurring, but it appears to be related to Formik handling of undefined values.  While this was working originally without these additional steps, it now will calculate and return $0 for the calculated fields.
> Fixed SPL form error

- openshift/MULTIPLE_INSTANCES.md
- openshift/templates/pims-api/deploy.yaml
- openshift/templates/pims-app/deploy.yaml
- openshift/templates/resources/api-sso-configMap.yaml
- openshift/templates/resources/app-sso-configMap.yaml
- tools/import/README.md
- tools/import/appsettings.Development.json
- tools/import/appsettings.Test.json
- tools/import/appsettings.json
- tools/keycloak/sync/appsettings.development.json
- tools/keycloak/sync/appsettings.json
- tools/keycloak/sync/appsettings.test.json
Updated configuration to match the new SSO domain name `oidc.gov.bc.ca`
> Updating sso domain name

- frontend/src/components/common/form/ParentSelect.scss
- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/features/properties/components/forms/subforms/InformationForm.tsx
- frontend/src/features/properties/filter/PropertyFilter.scss
Quick bug fix to only allow SRES users to select Disposed for property classifications 
Updated: Still fighting off the warnings on the `ParentSelect` component. Split off the larger dropdown menu for agencies into this PR
> Only SRES can select Disposed classification

- frontend/src/features/properties/containers/ParcelDetailFormContainer.tsx
- frontend/src/utils/YupSchema.ts
Handled the fix on the frontend, let me know if this is ok
Bug was that the API is still expecting OccupantTypeId and it has been removed from the frontend. Also the schema was still validating for it.
> Hotfix for OccupantId error

- frontend/src/features/properties/components/forms/subforms/InformationForm.tsx
Originally had this checking the label not the value and when I switched it over to use the value and enum I forgot to cast it to a number
> Classification - remove disposed from non-sres

- frontend/src/utils/YupSchema.ts
Some numeric fields weren't part of the yup schema and therefore were not validating non-numeric inputs.
> PA-2376 update yup schema to include missing number fields.

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
Note - I am going to make another ticket as I noticed some of the other fields were not clearing properly (eg. Agency). They clear when you hit search and then reset but if you fill in values without submitting and then hit reset they will not. Will assign ticket to myself for this sprint. 
Includes:
- bug fix for the clearing of location
- adding the `Typeahead` component to the `Surplus Properties` location search to allow for autocomplete
> Location filter bug fix

- .github/workflows/api-dotnetcore.yml
Fix for the failing GitHub action currently block PR's. Coverlet console had an update 2 days ago and it looks like it does not support .Net Core 3.1. Reverted back to the previously used version of coverlet to address this problem
> Coverlet console fix

- openshift/3.11/MULTIPLE_INSTANCES.md
- openshift/3.11/PIPELINES.md
- openshift/3.11/pipelines/Jenkinsfile.cicd
- openshift/3.11/pipelines/Jenkinsfile.dev-to-test
- openshift/3.11/pipelines/Jenkinsfile.test-to-prod
- openshift/3.11/templates/jenkins/generic-pipeline.yaml
Moving jenkins files around to prepare for OCP4.0 broke the 3.11 pipelines.  These updates should resolve them.
> Fixing DevOps Jenkins configuration

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/constants/API.ts
- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
- frontend/src/typings/tiles-in-bbox/index.d.ts
I used a library called `tiles-in-bbox` to generate tiles (size 256), then use the generated tiles to calculate a bbox for each tile and use it to fetch inventory markers features for the tile. The results of each tiles are merged together and passed as props to the PointCluster component for rendering (same behaviour as before). After all the files have loaded/processed, the map zooms to the results.
> Using tiles to fetch PIMS Inventory

- backend/api/Areas/Property/Controllers/ParcelController.cs
- backend/dal/Services/Concrete/ParcelService.cs
- backend/tests/unit/dal/Services/ParcelServiceTest.cs
- frontend/src/actionCreators/parcelsActionCreator.spec.ts
- frontend/src/actionCreators/parcelsActionCreator.ts
- frontend/src/actions/parcelsActions.ts
- frontend/src/features/properties/containers/ParcelDetailFormContainer.tsx
Presently it is impossible to click the Submit button a second time when saving properties because the `rowVersion` isn't updated correctly.
- Note: this does not fix a more complex problem when attempting to save financial values in the second submit.
> Fixed RowVersion on Second Submit

- frontend/src/features/properties/list/PropertyListView.tsx
Was previously passing existing filter instead of the default values so reset was not working as intended
> Fix inventory list view not resetting properly

- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- look for exact match with users input before select closest
- do not overwrite selected value if chosen from the list
- added display additional back to the location filter when results cap out
> Location hotfix

- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
Fix that ensures the `agency.value` is being sent on subsequent requests with the filter, ensure that name is changed on subsequent requests when the value is not equal to the existing formik value, account for various other scenarios where subsequent requests were previously causing bugs
> Agency filter hotfix

- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/forms/AppraisalCheckListForm.tsx
- frontend/src/features/projects/common/forms/DocumentationForm.tsx
- frontend/src/features/projects/common/strings.ts
- frontend/src/features/projects/common/tabs/ProjectInformationTab.tsx
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/spl/forms/CloseOutFinancialSummaryForm.tsx
- frontend/src/features/projects/spl/forms/CloseOutFinancialsForm.tsx
- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
- frontend/src/features/projects/spl/steps/SplStep.test.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
- frontend/src/features/projects/spl/tabs/CloseOutFormTab.tsx
- frontend/src/features/projects/spl/tabs/SurplusPropertyInformationTab.tsx
- Remove "Loan Terms" 
- Rename "Sales History Notes" to "OCG Variance Notes", move to OCG section, add tooltip
- Move "Project Comments" to Financial Summary section
- rename "Appraisal Notes"
- Remove "Shared Notes"
> PA-1969 Reconfigure Disposal Projects notes fields

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/components/maps/leaflet/Spiderfier.ts
- frontend/src/typings/tiles-in-bbox/index.d.ts
- Only make api request when filter is changed and use full bc map bounds to calculate tiles for the filter
- Using map onmoveend to track bbox used to calculate clusters in supercluster (fix bottom 10-15% data not showing and Victoria are data)
- Hide parcel pins that have buildings
> PIMS inventory features loading performance optimization

- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
Picking some low hanging fruit while I'm figuring out the others..
- add `Surplus Active` back as an option on the `Classification Form`
> PA-2491: Add Surplus Active back

- backend/dal/Migrations/v01.06.01/Down/PreDown/RemoveRolesAndClaims.sql
- backend/dal/Migrations/v01.06.01/Up/PostUp/AddRoleAndClaims.sql
The DB Migration v01.06.01 scripts were invalid.  I have updated them to resolve the issue.
You may not need to refresh your DB, or perhaps you may.
> Fixed v01.06.01 DB Migration

- frontend/src/components/maps/leaflet/InventoryLayer.tsx
Bare land wasn't showing up because buildings no longer have a single link to a parcel `building.parcelId`.  We're going back to showing all land parcel pins.  We can reevaluate when we have more time.
> Show all land pins

- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.scss
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
Default to Surplus Active in the Select Properties step when creating a Disposal Project with ability to select all. 
Worked through this ticket and matched up to the acceptance criteria, just wondering if it may be a little confusing having an additional classification filter below? They both work together but just had that thought when I was testing it myself. [Link to story](https://pimsteam.atlassian.net/browse/PA-2463?atlOrigin=eyJpIjoiY2FmMTZhYzFhNDFhNDgxZmIwZGJlMjIzZTg5YmRmNTYiLCJwIjoiaiJ9)
> PA-2463: Default to SA and ability to select all

- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
Allow SRES users to update/add a property on behalf of another agency. Previously it was overriding the frontend with the user's agency. It now checks to see if they are an admin in ParcelService and BuildingService before locking it to the user's agency. Also initial values were previously overwriting the agency value to the keycloak value so that is now changed as well.
I found some existing bugs throughout this process that I will log and attempt to fix outside of this ticket:
- Agency dropdown for land only contains parents 
- Slide out does not always instantly populate the Owning Agency but will appear after clicking away and back
> Allow SRES to change on behalf of another agency

- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
Users can now delete properties from sub-agencies.
The delete button should appear during view and edit.
Corrected permission on building delete from `property-edit` to `property-delete`.
Please note that there are still some issues that revolve around the map, info side-bar and the submitting of new properties and deleting of properties.  They are often out of sync for a minute or two.  Clicking around and retrying solves this.  This indicates implementation issues with one or more of the following - caching or state.  This is a larger problem and can't be resolved before Sprint Review however.
> PA-2640 Fixed Delete Property

- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
The delete and edit buttons were not visible for SRES users on the Inventory Forms.  This appears to have been the result of a misplaced end bracket and auto-save reformatting.
> Fixed edit/delete buttons

- backend/api/appsettings.Local.json
Just discovered that the `.env` files that have blank values (i.e. `Key=`) are ignored for some reason.  This ensures the secret value is blank for debugging locally.
> Fixed Local Config

- backend/api/Areas/Property/Models/Building/BuildingEvaluationModel.cs
- backend/api/Areas/Property/Models/Building/BuildingFiscalModel.cs
- backend/api/Areas/Property/Models/Parcel/BuildingEvaluationModel.cs
- backend/api/Areas/Property/Models/Parcel/BuildingFiscalModel.cs
- backend/api/Areas/Property/Models/Parcel/ParcelEvaluationModel.cs
- backend/api/Areas/Property/Models/Parcel/ParcelFiscalModel.cs
- backend/api/Areas/Tools/Models/Import/BuildingEvaluationModel.cs
- backend/api/Areas/Tools/Models/Import/BuildingFiscalModel.cs
- backend/api/Areas/Tools/Models/Import/ParcelEvaluationModel.cs
- backend/api/Areas/Tools/Models/Import/ParcelFiscalModel.cs
- backend/api/Models/Building/BuildingEvaluationModel.cs
- backend/api/Models/Building/BuildingFiscalModel.cs
- backend/api/Models/Parcel/BuildingEvaluationModel.cs
- backend/api/Models/Parcel/BuildingFiscalModel.cs
- backend/api/Models/Parcel/ParcelEvaluationModel.cs
- backend/api/Models/Parcel/ParcelFiscalModel.cs
`float` has a precision of 6-9 digits while `decimal` has 28-29 which will handle the large financial values correctly. Could always go with a `double` as well if that is preferred (15-17)
> PA-2679: Fix backend erroneously rounding values

- frontend/src/components/Table/PageSizeSelector.tsx
- frontend/src/components/Table/Table.scss
- frontend/src/components/Table/Table.tsx
- frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/projects/common/components/PropertyListViewSelect.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.scss
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
Originally had just implemented a **Show All** option like the story suggested; however, there was no way to get back from Show All state to reduce the list size (based off UI) so I thought it may be better to just allow them to choose from multiple options with the `PageSelector's` existing functionality in case they want to jump between sizes. 
Confirmed this was ok with Bobbi!
> PA-2482 Allow row increase in select properties

- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
- frontend/src/features/mapSideBar/hooks/useSideBarBuildingLoader.tsx
- Fixes bug where clicking 'Add a building" after viewing a building loaded the old building values
> "Add new building": ensure form is empty

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/properties/filter/IPropertyFilter.ts
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/utils/YupSchema.ts
Validation for ERP or SPL Checkboxes now make them required **ONLY** when searching with the Surplus Properties Filter
> PA-2635: ERP or SPL Checkbox now required

- frontend/src/components/maps/leaflet/InfoSlideOut/AssociatedBuildingsList.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
Basically the problem was that if you had the associated buildings list open and then clicked a building pin, it would try to open a non-existent list of buildings for that building.
This is just a small/temporary fix, next sprint I have a story to add an associated land tab so I'll need to rethink some of the logic anyways
https://user-images.githubusercontent.com/33818575/107837521-07c68d80-6d56-11eb-87d2-295b939b054d.mp4
> Fixt slide out bug

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
Users cannot filter by agencies they don't have access to.  This enforces their need to contact SRES about properties.
> PA-2670 Limit Agency Filter

- frontend/src/components/common/form/ParentSelect.tsx
So there was a line tucked away that was checking the value of the status against the `parentId` instead of the value of the item's parent. It just happened to work still because those values shared the same number id's as the parent. But caused that weird bug we were seeing before. The headers will now correctly stay in place.
Highlights the readability issues of this component, not a huge fan of my implementation. Adjusted some variable names to try and be more clear.
> PA-2115: Project status filter Fix

- backend/api/Areas/Reports/Controllers/PropertyController.cs
- backend/api/Areas/Reports/Mapping/Property/AllFieldsPropertyMap.cs
- backend/api/Areas/Reports/Models/Property/AllFieldsPropertyModel.cs
- frontend/src/features/properties/list/PropertyListView.tsx
New export button and report for SRES/SRES Financial Manager. This report contains some additional fields that the basic report does not.
Few things to note: 
- The story asked for all information we had, I did not include the numeric values for classifications etc as I assumed this was not desired. Please correct me otherwise!
- I believe I have pulled in all relevant fields outside of what I mentioned above - hard to confirm as I did not have a list to reference other than the property entity itself (did my best to choose what is relevant). So if one looks like it's missing let me know
> PA-2528: Export additional fields for SRES

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/features/projects/common/components/PropertyListViewSelect.tsx
- frontend/src/features/projects/common/forms/GreTransferForm.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx
- frontend/src/features/projects/erp/forms/AgencyInterest.tsx
- frontend/src/features/projects/erp/steps/GreTransferStep.test.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/map/MapView.tsx
Disabled agencies and other lookup codes shouldn't be selectable when they have been disabled.  There is a lot of tech-debt related to this issue, as we haven't correctly applied the rules.
- Disabled lookup codes shouldn't be displayed as a selection option
- If an existing entity uses the disabled lookup code, then it should still be able to show that lookup code.
> Fix disabled agency

- backend/dal/Services/Concrete/ProjectService.cs
Always seems to be one liners...
`project` does not have workflow in its context while `originalProject` does. This caused `IsProjectInDraft` to throw a null workflow error everytime
> Delete project bug fix

- frontend/src/components/maps/leaflet/Map.tsx
`isEmpty(true)` returns `true` which caused an issue for when we set our filter changed state. The issue would occur when either the ERP or SPL checkbox was checked as even if the first half of code resulted in them not being equal, the second half would evaluate to true even though they are not "empty". i.e) `isEmpty(true) && isEmpty(undefined)` evaluates to true
> Logic fix for filter changed

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- frontend/src/constants/workflows.ts
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/columns.tsx
- frontend/src/features/projects/list/interfaces.ts
Only projects that are still in the `SUBMIT-DISPOSAL` workflow can be deleted. The delete icon will appear next to a project if that condition is satisfied AND the user 
- has a `project-edit` claim
- or an `admin-projects` claim
- or they created that project
> Delete Project Adjustments

- frontend/src/components/maps/leaflet/mapUtils.tsx
Purple pin now checks for the existence of project number(s) as well as the Surplus Active/Encumbered classification
> PA-2589: Purple pin appearing when it shouldn't

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/propertyTypeNames.ts
- frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
- frontend/src/features/mapSideBar/hooks/useQueryParamSideBar.tsx
- frontend/src/features/projects/common/components/FilterBar.tsx
- frontend/src/features/projects/common/components/columns.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx
- frontend/src/features/properties/components/forms/strings.ts
- frontend/src/features/properties/filter/PropertyFilter.test.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/columns.tsx
- frontend/src/features/properties/map/MapView.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/hooks/useLookupCodes.tsx
- frontend/src/utils/index.ts
- frontend/src/utils/mapLookupCode.ts
- frontend/src/utils/utils.ts
Property Classifications will now use the commonly shared hook `useLookupCodes()`.  Additionally based on permissions the correct classifications will be displayed.
> PA-2707 Fixed Property Classifications

- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
Originally the project import would attempt to link projects to properties by parsing the notes.  The import will no longer do this as it wasn't adding value.
> PA-2807 Removed link to project properties

- frontend/src/components/common/form/ParentSelect.tsx
I originally did not think this was a bug because every agency came back when I searched for it, but by default when scrolling through (with no filter applied to the list) not every agency would show up. Mikaela created a bug for us to display everything, so all I had to do was change the `maxResults` to the length of the `options` so they get rendered within their groups all at once
> PA-2788: Dropdown not displaying all results

- frontend/src/components/Table/Table.tsx
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/features/admin/agencies/__snapshots__/ManageAgencies.test.tsx.snap
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingValuationForm.test.tsx.snap
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/dispose/forms/__snapshots__/PropertyListViewSelect.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
- frontend/src/features/projects/erp/tabs/__snapshots__/EnhancedReferralTab.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/splReports/columns.tsx
- frontend/src/features/splReports/components/ReportForm.tsx
- frontend/src/features/splReports/components/SplReportLayout.scss
Rather than try to build some workaround to get only the headers to align right, I just aligned the columns left
> PA 2607 Align SPL report headers and fields

- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ProjectNumberLink.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ThreeColumnItem.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/components/maps/leaflet/mapUtils.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/IdentificationForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ParcelIdentificationForm.tsx
Display appropriate project number(s) in property info panel
- if an admin clicks the link it will go to the project status route
- link goes to summary if project has been submitted and user is in the same agency
- link goes to project status route if it is still in draft and user is a part of the agency
- if user is outside of the agency and not an admin the numbers will not be clickable 
Updated:
- land, associated land, and building review pages now have project number(s) with appropriate links
- also included when viewing the info screen
- fixed bug where lat and long was not being stored when a marker was clicked
- fixed another bug where the project workflow information was not being read correctly because the data shape was changing
> PA-2809, 2808, 2813, 2811, 2812, 2810: Project number link related stories 

- backend/dal/Services/Concrete/ProjectService.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/features/projects/common/components/FilterBar.tsx
- frontend/src/features/projects/common/forms/ProjectDraftForm.tsx
- frontend/src/features/projects/dispose/hooks/useStepper.ts
- frontend/src/features/projects/dispose/steps/ProjectDraftStep.test.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
On submit and edit project the ability to change the projects agency so that I can submit properties on their behalf 
User has to be at the Ministry Level to be able to do this. They can only select their agency or sub agency
OR 
If they are SRES they can select any agency or sub agency 
PROPERTIES in the list must belong to the selected agency
> Allow parent agency users and SRES users to set project agency

- backend/dal/Services/Concrete/ProjectService.cs
- frontend/src/features/projects/erp/forms/EnhancedReferralCompleteForm.tsx
- frontend/src/features/projects/erp/forms/ExemptionEnhancedReferralCompleteForm.tsx
- frontend/src/features/projects/erp/forms/erpYupSchema.ts
- frontend/src/features/projects/erp/steps/ErpStep.test.tsx
- frontend/src/utils/utils.ts
Disposal Projects will only require the `ClearanceNotificationSentOn` date if they are in ERP.
Disposal Projects that are in other status like **Not in SPL** will not require the value.
This should allow some historical projects to bypass this validation.
> PA-2854 Disposal Project Clearance Notification

- frontend/src/features/properties/filter/PropertyFilter.tsx
- Non sres user cannot specify which agency just set it to undefined and `includeAllProperties` when searching surplus filter 
- If sres user they can adjust the agency filter with `includeAllProperties` set to true
Something to confirm, will a user (ex. REM) want to do the SPL/ERP filter with `includeAllProperties = false`? Will have to adjust if this is the case. The Surplus Filter and Property Filter have the same initial values so some more logic will have to be added.
> Default to includeAllProperties in Surplust Filter

- openshift/4.0/templates/api/deploy.yaml
- openshift/4.0/templates/app/deploy.yaml
- openshift/4.0/templates/database/mssql-deploy.yaml
Change deployment configuration to use `Recreate` instead of `Rolling` for the database.  This is because the database will fight over the database file when a new pod starts up.
> Database DC changed Rolling to Recreate

- frontend/src/features/projects/erp/forms/EnhancedReferralCompleteForm.tsx
- frontend/src/features/projects/erp/forms/ExemptionEnhancedReferralCompleteForm.tsx
Removed some of the required attributes on inputs to allow **Not in SPL** to go to **Disposed**.
> PA-2875 Updated Not in SPL to Dispose

- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelAttributes.tsx
Making sure the slide out is displaying correct information. Had to verify the keys were the appropriate type before pulling that value.
Additionally, it used to sum up each building and display the cumulative value but now it takes straight from the `Improvements` of the developed land. 
Updated: 
- only take values from current year if present (previously most recent)
> Fix slideout improvements/assessed

- backend/api/Areas/Notification/Controllers/TemplateController.cs
- backend/ches/ChesService.cs
- backend/ches/Configuration/ChesOptions.cs
- backend/dal/Services/Concrete/NotificationTemplateService.cs
- backend/dal/Services/INotificationTemplateService.cs
- backend/entities/NotificationQueue.cs
- backend/notifications/NotificationService.cs
- backend/tests/unit/api/Controllers/Notification/TemplateControllerTest.cs
- backend/tests/unit/api/Routes/Notification/TemplateControllerTest.cs
Adding a configurable delay to all notifications.
Providing a way to test `to`, `cc`, and `bcc` notifications.  This may allow us to debug production email issues as we can send emails and place them in a queue for a length of time where support resources can review the test emails.
> PA-2948 Debugging Notifications

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
This filter was working on its own (ie. without SPL/ERP filter applied); however, started failing when the two were used together.
I spent a couple of hours trying to get the join to work but it seems as if it was failing due to the attempt to join an in-memory collection with EF. 
This was the only working solution that I could find, let me know if it is efficient enough.
> Land only filter fix

- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
- backend/dal.keycloak/Pims.Dal.Keycloak.csproj
- backend/dal.keycloak/PimsKeycloakService.cs
- backend/tests/core/TestHelper.cs
- backend/tests/unit/dal/Libraries/Keycloak/KeycloakServiceGroupsTest.cs
- backend/tests/unit/dal/Libraries/Keycloak/KeycloakServiceRolesTest.cs
- backend/tests/unit/dal/Libraries/Keycloak/KeycloakServiceTest.cs
- backend/tests/unit/dal/Libraries/Keycloak/PimsKeycloakUserServiceTest.cs
While still not ideal, I am hoping the removal of all groups and then adding back the relevant ones will resolve the issues we're seeing.  Ideally if the requests to keycloak fail PIMS will also not be updated.  Which will allow us to keep them in sync better.
> PA-2708 Fixed Keycloak User Administration

- frontend/src/components/maps/hooks/useSupercluster.test.tsx
- frontend/src/components/maps/hooks/useSupercluster.ts
- frontend/src/components/maps/leaflet/PointClusterer.tsx
Allow zoom to the map results after search and avoid cluster splitting before zoom is done.
> disable clustering until after zoom is done

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/list/PropertyListView.tsx
Search button will now always fire filter changed event, and inventory list view will now correctly stay on the appropriate `propertyType` tab after applying a filter
> PA-2634, PA-2886: Filter bug fixes

- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/ParcelIdentificationForm.tsx
- frontend/src/features/properties/components/forms/subforms/InformationForm.tsx
Now if a user is a member of a parent ministry when submitting inventory they will have the option to select any of its children. Re-used logic from the Disposal Project section.
Agency field is locked if they are not an admin AND the user's agency is not a parent agency. And lastly the disabled prop from the parent.
> PA-2851: Submissions on behalf of child agencies

- frontend/src/components/common/form/ParentSelect.tsx
Adding the conditional `<b>` tags was throwing the following error (thanks Devin for finding this)
`‘Warning: Failed prop type: Invalid prop children of type object supplied to Highlighter, expected string.\n in Highlighter (at ParentSelect.tsx:184)\n in InnerPopper (created by Context.Consumer)\n in Popper (created by Overlay)\n in Overlay (created by RootClose)\n`
Tried using `highlightClassName` originally but it was not working so I just created a conditional class-name and a styled component to apply the bold in the appropriate locations.
> Console warning fix

- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- backend/tests/unit/dal/Services/ParcelServiceTest.cs
- frontend/src/components/Table/ColumnFilter.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/utils/YupSchema.ts
Validation now more detailed for type error if it occurs, and allow REM's to submit on behalf of a child agency if they are a part of a parent agency.
> Bug fixes for submitting on behalf on child agency

- backend/ches/ChesService.cs
- backend/core/Http/HttpRequestClient.cs
- backend/tests/unit/dal/Libraries/Ches/ChesServiceTest.cs
CHES has a few issues/behaviours that have been discovered.
- Attempting to cancel a message that can't be cancelled throws an error 409.
- Attempting to request the status of a message after cancelling it times-out with a 504.
- HTTP Request and CHES library have been updated to only deserialize JSON data.
- A request for the status of the message will be sent to determine if it can be cancelled, instead of just sending a cancel message and then asking for the status.
> Fix CHES cancel response

- backend/dal/Migrations/v01.10.04/Up/PostUp/01-Agencies.sql
I have rolled back DB migration `v01.10.04` in **DEV** and **TEST**.   This PR updates this DB migration so that when it is applied again it will do the following;
1) Change ownership of properties from "TRAN", "PLMB", "TIC" to "BCTFA"
2) Change ownership of projects from "TRAN", "PLMB", "TIC" to "BCTFA"
3) Move all TRAN users to the "TRAN" ministry instead of sub-agency
4) Delete sub-agencies "PLMB" and "TIC"
> Note that users will need to be updated manually after this migration so that they reference the correct agencies (see below).
The only issue in the prior bug fix was that it was also moving properties from "BC Transit" to "BC Transportation Financing Authority".  I have removed that part of the migration.
> Fix TRAN agencies

- frontend/src/features/help/constants/HelpText.tsx
The email address is incorrect on the PIMS Ask For Help feature.  The email address should be:
citz_rpd_imit_help@gov.bc.ca
> Updated dest email for pims support (PA-14).

- backend/ches/ChesService.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/notifications/NotificationService.cs
When notification cancellations fail, so does cancelling a project.  Currently the main issue for this is because there are projects that created notifications in the prior version of CHES, which do not exist in the current version.
This fix will ignore the specific error response from CHES for missing notifications (404).  This isn't an ideal solution, but one that will resolve current issues.
I have notified the Common Services team of their design implementation issue regarding returning a 404 for a valid endpoint and a missing message.  They should be returning a 204, or a 200 with an empty array like they do for other endpoints.
> PIMS-6 Fix Cancel Notifications

- frontend/src/features/projects/erp/steps/ErpStep.scss
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/tabs/ErpTabs.tsx
Allow the SPL tab to be accessible by other statuses for the case of a project transitioning to another status and needing to view previous data.
- Width was slightly adjusted to accommodate for the extra tab (was previously stacking tabs when closeout form tab was included)
> PIMS-18: Allow SPL tab to be accessible by other statuses 

- backend/api/Areas/Reports/Mapping/Property/PropertyMap.cs
- backend/api/Areas/Reports/Models/Property/PropertyModel.cs
There might be a better way to get the project number into the report without the brackets, as it's currently an array.
[pims-inventory (11).xlsx](https://github.com/bcgov/PIMS/files/6718314/pims-inventory.11.xlsx)
> SPP Number on Inventory Export

- frontend/src/features/projects/common/ProjectSummaryView.tsx
- frontend/src/features/projects/common/tabs/ProjectInformationTab.tsx
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
- frontend/src/features/projects/spl/tabs/SurplusPropertyInformationTab.tsx
2 little tweaks in this PR
**1.** Add tabs to cancelled projects so user's can browse previous information regarding the project
**2.** Add shared notes back to project information, and rename Agency Notes -> Notes to avoid confusion
> Add tabs to cancelled projects, and shared notes back to project information 

- backend/dal/Migrations/v01.11.00/Up/PostUp/01-NotificationTemplates.sql
Updating the notification that is currently sent to the owning agency when the shared note is changed to send to the user who created the project instead.
To apply this change to DEV I will need to rollback the migration and then reapply.
> Update Notification Audience

- frontend/src/features/projects/assess/forms/ReviewApproveForm.tsx
Prior to this change `isReadOnly` would always be set to true from this state unless an error occurred and it would then check the value of `canEdit`. It now defaults `isReadOnly` to the inverse of `canEdit`.
As `isReadOnly` was always true the expression for whether the child components were disabled was `isReadOnly || !canEdit` which was previously always evaluating to true.
> PIMS-26 - Edit before project approval

- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
I was originally working on a modal for this but this is the quickest fix - if we want to use a modal please let me know and I will happily switch it. 
Users were getting confused when entering a valid PIN and no response was returned, in order to further enter information on desired property they would have to manually drop the pin and continue the process. Added some clarification text to the "error" toast that is currently appearing when this scenario happens.
> PIMS-35: Toast adjustment for more clear instructions

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
Downloading the report as an excel file sets the `filter.SPLWorkflow` to true, this was previously only ensuring cancelled SPL projects were not included but it now checks for `Transferred within the GRE` as well. This was already working on the graphical interface, just needed an update to the excel reporting.
> PIMS-20: Exclude T-GRE from SPL Reports

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
It looks like there's a bug which occurs if someone who is not the "initiator" or creator of the project approves the project, the CreatedById gets overwritten by the updater of the project.
I think there was a copy and paste error in the code...
> PIMS-42: The project initiator doesn't seem to be getting the "Project Owner" notifications

- frontend/src/features/projects/erp/forms/AgencyInterestColumns.tsx
Change to the AgencyInterestColumns condition in order to hardcode the proper values to display to a user.
> PIMS-40: Issue with different information for same project for different users

- backend/api/Controllers/AuthController.cs
- backend/api/Helpers/Authorization/RealmAccessRoleRequirement.cs
- backend/api/Models/Auth/UserModel.cs
- backend/core/Extensions/IdentityExtensions.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/PIMSContext.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/dal/Services/Concrete/UserService.cs
- backend/dal/Services/IUserService.cs
- tools/keycloak/sync/SyncFactory.cs
With the change to the User entity that now links to Keycloak through a separate property `KeycloakUserId` instead of the `Id`, additional changes needed to be made to support this.
DEV continued to work correctly because the `Id` and `KeycloakUserId` are identical values, however in TEST it will have different values based on what has been imported.
A better solution than the one I implemented would be to add the PIMS `User.Id` to the claims found in Keycloak to reduce the need to make an additional query/connection to the database for the `User.Id`, however this will take more time and requires additional updates to Keycloak.
> PIMS-46 Use KeycloakUserId

- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
Fixing bug with prior PR to use the `User.KeycloakUserId` property when performing PIMS user management and syncing.
> Fix Keycloak user management

- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
When updating users with the PIMS User Admin UI, it fails to be able to update Keycloak because it is apparently using the wrong Id.  The mapping should be correct, but for some reason it appears like it may not be.  I've manually ensured the correct GUID is used and will need to test once released.
> PIMS-46 Fix Keycloak user update

- frontend/src/features/projects/common/ProjectSummaryView.tsx
Fixing layout of the Project Summary form to show tabs when viewing a project whose status has changed to Transfer within GRE. This will allow Maggie to see the history of the T-GRE project and other project information and details.
> PIMS-48: SPP-11023 - Transfer within GRE - can no longer see Private Notes

- auth/keycloak/config/realm-export.json
This will enable new local instances of keycloak to be setup with DEV as an identity provider more quickly.  They will still need to manually update the identity provider secret, but everything else should be auto-configured.
> Add DEV identify provider

- backend/Dockerfile.migrations
The upgrade to .NET5.0 also needs the DB migration Dockerfile to be update appropriately.  This should resolve the devops issue.
> Fix db migration dockerfile

- frontend/src/components/maps/hooks/useActiveFeatureLayer.tsx
- frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
- frontend/src/components/maps/leaflet/LayerPopup/hooks/useBoundaryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/properties/hooks/useGeocoder.tsx
- frontend/src/hooks/useEnvironment.ts
- openshift/4.0/templates/app/deploy.yaml
Nginx doesn't natively provide a way to include environment variables in our React application.  This PR provides a way that will look for a `environment.json` file and make it accessible through a useEnvironment() hook.
Openshift deployment configuration has been updated to include a ConfigMap that generates this `environment.json` file for each environment.
> Add environment variables to nginx

- openshift/4.0/pipelines/Jenkinsfile.cicd
Presently it's impossible to force a build if files don't change, which results in never deploying.
This change will always build and always deploy when running the pipeline.
> DevOps always build

- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.test.tsx
- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
moving the axios component as a "global" object in the userLayerQuery.tsx, adding error handling within this component for situations where there maybe 403 response codes from a map layer request.
> PIMS-24 - Adding error handling in layer query

- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- openshift/4.0/templates/sonarqube/deploy.yaml
using the lts-enterprise image from sonarqube: https://hub.docker.com/_/sonarqube?tab=tags
I believe the version is v8.9.6, and I'm assuming enterprise is the one to use.
Also modified the deployment strategy from rolling to recreate and added a longer timeout:
recreateParams:
timeoutSeconds: 9600
> Fix for log4j to upgrade Sonarqube

- frontend/src/features/properties/list/PropertyListView.tsx
I've disabled validation on the assessed land field now which allows the editing and saving of financial values in the building view mode.
I noticed that there are a couple other minor bugs which can be addressed at a later date, one is that after saving a financial value, the lot size value switches to display "NaN". 
The value is still there, as we can switch to the parcels view and then back and the value is there, it's just not getting displayed when you click save for some reason. Maybe something to do with the state?
The other issue is that after saving your edits, if you click the cancel button to get out of "edit" mode, the assessed building value for the record/s that was changed goes to 0:
Just click the parcels view and then come back to the buildings view and the values will …
> PIMS-80: Property list building view financials not saving

- frontend/src/features/properties/list/PropertyListView.tsx
The lot size was getting displayed to 0 after saving a building in the property list view.
Changed landArea to totalArea in the PropertyListView.tsx file.
I might have found another bug which occurs after you save a record, then you click "cancel" which displays the edited and saved record:
but if you go back to edit again then the previous values get displayed again for some reason (possibly due to a state?).
If you click cancel again, the saved values reappear:
> PIMS-80 - fixing lot size issue

- backend/dal/Migrations/v01.15.00/Down/PostDown/01-NotificationTemplates.sql
- backend/dal/Migrations/v01.15.00/Up/PostUp/01-NotificationTemplates.sql
Modified the notification templates to update sqft to Sq. M and rollback the previous changes that had sqM.
> Pims 81 - Rollback sqM to sqft and update sqft to Sq. M

- frontend/src/components/maps/leaflet/InfoSlideOut/BuildingAttributes.tsx
When a building contains more than one evaluation/assessment value, it seems that the existing code for sorting the values was "mutating" the array which caused the Cannot assign to read only property '0' of object '[object Array]' error.
Adding slice() method before the sort method which creates a copy of array seems to fix the issue, tested creating multiple assessments on buildings locally and it seems to work.
> PIMS-100: Property Inventory Management System  Building slide out on the map issue on buildings with more than one evaluation.

- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
removing the filter on the surplus active drop down.
> PIMS-112: Surplus Active classification option missing from drop down

- backend/dal/Services/Admin/Concrete/UserService.cs
Right now, there is no easy way to select all subagency users belonging to a parent agency and there is a limit of 50 users when exporting to excel. This PR will change the way the filter works so that if you select a parent agency such as Education, it will return all Education users including all users whose parent agency belong to Education such as all the school district users.
> PIMS-90: Export list of Users not working 

- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useLookupCodes.tsx
Included the code which calls the lookupcodes that populates the drop downs for the filter bar at the top of the page.
Removed a couple more debug lines.
Am able to see the drop down lists for Agencies, locations, and classifications now from the View Property Inventory page.
> adding the lookupcodes hook to the propertylistview page

- frontend/src/components/common/form/StepForm/SteppedForm.tsx
- frontend/src/features/properties/list/PropertyListView.scss
Adding 4 styles to the filter bar and fixed forwardref error on SteppedForm.tsx-->FAWindowclose on the View Inventory Property page.
> Fixing view property inventory page

- frontend/src/components/layout/AppNavBar/AppNavBar.scss
- frontend/src/components/layout/Header/Header.scss
- frontend/src/components/layout/Header/Header.tsx
- frontend/src/features/admin/agencies/ManageAgencies.scss
- frontend/src/features/help/components/HelpModal.tsx
- frontend/src/features/help/containers/HelpContainer.tsx
**Styling fixes** for **pims-63** branch since moving from **react-bootstrap 4 to 5** broke some components.
Fixes styling of **Header** bar and **AppNavBar**. 
Fixes **close button** in **HelpModal** so it's white again.  
Adds padding to the bottom of the Administration > **Agencies page** so the page navigation is visible in 100% browser zoom (This was also an issue in dev, not just pims-63).
**Known Issue:** The Help Modal button's tooltip is a bit off center and the arrow from the tooltip isn't the right color. If you know how to fix this please let me know.
Fixes [PIMS-351](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-351)
> Pims-351 header styling tweaks

- frontend/src/features/properties/components/GeocoderAutoComplete.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/PropertyFilterOptions.tsx
Adding Geocoder search to the property filter bar.  When typing an address it needs to extract the administrative area if provided, and it also needs to apply the administrative area if selected from the dropdown.
Local testing and ran unit-tests.
> PIMS-307 Fix geocoder administrative area

- codecov.yml
Right now the Github PR's to the dev branch are being blocked due to the Codecov threshold limit being reached. 
This is to lower the code coverage threshold to 55% to hopefully bypass this threshold the next time we create a PR.
> Lowering code coverage 

- frontend/src/features/projects/list/ProjectListView.tsx
By default when viewing the "View Projects" page, the list will initially exclude projects whose statuses are either Denied, Transferred-GRE, Cancelled, or Disposed. The status filter would work when viewing projects on the webpage, but when exporting to excel you would not see these project statuses in the report.
This "initial" filter state in the ProjectListView.tsx component for "notStatusId" were being passed into the filter when exporting to excel in the ProjectExtensions.cs GenerateQuery function on line 91 which would essentially exclude these project statuses.
`if (filter.NotStatusId?.Any() == true)
{
query = query.Where(p => !filter.NotStatusId.Contains(p.StatusId));
}`
The fix was to "reset" the notStatusId in the PropertyListView.tsx, in the frontend, to an empty array when a …
> PIMS-356 - Excel export for specific property classifications not working (Disposed, Transferred in GRE etc..)

- backend/api/appsettings.Development.json
- backend/api/appsettings.Local.json
The dev pipeline is currently giving this error during the run-db-migration step in Openshift:
`Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.`
Trying to see if adding these new parameters to the connection string resolves the issue, based on this similar situation: https://github.com/dotnet/SqlClient/issues/1479
`TrustServerCertificate=True;MultiSubnetFailover=True`
[![](https://img.shields.io/badge/tickets_and_issues_this_solves-blue?style=for-the-ba …
> PIMS-612 - Fixing issue with dev pipeline

- frontend/src/components/maps/leaflet/LayerPopup/LayerPopUpContent.test.tsx
- frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
Removed populate property details hyperlink button.
- [PIMS-610](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-610)
- None listed.
Link no longer appears, tests pass.
> Remove 'Populate property details' hyperlink

- frontend/src/features/properties/list/PropertyListView.tsx
Filter on property inventory will default to sending Core Operational classification, make it default to empty string.
I have made changes to PropertyListView.tsx file to make sure by default, it will display empty string and if classification field has a value then it will display the string instead of the id. 
<br />
- [PIMS-683: Analytics fixes](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-683)
<br />
```
```
[TICKETS_AND_ISSUES]: …
> PIMS 683: Analytics fixes

- frontend/src/index.tsx
Provides a fix to the issue from updating keycloak-js. 
The warning about using old methods for class instantiation is now an error otherwise.
> keycloak hotfix - using update class instantiation

- frontend/package.json
- frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/utils/testUtils.tsx
[PIMS-140: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-140)
Updated react-leaflet to version 4.2.1
The parameter `onClose` for popups were removed. Need to use a ref now to track when it closes.
The `whenCreated` parameter was also removed from the Leaflet map, so it also had to be handled with a ref.
Current status:
~One test failing because only sees `mapInstance` as null.~
Test working now. The way to access the inner map has changed, and there isn't a lot of information out there about how to do this now that `whenCreated` is removed. There is a `useMap()` function that seems to work to get the inner map component of `MapContainer`. 
Finally found this here: https://stackoverflow.com/questions/65394203/leaflet-react-get-map-instance-in-functional-component
> - I have performed a …
> [PIMS-140] Update react-leaflet

- frontend/src/actions/parcelsActions.ts
- frontend/src/components/ltsa/Charges.tsx
- frontend/src/components/ltsa/LTSADialog.test.tsx
- frontend/src/components/ltsa/LTSADialog.tsx
- frontend/src/components/ltsa/OwnershipInformation.tsx
- frontend/src/components/ltsa/TitleDetails.tsx
- frontend/src/components/maps/leaflet/LayerPopup/LayerPopUpContent.test.tsx
- frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/components/tables/ChargeTable.tsx
- frontend/src/features/mapSideBar/components/tables/OwnershipTable.tsx
- frontend/src/features/mapSideBar/components/tabs/TabStyles.ts
- frontend/src/features/mapSideBar/components/tabs/TitleOwnership.tsx
[PIMS-200: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-200)Create LTSA dialog to be accessed from parcel popup.
Testing Instructions:
- Select a parcel from the parcel layer
- Click `LTSA Info` to view popup
> [PIMS-200] LTSA Parcel Popup

- frontend/src/features/properties/list/PropertyListView.test.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
As mentioned in Teams chat:
> If you edit a list of buildings from the View Inventory page, any entries that are updated will disassociate their connected land/buildings. 
> 
> I'm going to put in a PR for a temporary fix to hide the edit button on that page, so prod doesn't end up with a bunch of disassociated entries. It doesn't seem to be an issue when editing an individual entry from the sidebar, so users can still use that.
> 
> We can try to diagnose this later, but at first glance it doesn't look straightforward.
> - My changes generate …
> edit-button-hotfix

- backend/api/Areas/Property/Controllers/BuildingController.cs
- backend/dal/Services/Concrete/BuildingService.cs
- backend/tests/unit/api/Controllers/BuildingControllerTest.cs
- backend/tests/unit/api/Routes/Property/BuildingControllerTest.cs
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useApi.ts
[PIMS-227: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-227)
Issue:
When updating buildings from the View Inventory page, it was causing some fields, including associated land parcels, to be cleared or reset to default values. 
This was because that information is never loaded on the page and was therefore sent back to the API without it, which interpreted it as intentionally removed.
Changes:
- The route for updating financials was restored to only update the financials.
- Added an assignment to update the `ClassificationId` and removed the attempted update to `Classification`. `ClassificationId` is the foreign key and should be updated instead.
- Restored the edit button.
Testing instructions:
1. Identify a building with associated land. 
2. Go to the View Inventory page and edit that …
> [PIMS-227] Fix: Buildings disassociating from land

- frontend/src/features/projects/common/hooks/useStepForm.test.tsx
- frontend/src/features/projects/common/hooks/useStepForm.tsx
[PIMS-158: ](https://citz-imb.atlassian.net/browse/PIMS-158?atlOrigin=eyJpIjoiZDdhOWRmNGY1ZTg2NGFiZjg5YmViYzk3N2JlNGVjOTMiLCJwIjoiaiJ9)
I believe the original issue was caused by lack of permissions (local keycloak roles). Not an issue with the proper roles assigned. This is only an issue that will appear in local.
Decided to add additional feedback to the error message though.
Can test this by removing your Keycloak role (keep a minimal one) and trying to navigate through a step form, like Disposals. 
Original error:
Example of updated error: …
> [PIMS-158] Axios request failed error

- frontend/src/components/Table/ColumnFilter.scss
- frontend/src/components/Table/ColumnFilter.test.tsx
- frontend/src/components/Table/ColumnFilter.tsx
- frontend/src/components/Table/Table.tsx
[PIMS-96: ](https://citz-imb.atlassian.net/browse/PIMS-96?atlOrigin=eyJpIjoiMzgyZjgxNjZhNWY0NDYwMzg5MDc3MmIwMzRiZTg4ODIiLCJwIjoiaiJ9)
When on the View Inventory page, the filtering controls that exist in the table header were not behaving properly when cleared. Specifically, removing a filter from Classification or Location would not update the filter.
There were a few issues. 
- The useEffect in Table.tsx only ever set the filter with the props.filter passed in from the parent component. It didn't seem like that filter had the updated information.
- The values `administrativeArea` and `classificationId` were completely removed from the filter object when clearing the values from the table filter, but the filter needs empty strings, otherwise it will not override the existing value for …
> [PIMS-96] Table Filter Not Clearing

- frontend/src/features/properties/map/MapView.scss
The map didn't take up 100% of the height if you navigated there from View Inventory by clicking on a property. 
The .side-bar class didn't have a height property.
Height set to 100%.
> HOTFIX: Ensure map takes full height when sidebar is out

- frontend/package.json
[PIMS-351: ](https://citz-imb.atlassian.net/browse/PIMS-351?atlOrigin=eyJpIjoiOGFjNGJhZDhiOTU2NGY1OGE1OTMyOGIwNTA4ZThiZTciLCJwIjoiaiJ9)
Update @babel/traverse sub-dependency. This is mostly by `babel`, but also by `react-scripts` and `jest` somewhat. 
Any dependency trying to use a version less than 7.23.2 will now use 7.23.2 instead.
Tests appear to run fine. Builds with no errors. Navigated the site and didn't notice anything unusual.
> PIMS-351: Update @babel/traverse sub-dependency

- frontend/src/components/SearchBar/FindMorePropertiesForm.scss
- frontend/src/components/SearchBar/FindMorePropertiesForm.test.tsx
- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/components/SearchBar/__snapshots__/FindMorePropertiesForm.test.tsx.snap
- frontend/src/features/admin/users/components/UsersFilterBar.scss
[PIMS-336](https://citz-imb.atlassian.net/browse/PIMS-336?atlOrigin=eyJpIjoiOWQ3MDFmZDY0MDFmNGQwYWIwNDk4Yzk5YTRhYmU4MTQiLCJwIjoiaiJ9)
Converted the styled-components in this file to scss. Adjusted styling for a more uniform look.
Had to scope a class from UsersFilterBar.scss. It would apply to the styles on the Surplus Properties popup if a user navigated to the Users page and back.
> PIMS-336 Surplus Properties Popup Styling

- frontend/src/components/Table/ColumnFilter.test.tsx
- frontend/src/components/common/form/FastDatePicker.test.tsx
- frontend/src/components/layout/Header/Header.tsx
- frontend/src/features/admin/access/ManageAccessRequests.test.tsx
- frontend/src/features/admin/agencies/ManageAgencies.test.tsx
- frontend/src/features/admin/users/ManageUsers.test.tsx
- frontend/src/features/help/forms/BugForm.test.tsx
- frontend/src/features/help/forms/FeatureRequestForm.test.tsx
- frontend/src/features/help/forms/QuestionForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandSearchForm.test.tsx
- frontend/src/features/mapSideBar/components/tabs/BuildingDetails.tsx
- frontend/src/features/mapSideBar/components/tabs/ParcelDetails.tsx
- frontend/src/features/projects/assess/steps/ReviewApproveStep.test.tsx
- frontend/src/features/projects/common/forms/UpdateInfoForm.test.tsx
- frontend/src/features/projects/dispose/ProjectDisposeView.test.tsx
- frontend/src/features/projects/dispose/hooks/useStepper.test.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.test.tsx
- frontend/src/features/routes/LayoutWrapper.test.tsx
- frontend/src/utils/KeycloakEventHandler.test.ts
[PIMS-35: ](https://citz-imb.atlassian.net/browse/PIMS-35?atlOrigin=eyJpIjoiYWVkYTZiNDFjNjFmNDRhYjkyOTVjMWI5NmUyZWMxNGUiLCJwIjoiaiJ9)Resolve react-paginate warnings in jest tests
[PIMS-36: ](https://citz-imb.atlassian.net/browse/PIMS-36?atlOrigin=eyJpIjoiMDM2YzU1NWIxZWRiNGNhY2I2YjRlMWNhZmMwYzkwOTUiLCJwIjoiaiJ9)Resolve "relative pathnames are not supported in memory history" in jest tests
Started with fixing the issues mentioned in the above tickets:
- Paginate warnings were caused by react-paginate not liking when -1 is used as the starting page, but that's what the table pagination does. 
- Relative pathnames just needed a `/` before paths to make them correct. 
Added fixes:
- Updated a ReactDOM.render to a render from the testing-library
- Move a navigate to within a useEffect hook
- …
> PIMS-35/36 Fix Jest Test Warnings

- frontend/package.json
- frontend/src/features/admin/agencies/__snapshots__/ManageAgencies.test.tsx.snap
[PIMS-373: ](https://citz-imb.atlassian.net/browse/PIMS-373)
update @types/crypto-js from version `4.1.2` to `4.2.1`
> PIMS-373 update @types/crypto-js from version `4.1.2` to `4.2.1`

- backend/Dockerfile.ocp
> Pipeline test: removed temp comment from dockerfile BE

- frontend/src/components/SearchBar/FindMorePropertiesForm.test.tsx
- frontend/src/components/maps/leaflet/Legend/LegendControl.scss
- frontend/src/components/maps/leaflet/Legend/LegendControl.test.tsx
- frontend/src/components/maps/leaflet/Legend/LegendControl.tsx
- frontend/src/components/maps/leaflet/Legend/__snapshots__/LegendControl.test.tsx.snap
[PIMS-89: ](https://citz-imb.atlassian.net/browse/PIMS-89?atlOrigin=eyJpIjoiMjM3NjU4OTMxMWIzNDQxMmE4OTUxMjFlMTJjYTg1NTEiLCJwIjoiaiJ9)
Looked at removing/replacing the react-click-away-listener with something custom.
It was working in all situations except one, which was just a strange implementation, I think. 
Tried to write a custom one, which worked everywhere except the table filters. Ended up just keeping the existing package, as there's no strong reason to remove it at this point and it is working.
I'll include the custom code below for future use.
Also had to add console.error suppression for a recently updated test.
> - I have made corresponding changes to the …
> PIMS-89 Investigate Removing react-click-away-listener

- .github/helpers/jira-api/create_tickets.py
- .github/helpers/jira-api/jira_con.py
- .github/helpers/jira-api/refine_tickets.py
- .github/workflows/app-npm-dep-check.yml
[TES-795: ](https://citz-imb.atlassian.net/browse/TES-795)
Adding link to epic for parent task
1. go to the [Actions](https://github.com/bcgov/PIMS/actions) tab for the PIMS repo 
2. on the left menu select "[App NPM Dependency Updates](https://github.com/bcgov/PIMS/actions/workflows/app-npm-dep-check.yml)"
3. select the dropdown menu labeled "Run Workflow"
4. select the dropdown menu labeled "Branch: main"
5. select this branch: "TES-795-add-epic-field"
6. then select the green button labeled "Run workflow"
7. wait for all jobs to accomplish
8. check the backlog of [PIMS Jira board](https://citz-imb.atlassian.net/jira/software/c/projects/PIMS/boards/26/backlog)
9. There should be a new ticket labeled "Dependency Updates - <todays date>" that is linked to the Epic "NPM Dependency Updates" …
> TES-795 Update script to add connection to epic

- frontend/package.json
Example: PIMS-504:  Update typescript from version `5.2.2` to `5.3.2`                                   
[PIMS-504](https://citz-imb.atlassian.net/browse/PIMS-504)
> PIMS-504: Update typescript from version `5.2.2` to `5.3.2`

- frontend/package.json
[PIMS-502](https://citz-imb.atlassian.net/browse/PIMS-502?atlOrigin=eyJpIjoiMzI3NmM4MzIxMjUzNDMzMmI4Yzk4ZTRhZDNhNTQ2MjYiLCJwIjoiaiJ9)
Updates cypress to 13.6.0
I'm going to also create a ticket to remove Cypress. 
We're not using it. We have no tests that work for it. Playwright is likely going to be used instead.
> PIMS-502 Update cypress to 13.6.0

- express-api/.eslintrc.cjs
- express-api/constants/switches.ts
- express-api/express.ts
- express-api/jest.config.ts
- express-api/middleware/index.ts
- express-api/middleware/morganHttpLogging.ts
- express-api/package.json
- express-api/server.ts
- express-api/tests/integration/express/express.test.ts
- express-api/tests/unit/utilities/winstonLogger.test.ts
- express-api/tsconfig.json
- express-api/utilities/winstonLogger.ts
[PIMS-405](https://citz-imb.atlassian.net/browse/PIMS-405?atlOrigin=eyJpIjoiMzYwNDQ0MmE4NDBmNDUzOGExNzU0NTMxNDQ4NWRhZTMiLCJwIjoiaiJ9)
Decided to use both `morgan` and `winston` because they excel at different areas. `morgan` works with Express natively to get the details of http requests, which I don't see `winston` doing nicely. `winston` gives better output with more configurations, can replace console.log statements, and will be easier to eventually send to a service like Kibana if desired.
- Added `morgan` and `winston` logging packages.
- Created middleware that takes `morgan` http logs and uses `winston` to log as JSON to the console
- Switched the source of the TESTING env. It is now dependant on the NODE_ENV, which is automatically `test` when running Jest tests. This will prevent …
> PIMS-405 Add Logging to Express API

- backend/dal/Services/Admin/Concrete/UserService.cs
[PIMS-530:](https://citz-imb.atlassian.net/browse/PIMS-530) Error when trying to approve access requests
This ticket is to help debug the issue when trying to approve users that don't have any "roles".
We are currently unable to approve a user access request, because according to the application it's unable to retrieve the roles from Keycloak.
It looks like this is not the only user it happens to, but if a user doesn't have any roles, then we can't approve their access request using the access request page and get an error (see the Jira ticket for specifics). We are also unable to view or change the user's roles from PIMS. Strange thing is that the user can see his role, when clicking on the drop down by his username.
> - I have commented my …
> PIMS-530: Error when trying to approve access requests

- .github/workflows/api-lint.yaml
- express-api/.eslintrc.cjs
- express-api/.prettierignore
- express-api/jest.config.ts
- express-api/tests/integration/health/getHealth.test.ts
- express-api/tests/integration/middleware/headerHandler.test.ts
- express-api/tests/unit/controllers/healthController.test.ts
[PIMS-388](https://citz-imb.atlassian.net/browse/PIMS-388?atlOrigin=eyJpIjoiZjNjYjVjZjgwYjEzNDkzY2IyNzI3YjkwYzkwNzQ5YWUiLCJwIjoiaiJ9)
Provides a linting workflow that should run when PRs are opened or synchronized. 
If there are linting errors, the workflow check will fail.
Had to make some linting updates for errors that already existed.
> PIMS-388 Express Linting Workflow

- .github/helpers/deploy.sh
[PIMS-543: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-543)
Hot fix to handle the api and app differently on deployement
> Fix to handle Api and App deploy differently

- react-app/.eslintrc.cjs
- react-app/.prettierrc.cjs
- react-app/package.json
- react-app/src/App.tsx
- react-app/vite.config.ts
[PIMS-619](https://citz-imb.atlassian.net/browse/PIMS-619?atlOrigin=eyJpIjoiZWMxY2Q4OWJkODBkNDUxZjlhNDFjODM5NzRiNDA1N2IiLCJwIjoiaiJ9)
Adds ESLint and Prettier using similar configurations to our existing frontend.
Fixed some existing linting issues.
Same commands as the `express-api` to run linting.
- `npm run lint` to check everything
- `npm run lint:fix` to fix the easy stuff automatically
- `npm run check` to check only the prettier rules
- `npm run format` to fix the prettier rule violations
> PIMS-619 React App Linting

- .github/workflows/react-app-lint.yml
- react-app/.eslintrc.cjs
[PIMS-621: ](https://citz-imb.atlassian.net/browse/PIMS-621)
Add linting workflow for react-app folder
> Add workflow to lint react-app

- react-app/.babelrc
- react-app/jest.config.ts
- react-app/package.json
- react-app/src/App.test.tsx
- react-app/src/App.test.tsx.snap
- react-app/src/App.tsx
- react-app/src/pages/Home.tsx
- react-app/tests/__mocks__/imgMock.tsx
- react-app/tests/__mocks__/styleMock.ts
- react-app/tests/setupTests.ts
- react-app/tests/snapshotResolver.ts
- react-app/tsconfig.json
[PIMS-610](https://citz-imb.atlassian.net/browse/PIMS-620?atlOrigin=eyJpIjoiMDI5MzBmYmI1NmUxNGUzMDg4MDEyN2ZiMjhlZGVlOGQiLCJwIjoiaiJ9)
- Adds a testing framework to the new react-app component. 
> PIMS-620 Frontend Testing Addition

- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
[PIMS-1312](https://citz-imb.atlassian.net/browse/PIMS-1312?atlOrigin=eyJpIjoiMzU5ODQzZWVlOTI2NDNmNjgxYjJhZGI4MWU5NWIzZDEiLCJwIjoiaiJ9)
Fixes some bad styling of the encumbrance reason field. It was very narrow before.
- Specified minimum width and height for encumbrance field
- Removed some unneeded styled components, using just bootstrap layouts instead.
- Elements are now aligned into evenly-space rows.
Try submitting new parcels and buildings. Select the Surplus Encumbered classification to see this field.
> - My changes generate no new …
> PIMS-1312 Encumbrance Field Width

- openshift/templates/app-dc-template.yaml
Missing VITE_ prefix necessary for the app to detect it.
> Corrected vite env with prefix

- react-app/src/components/property/AddProperty.tsx
- react-app/src/hooks/api/useAdministrativeAreaApi.ts
- react-app/src/hooks/api/useLookupApi.ts
- react-app/src/hooks/usePimsApi.ts
Added hooks for obtaining various lookup values needed for the add property form. Also implemented them into the form itself.
> PIMS-1483: Lookup and Administraive Areas Hooks

- express-api/src/controllers/agencies/agenciesController.ts
- express-api/tests/unit/controllers/agencies/agenciesController.test.ts
Fixed an issue where the controller would incorrectly skip the own parent check if the ID was set to zero. 
In Javascript, `0 == false` so the line `if (updateInfo.ParentId && updateInfo.ParentId === updateInfo.Id)` would evaluate false in this scenario.
> Agencies Cannot Be Own Parent Zero ID Bug

- react-app/src/components/form/AutocompleteFormField.tsx
- react-app/src/hooks/api/useGroupedAgenciesApi.ts
[PIMS-1582](https://citz-imb.atlassian.net/browse/PIMS-1582?atlOrigin=eyJpIjoiNTkyYTBkNGQ3YWE3NGY4MDk0ZmRlODc2YjRmYjQwMDkiLCJwIjoiaiJ9)
- Autocomplete field now filters on the label again. Not sure when this originally broke.
- Noticed that child agencies weren't sorted. Changed sorting code to make this work.
- Play with the autocomplete fields (especially grouped agencies)
> PIMS-1582 Options Filter Fix

- express-api/src/typeorm/Migrations/1713814960226-UpdateIDSequences.ts
Fixed wrong coalesce from 0 to 1. Sequences can't start at 0, it's out of range.
> Fix for coalesce in Sequence Migration

- express-api/src/controllers/buildings/buildingsController.ts
- express-api/src/controllers/parcels/parcelsController.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/controllers/buildings/buildingsController.test.ts
- express-api/tests/unit/controllers/parcels/parcelsController.test.ts
[PIMS-1625: ](https://citz-imb.atlassian.net/browse/PIMS-1625) - Parcel and Building view details agency authorization
Adding authorization checks to prevent a user from viewing a parcel or a building not belonging to their agency.
To test you can try as a "General user" by editing the url and changing the id of the parcel or building to one that has an agency which doesn't belong to your user's agency.
> PIMS-1625: Parcel and Building view details agency authorization

- react-app/src/components/map/MapPropertyDetails.tsx
- react-app/src/components/map/ParcelMap.tsx
- react-app/src/components/map/ParcelPopup.tsx
- react-app/src/components/map/parcelPopup.css
- react-app/src/components/text/MetresSquared.tsx
- react-app/src/hooks/api/useParcelLayerApi.ts
- react-app/src/pages/DevZone.tsx
[PIMS-1590](https://citz-imb.atlassian.net/browse/PIMS-1590?atlOrigin=eyJpIjoiNTMwZWMyNzUwMGQwNGE4ZDg1OTFhOGM2YzgyN2M2ODciLCJwIjoiaiJ9)
- Fixed some styling issues with the MapPropertyDetails (MetresSquared fits in grids better)
- Added more info to view on the parcel layer popup
- Changed the state control for the popup so the map doesn't rerender upon click
- Added a PID list to the popup when a parcel has multiple parcels (aka a strata)
- Changed the hooks so they return more than one feature from the parcel layer
- Navigate to /dev and click on parcels
I noticed that there isn't often differences in the parcel layer data when many parcels are stacked, like in a strata.
This popup might benefit from some changes in UI if it seems too repetitive. I want to see how the LTSA and BCA data …
> PIMS-1590 Expand Parcel Layer Popup

- react-app/src/components/adminAreas/AdministrativeAreasTable.tsx
- react-app/src/components/map/parcelPopup/ParcelPopup.tsx
- react-app/src/components/projects/ProjectsTable.tsx
- react-app/src/components/property/PropertyTable.tsx
[PIMS-1682](https://citz-imb.atlassian.net/browse/PIMS-1682?atlOrigin=eyJpIjoiMTM3ODYyMWJjOWUzNDAxMWI3OGRlZTllMDI2NDYxZWYiLCJwIjoiaiJ9)
- Fixed issue with preset filter options
Plus....
- Standardized parcel wording to Land
- Added snackbar error messages in property and project excel exports
- Fix some areas where rendercell was used improperly, resulting in checkmarks all the time
- Fix bug on small map popup when there is no pid or pin on a shape
> PIMS-1682 Active Inventory Filter

- react-app/src/components/form/TextFormField.tsx
- react-app/src/components/map/ParcelMap.tsx
- react-app/src/components/projects/DisposalPropertiesSearchTable.tsx
- react-app/src/components/projects/DisposalPropertiesSimpleTable.tsx
- react-app/src/components/property/AddProperty.tsx
- react-app/src/components/property/PropertyDetail.tsx
- react-app/src/components/property/PropertyDialog.tsx
- react-app/src/components/property/PropertyForms.tsx
- react-app/src/utilities/formatters.tsx
[PIMS-1567](https://citz-imb.atlassian.net/browse/PIMS-1597?atlOrigin=eyJpIjoiY2QwMWZkMjVkN2YxNDA4OGEzYjM1NzI5MmI4YjI3MzAiLCJwIjoiaiJ9)
- Used pidFormatter utility where possible to make sure PID is always presented with hyphens
- Modified the PID text fields to format as values are typed in
- I felt this was a little hacky, but it seems to work.
- Addressed concerns with map on property pages not zooming/dragging. Users had an issue with accidentally zooming as they scrolled, so I added a prop that focus on that directly. Map on property pages now can zoom and drag, but not from scrolling.
- Added ParcelMap prop to hide the controls. Because they were moved out of the InventoryLayer, they were visible on pages that didn't load properties. This prop hides those controls if wanted.
- Find …
> PIMS-1597 PID Formatting & Map Adjustments

- express-api/src/services/notifications/notificationServices.ts
- express-api/tests/unit/services/notifications/notificationServices.test.ts
Fixed an issue where certain notification insertions were spawning new connections that would not be released upon function exit. This was happening because the queryRunner is an optional parameter to these functions, and it was not being passed in some instances of insertProjectNotificationQueue. There are a few functions that also take this as an arg, and I've applied the same fix to each so that the connection will be released when they spawn their own in the case of a missing arg. 
Admittedly, I don't know if we even need this arg if we don't want notifications wrapped into the same transaction block as the rest of the project update, but regardless this should no longer lock up the pool.
> - I have commented my code, particularly in …
> Notification services query runner maxing out conn pool fix

- react-app/src/components/projects/ProjectDetail.tsx
- react-app/src/components/property/PropertyDetail.tsx
[PIMS-1714: ](https://citz-imb.atlassian.net/browse/PIMS-1714)
Hiding the delete and edit buttons on the property details and the project details pages when the user has the "Auditor" role.
> PIMS-1714: Hide edit/delete buttons for Auditor Role

- express-api/src/constants/config.ts
- express-api/src/controllers/users/usersController.ts
- express-api/src/services/ches/chesServices.ts
- express-api/src/services/notifications/notificationServices.ts
- express-api/src/services/users/usersServices.ts
- react-app/src/pages/AccessRequest.tsx
Fixed some bugs in the access request notif generation service. Added…function calls for submitting notifications when a user submits an access request. Fixed a minor frontend issue causing the access request page to crash.
[PIMS-1719](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1719)
* Fixed some bugs in the access request notif generation service. 
* Added function calls for submitting notifications when a user submits an access request. 
* Fixed a minor frontend issue causing the access request page to crash.
* How to handle administrators under new role format? Previously notifications would be sent to "system administrators" plus relevant users that were both administrators and part of the same agency. Now everyone is just an administrator without differentiating systems level.
* …
> PIMS-1719: Send notifications for access request

- express-api/src/services/projects/projectsServices.ts
- express-api/src/typeorm/Entities/Project.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/services/projects/projectsServices.test.ts
[PIMS-1744 ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1744)
* Can now include an array of Monetary and/or Timestamps in the body of a PUT or POST request to projects to have those records upserted.
* Monetary and Timestamps now included in the response of the GET endpoint.
* Monetary and Timestamps are soft deleted when a project is soft deleted.
* Tests and factories updated to accommodate.
> PIMS-1744: Projects API support timestamps and monetary 

- react-app/src/components/adminAreas/AdministrativeAreasTable.tsx
[PIMS-1605: ](https://citz-imb.atlassian.net/browse/PIMS-1605)
removed initial state table length 10 for Admin Areas. Data grid has a length default of 100 and PO requested 100 as the set length for all tables. 
> PIMS-1605 - set table length to 100 

- express-api/src/controllers/properties/propertiesController.ts
- express-api/src/controllers/properties/propertiesSchema.ts
- express-api/src/routes/propertiesRouter.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/src/utilities/helperFunctions.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/controllers/properties/propertiesController.test.ts
- express-api/tests/unit/services/properties/propertyServices.test.ts
[PIMS-1799](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1799)
* Added new endpoint at `properties/`
* Added controller and service for query PropertyUnion view. Lets you filter and sort on all columns you might expect.
* Includes a change to the helper function for construction find options from the filter that makes us not need to manually correct the column alias. For whatever reason, `${alias}::TEXT ... ` breaks it, while `(${alias})::TEXT ... ` is perfectly fine.
> PIMS-1799: Property Union API

- express-api/src/controllers/lookup/lookupController.ts
- express-api/src/services/administrativeAreas/administrativeAreaSchema.ts
- express-api/src/services/administrativeAreas/administrativeAreasServices.ts
- express-api/src/services/agencies/agencyServices.ts
- express-api/src/services/buildings/buildingServices.ts
- express-api/src/services/parcels/parcelServices.ts
- express-api/src/services/projects/projectsServices.ts
- react-app/src/components/adminAreas/AddAdministrativeArea.tsx
- react-app/src/components/adminAreas/AdministrativeAreaDetail.tsx
- react-app/src/components/agencies/AddAgency.tsx
- react-app/src/components/agencies/AgencyDetails.tsx
- react-app/src/components/form/MultiselectFormField.tsx
- react-app/src/components/map/clusterPopup/ClusterPopup.tsx
- react-app/src/components/map/controls/FilterControl.tsx
- react-app/src/components/map/sidebar/MapSidebar.tsx
- react-app/src/components/projects/AddProject.tsx
- react-app/src/components/projects/ProjectDetail.tsx
- react-app/src/components/projects/ProjectDialog.tsx
- react-app/src/components/projects/ProjectForms.tsx
- react-app/src/components/property/AddProperty.tsx
- react-app/src/components/property/PropertyDetail.tsx
- react-app/src/components/property/PropertyDialog.tsx
- react-app/src/components/property/PropertyForms.tsx
- react-app/src/components/table/DataTable.tsx
- react-app/src/components/users/UserDetail.tsx
- react-app/src/contexts/lookupContext.tsx
- react-app/src/hooks/api/useGroupedAgenciesApi.ts
[PIMS-1801](https://citz-imb.atlassian.net/browse/PIMS-1801)
Reducing the need for database joins by using the lookup context instead.
- Removed a number of dataloader uses where context usage would work instead.
- Removed joins from services where it would no longer affect frontend behaviour
- Uncommented a line to restore quicksearch functionality on client-filtered tables
- MultiselectFormField now accepts nested indent formatting
Didn't remove the joins on get______ services. This mostly just applies to tables. Replacing the joins on these tables with just the Id value affects the server-side pagination addition in a negative way. Can continue to look for a solution, but would like to see how the pagination is applied to the Disposal Inventory table first.
Just use the app as normal. …
> PIMS-1801 Replace Joins with Lookup

- express-api/src/controllers/properties/propertiesController.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/tests/unit/controllers/properties/propertiesController.test.ts
- express-api/tests/unit/services/properties/propertyServices.test.ts
- react-app/src/components/property/PropertyTable.tsx
[PIMS-1805: ](https://citz-imb.atlassian.net/browse/PIMS-1805)
- Adding restrictions on property search in projects so that "General Users" should only be able to add their own agency's properties, while administrators can add a property from any agency to a project.
- Only properties that are in "Surplus Active" or "Surplus Encumbered" classification can be added.
I needed to change the propertiesFuzzySearch, so hoping this doesn't break anything.
- To test, you'll need to change your user's role to a "General User", then search for a property and confirm that you can only see properties belonging to your agency and if you belong to a parent agency, that properties belonging to the sub agency also can be added.
- These properties should all have a classification of either "Surplus …
> PIMS-1805: Disposal project property search constraints 

- react-app/src/components/map/InventoryLayer.tsx
- react-app/src/components/map/ParcelMap.tsx
- react-app/src/components/map/clusterPopup/ClusterPopup.tsx
- react-app/src/components/map/sidebar/MapSidebar.tsx
[PIMS-1830](https://citz-imb.atlassian.net/browse/PIMS-1830?atlOrigin=eyJpIjoiMDMwZjRkZWI4YjNjNDhhZDg0ZmMxMDE1OTVmYWQ1ODAiLCJwIjoiaiJ9)
- Sidebar `x of y` count now has a minimum of 1 for the second number
- Things noticed and fixed while doing this:
- Clusters' centres are now anchored properly to the location. This is really only obvious for properties of 1, but before the cluster marker anchored from the top-left.
- Cluster popup closes on resizing the map. Noticed it would just stay up, then be out of position when the map resized before.
- Shrunk scaling of cluster icons. When there were only a few on the screen, it got much bigger than needed.
- Updated offset of cluster popup. This was probably affected when the address was added to the property rows.
- Use the map page to view the …
> PIMS-1830 Sidebar Count Issue & Other Map Fixes

- express-api/src/services/properties/propertiesServices.ts
- express-api/src/utilities/helperFunctions.ts
- express-api/tests/unit/services/properties/propertyServices.test.ts
- express-api/tests/unit/utilities/helperFunctions.test.ts
- react-app/src/components/projects/DisposalPropertiesSearchTable.tsx
[PIMS-1826](https://citz-imb.atlassian.net/browse/PIMS-1826?atlOrigin=eyJpIjoiOTViMDlhYzMzNGZlNDJkNjkyNzgwOTQwNjg1YjRkNGIiLCJwIjoiaiJ9)
- Edit fuzzy search service to be case insensitive
- Edit fuzzy search by PID to allow for leading zeroes and hyphens
- Change how autocomplete options are rendered for the fuzzy search
> PIMS-1826 Fuzzy Search Options

- express-api/src/services/projects/projectsServices.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/tests/unit/services/projects/projectsServices.test.ts
- express-api/tests/unit/services/properties/propertyServices.test.ts
- react-app/src/components/projects/ProjectsTable.tsx
- react-app/src/components/property/PropertyTable.tsx
- react-app/src/components/table/DataTable.tsx
- react-app/src/hooks/api/useProjectsApi.ts
- react-app/src/hooks/api/usePropertiesApi.ts
[PIMS-1823: ](https://citz-imb.atlassian.net/browse/PIMS-1823) - Fix count for server-side pagination
- Used a separate query for the "totalCount" in the project and property services because the TypeORM "findAndCount" function still returns the "filtered" number of rows and not the actual count.
- Modified the FilterSearchDataGridProps to take a rowCountProp number as a property that can be passed in.
- You should be able to see the total count reflected in the properties and projects list page as well as a snackbar notification at the bottom of the screen. This number should change when applying a filter on the list being displayed.
> - I have made corresponding changes …
> PIMS-1823: Fix count for server-side pagination

- react-app/src/components/map/parcelPopup/LtsaDetails.tsx
- react-app/src/components/map/parcelPopup/ParcelPopup.tsx
Removing double overflow properties so that we don't get scrollbars stacked all over the place in Chromium browsers
Removing double overflow properties so that we don't get scrollbars stacked all over the place in Chromium browsers.
Let me know if this breaks anything somehow but it looks better to me.
> Map popup scrollbar fix

- react-app/src/components/property/PropertyDialog.tsx
- react-app/src/components/property/PropertyForms.tsx
[PIMS-1752: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1752)
* The disabled prop has been removed on the non-year fields of the netbook and assessment forms for properties.
* An additional restriction has been added on adding a new row to these sections: you cannot re-use an existing year. Instead, just edit the relevant row and submit.
* You still must enter a year of current year or previous year for a new value.
* I removed some logic in the transform function for handling the submission, as it should no longer be relevant to do that filtering with the above changes.
> - I have tested my …
> PIMS-1752: Allow editing of previous netbook and asssessment values

- react-app/src/components/projects/ProjectDetail.tsx
- react-app/src/components/projects/ProjectForms.tsx
[PIMS-1773: ](https://citz-imb.atlassian.net/browse/PIMS-1773)
as noted in the ticket above here are the changes requested by Josh:
- ~~User list should be limited to Admin – I’m not sure how old PIMS is but I think only admin can see this~~
- This was cleared up after a conversation - users list should stay as is
- General user should be able to submit Disposal Project, but not change status once submitted under the Project Information heading. Changing status should be limited to Admin after project has been submitted by client.
- handled in this ticket
- Agency Interest field should only be accessible/viewable to Admin
- handled in this ticket
- Error when trying to submit application for exemption to ERP – after trying this I now get the error when trying to submit regular project
- …
> Pims-1773 Only Admins to See Agency Interest

- react-app/src/components/property/PropertyDetail.tsx
- react-app/src/contexts/lookupContext.tsx
Wrapped the function for looking up values by id in a useCallback so that dependent components know to re-render when data is loaded. Most evident on the property page as the object used to display property data was memoized and did not have anything lookupContext related as a dependency. 
> Wrap getLookupValueById in useCallback

- .env-template
- express-api/README.md
- express-api/src/constants/config.ts
- express-api/src/controllers/lookup/lookupController.ts
- express-api/src/controllers/reports/reportsController.ts
- react-app/src/constants/jsxSnippets.tsx
- react-app/src/contexts/lookupContext.tsx
- react-app/src/hooks/api/useLookupApi.ts
- react-app/src/pages/AccessRequest.tsx
[PIMS-1951](https://citz-imb.atlassian.net/browse/PIMS-1951)
- Added config property to the lookup call.
- ENV for the error report now generalized to a contact email (CONTACT_EMAIL)
- Cases of this email in the frontend now come from this contact
- Populated the links on the access request form
> PIMS-1951 Remove pimshelp Email

- express-api/src/controllers/notifications/notificationsController.ts
- express-api/src/routes/notificationsRouter.ts
- express-api/src/services/ches/chesServices.ts
- express-api/src/services/notifications/notificationServices.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/controllers/notifications/notificationsController.test.ts
- express-api/tests/unit/services/notifications/notificationServices.test.ts
- react-app/src/components/projects/ProjectDetail.tsx
- react-app/src/components/projects/ProjectDialog.tsx
- react-app/src/components/projects/ProjectNotificationsTable.tsx
- react-app/src/hooks/api/useBuildingsApi.ts
- react-app/src/hooks/api/useParcelsApi.ts
- react-app/src/hooks/api/useProjectNotificationApi.ts
- react-app/src/hooks/api/useProjectsApi.ts
- react-app/src/hooks/api/usePropertiesApi.ts
- react-app/src/hooks/api/useUsersApi.ts
- react-app/src/hooks/useFetch.ts
- react-app/src/pages/BulkUpload.tsx
[PIMS-1928](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1928)
* Adds new controllers and services for resending and cancelling notifications
* Adds new frontend hooks for resending and cancelling notifications
* Added buttons to the notification table on the project detail for resending or cancelling projects.
Note:
* The cancel button is greyed out for notifications that are already cancelled or completed, obviously cancelling them doesn't do anything.
* Resending a cancelled or completed notification does work, but the function to refresh notifications in getNotificationByProjectId is hardcoded to not update notifications in these statuses. Should we loosen that restriction? EDIT: This is still true, but I added a call to update just the single notification in the resend endpoint, so …
> PIMS-1928: Cancel and resend notifications

- express-api/src/controllers/notifications/notificationsController.ts
- express-api/src/services/notifications/notificationServices.ts
- express-api/tests/unit/services/notifications/notificationServices.test.ts
- react-app/src/constants/chesNotificationStatus.ts
[PIMS-1929: ](https://citz-imb.atlassian.net/browse/PIMS-1929)
- Added 2 new notification statuses to handle 404, and 422 responses from the CHES api: https://ches.api.gov.bc.ca/api/v1/docs#tag/Message/operation/GetStatusQuery
- I can't seem to catch the 401 unauthorized response from CHES, this may need handling in the controller.
- Since most of the notifications you will have in your localhost are from production, you can use the CHES dev credentials in your .env, then create a new project. To trigger a 404 not found, you can change one of the characters in the ChesMessageId column for the record in the NotificationQueue table where the notifications are stored.
- With existing projects from production, you should still see all the "completed" notifications, but the ones that were in a …
> PIMS-1929: Unknown status for project notifications

- express-api/src/controllers/properties/propertiesController.ts
- express-api/src/routes/propertiesRouter.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/tests/unit/controllers/properties/propertiesController.test.ts
- react-app/src/components/property/AssociatedProjectsTable.tsx
- react-app/src/components/property/PropertyDetail.tsx
- react-app/src/hooks/api/usePropertiesApi.ts
[PIMS-1967: ](https://citz-imb.atlassian.net/browse/PIMS-1967)
- Added new controller, route, and service to find associated projects for a property
- New data card on the property details page
- I can't seem to make the third column for the project description wrap around when this field contains text which goes beyond the width of the table.
- Waiting for some feedback from Josh as well, so some things may change.
> PIMS-1967: Create link to project from property page

- react-app/src/components/form/SelectFormField.tsx
- react-app/src/components/property/PropertyForms.tsx
[PIMS-1984](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1984)
Just adding a numeric prop to the text field could have solved this bug but it seemed like it may be better to just constrain this input a lot more in general. After all, there's really only two options that may be valid, max. So with that in mind I've tried to make this a single select style input instead. I also made it so that you can't add more rows once you've added current year and previous year, since past that point nothing else is valid.
> - My changes generate no new …
> PIMS-1984: Fiscal year only takes year values.

- express-api/src/services/properties/propertiesServices.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/services/buildings/buildingService.test.ts
- express-api/tests/unit/services/parcels/parcelsService.test.ts
- express-api/tests/unit/services/properties/propertyServices.test.ts
- react-app/src/components/property/PropertyTable.tsx
- react-app/src/components/table/DataTable.tsx
- react-app/src/hooks/api/usePropertiesApi.ts
[PIMS-2002](https://citz-imb.atlassian.net/browse/PIMS-2002?atlOrigin=eyJpIjoiMmIxMTMxNDFlZWU0NGU5ZjhiZTM1MDRlMDE0YTAyOWEiLCJwIjoiaiJ9)
This is in response to the timeout issue sometimes happening when exporting the properties in a live environment.
Pretty sure the clause that slows things down is this:
`where: { Id: In(buildingIds) }`
When it is called getting parcels and buildings.
Suspect this is an issue with how TypeORM handles its queries. Almost looks like it's going a circular query at one point.
- Broke up the relations and where properties in the TypeORM call into operations in code instead. For some reason this runs faster than letting TypeORM do the joins and filtering. These are the timings I got in local testing:
```
// Getting evals, fiscals, and filtering separately: …
```
> PIMS-2002 Properties Export

- react-app/src/components/projects/EnhancedReferralDates.tsx
- react-app/src/components/projects/ProjectDetail.tsx
- react-app/src/components/projects/ProjectNotificationsTable.tsx
[PIMS-2001: ](https://citz-imb.atlassian.net/browse/PIMS-2001)
- Created a separate component for the ERP dates section
- This will display when an ERP project has been approved and the 30, 60, 90 day notifications have been sent to CHES.
- You can either create a new and approved ERP project to see this new section, or just go to an existing project that has already sent the 30, 60, & 90 day notfications.
- Please test to see that all user types can see this section.
> PIMS-2001: Add ERP date for general user projects

- express-api/src/controllers/tools/toolsController.ts
- express-api/src/routes/tools.swagger.yaml
- express-api/src/routes/toolsRouter.ts
- express-api/src/services/geocoder/geocoderService.ts
- express-api/tests/unit/controllers/tools/toolsController.test.ts
- express-api/tests/unit/services/geocoder/geocoderService.test.ts
[PIMS-2086](https://citz-imb.atlassian.net/browse/PIMS-2086)
- Removed everything related to the getPIDs function as we are not even using this in PIMS.
- It should resolve this security issue: https://github.com/bcgov/PIMS/security/code-scanning/1
- Not sure if there's much to test other than making sure this didn't break anything. After merging it will hopefully resolve that issue.
> PIMS-2086: Remove getPIDs function

- express-api/src/constants/config.ts
- express-api/src/controllers/lookup/lookupController.ts
- express-api/src/routes/lookup.swagger.yaml
- express-api/src/typeorm/Entities/User.ts
- express-api/src/typeorm/Migrations/1726615038425-KeycloakUserIdType.ts
- react-app/src/components/users/UserDetail.tsx
- react-app/src/components/users/UsersTable.tsx
- react-app/src/hooks/api/useLookupApi.ts
- react-app/src/pages/AccessRequest.tsx
- react-app/src/utilities/helperFunctions.ts
[PIMS-2027](https://citz-imb.atlassian.net/browse/PIMS-2027)
This PR adds the BCSC option whenever a provider is presented in the frontend.
The BCSC provider in the token is just the Keycloak integration client ID unfortunately, so it looks for that.
- Added helper function to return Provider string
- Replaced individual checks with this helper function for consistency
- Added sso client id to config so we have something to check BCSC for
- Changed KeycloakUserId column from uuid type to varchar type. The id from Keycloak for BCSC is not a true uuid because it contains values outside [0-9a-f]. This would cause the database to reject the BCSC value when it was entered. Note, the KeycloakUserId field will not populate correctly still, because the sso-express package does not recognize BCSC …
> PIMS-2027 BCSC Provider Options

- react-app/src/components/form/DateFormField.tsx
[PIMS-2085](https://citz-imb.atlassian.net/browse/PIMS-2085)
- Added a required property to slotProps in the DateFormField.tsx component
- Please see testing instructions here: https://citz-imb.atlassian.net/browse/PIMS-2085
- This will automatically show the date as required on the page displaying the asterisk symbol beside the name, and right now there is only one date in the database being required.
> PIMS-2085: Add the required option to DatePicker

- express-api/.gitignore
- react-app/package.json
- react-app/src/components/adminAreas/AdministrativeAreasTable.tsx
- react-app/src/components/agencies/AgencyTable.tsx
- react-app/src/components/projects/ProjectsTable.tsx
- react-app/src/components/users/UsersTable.tsx
- react-app/src/pages/BulkUpload.tsx
- react-app/src/utilities/downloadExcelFile.ts
- react-app/src/utilities/helperFunctions.ts
[PIMS-2134](https://citz-imb.atlassian.net/browse/PIMS-2134)
Request was to have the dates in exported spreadsheet be just the date format, not the ISO date strings we store.
- Moved from 'node-xlsx' to the `xlsx` (really sheetjs) package we use in the backend too. This allowed for date formatting.
- Created a function to handle and convert the date strings as needed for export
- Reworked the export from tables to use the `xlsx` process for making and downloading spreadsheet. This way we can specify that fields are actually configured as dates that excel will just recognize.
- Updated the export from bulk upload results to use the new package as well.
If you need to seed the bulk upload results but can't legitimately do so because of the upload bug, try uploading a file, let it fail, then …
> PIMS-2134 Export Tables with Dates

- express-api/src/controllers/properties/propertiesController.ts
- express-api/src/typeorm/Entities/User.ts
- react-app/src/pages/BulkUpload.tsx
[PIMS-2135](https://citz-imb.atlassian.net/browse/PIMS-2135)
There was an issue with the bulk upload that was caused when moving the authentication checks out of Keycloak.
Two problems:
- The user passed into the worker now had the `hasOneOfRoles` function attached. Workers apparently cannot pass functions, promises, steams, etc.
- The role was initially sending the name, but later checks expected the Id.
- Formatted a date on the Bulk Upload page to make it more human readable.
- Made sure that the Role and Agency properties of the User records are marked as potentially undefined (when you get the record without doing the JOIN)
- Updated the user object to remove the `hasOneOfRoles` function before it is passed into the worker. It's not used further in this process, and the type is …
> PIMS-2135 Bulk Upload Worker Bug

- react-app/src/components/map/clusterPopup/ClusterPopup.tsx
- react-app/src/components/map/controls/FilterControl.tsx
- react-app/src/components/map/sidebar/MapSidebar.tsx
[PIMS-2136](https://citz-imb.atlassian.net/browse/PIMS-2136)
- Made the map filter area scrollable. Kept this scroll bar visually hidden.
- Made the property lists in the sidebar and cluster popup only have the scroll on the Y axis. Didn't notice this before on Mac, but on Windows it shows a horizontal scrollbar otherwise.
- Visually inspect the filter and property lists on the map for scroll function.
> PIMS-2136 Filter Scroll

- express-api/src/controllers/properties/propertiesSchema.ts
- express-api/src/services/properties/propertiesServices.ts
- react-app/src/components/form/ToggleSwitch.tsx
- react-app/src/components/map/controls/FilterControl.tsx
- react-app/src/hooks/api/usePropertiesApi.ts
[PIMS-2036](https://citz-imb.atlassian.net/browse/PIMS-2036)
- Added a new ToggleSwitch on the map page to display properties that are in ERP projects.
- To test the filter, when selected it should only display properties that are in ERP.
- You can also test adding additional filters when this is selected as well, eg. Land or Building, Agency, etc.
- You will probably need to double check the number of properties in each project that is in "Approved for ERP" status just to make sure the results match.
> PIMS-2036: Map Filter - ERP Projects

- express-api/src/controllers/tools/toolsController.ts
- express-api/src/express.ts
- express-api/src/routes/tools.swagger.yaml
- express-api/src/routes/toolsRouter.ts
- express-api/src/typeorm/Entities/JurRollPidXref.ts
- express-api/src/typeorm/Migrations/1729627184522-CreateXrefTable.ts
- express-api/src/typeorm/entitiesIndex.ts
- express-api/tests/unit/controllers/tools/toolsController.test.ts
- react-app/src/components/map/parcelPopup/ParcelPopup.tsx
- react-app/src/hooks/api/useBCAssessmentApi.ts
- react-app/src/hooks/usePimsApi.ts
[PIMS-1869](https://citz-imb.atlassian.net/browse/PIMS-1869)
- Created table to host XREF data
- Added controller and route to API to access this table
- Updated the ParcelPopup component to select the BCA data depending on the return value from this table.
- Tests and Documentation
This is tough to test without the BC Assessment data in local, but it's possible to test individual parts with some substitutions.
First you have to run the migration then load the XREF data.
Get the data from here:
https://catalogue.data.gov.bc.ca/dataset/parcelmap-bc-jurisdiction-roll-number-pid-cross-reference-table
You will have to log in to see it.
I loaded the data with dbeaver. There's an option by right-clicking a table to import data > from CSV
Make sure you only import the three columns that are …
> PIMS-1869 BCA XREF

- express-api/src/middleware/headerHandler.ts
- express-api/tests/integration/middleware/headerHandler.test.ts
- react-app/index.html
- react-app/nginx.conf
[PIMS-2106](https://citz-imb.atlassian.net/browse/PIMS-2106)
It seems that some of the findings of the WAVA report such as "Cookie with Insecure or Improper or Missing SameSite attribute" is out of our control, as these cookies are being sent by the service sending back the response (keycloak, siteminder, etc.)
- Added security headers based on an existing repo mentioned by Garry in the Jira ticket.
- Modified the content security policy somewhat to allow for requests to unpkg.com, cdnjs.cloudflare so that the map displays correctly.
- Also removed "'Access-Control-Allow-Origin', '*'" as this can potentially be a security issue, please test to see nothing broke.
- This is a preliminary change. Feedback and additional suggestions are welcome!
- To test you will need to run the react-app …
> PIMS-2106: Address WAVA Scan Findings

- react-app/nginx.conf
Ran into an issue yesterday trying to test the BCA changes.
I think our nginx.conf is blocking the request, but there's no way to test locally.
Missed testing this in DEV the first time around.
Added two addresses to the connect-src line. One for test server and one for prod server.
> BCA connect-src Fix

- express-api/src/services/buildings/buildingServices.ts
- express-api/src/services/parcels/parcelServices.ts
- express-api/tests/unit/services/buildings/buildingService.test.ts
[PIMS-2258](https://citz-imb.atlassian.net/browse/PIMS-2258)
- Added some comments
- Added a condition to the if statement that controls if an agency change is denied for properties
- It will now check that an agency was included in the request before checking if a user has permissions for that agency
- As a General User, try to add/update assessment values for a property in your agencies.
> PIMS-2258 Adjust when property agency changes are restricted

- react-app/src/components/map/sidebar/MapSidebar.tsx
[PIMS-2269](https://citz-imb.atlassian.net/browse/PIMS-2269)
Wrapped the sidebar page counts in a grid to separate some of the elements. It should break evenly now when there's a large number of properties.
Examples:
Small number
Big number
> PIMS-2269 Fixing Sidebar Page Count

- express-api/src/appDataSource.ts
- express-api/src/server.ts
- express-api/src/services/notifications/notificationServices.ts
- express-api/src/services/projects/projectsServices.ts
- express-api/src/utilities/clearIdleConnections.ts
[PIMS-2302](https://citz-imb.atlassian.net/browse/PIMS-2302)
- Remedy some database calls in the backend services that may be opening connections and never closing them.
- Add a cron job that removes idle connections that match appropriate conditions
I tested it by creating intentionally open idle connections
```ts
const db = AppDataSource.createQueryRunner();
db.startTransaction();
```
Trigger this a couple of times to make the connections, then check your connections in the database with this SQL
```sql
SELECT * FROM pg_stat_activity;
```
Manually trigger the `clearIdleConnections` function and check the table again to see that the ones in the `idle in transaction` state should be cleared. They must also be older than 5 minutes to clear, so give yourself some delay or adjust the SQL to …
> PIMS-2302 Idle Connection Pool Fixes

- .gitignore
- docker-compose.yml
Not related to a ticket. These are just the changes that I had to make to have the compose file work with Podman instead of Docker. 
I believe it should still be compatible with the docker-engine. 
- Add database folder to gitignore. I don't see how this wasn't an issue before. Maybe Docker handled it automatically.
- Few auto-formatting changes to the compose, such as quotation marks.
- Move postgres environment ENVs from inline to env file.
- Specify where postgres saves its data with the PGDATA environment variable. For some reason, this version of postgres was not saving it in the volume.
1. Make sure your .env is still populated. No change needed if PIMS is already running.
2. Try building the containers with your choice of software (Docker, Podman, etc.)
`docker-compose up --build …
> Update compose file and git-ignore

- express-api/package.json
[PIMS-2303](https://citz-imb.atlassian.net/browse/PIMS-2303)
Minor dependency updates. See the package.json file for more information.
I tried to update Express to v5 again as well, but I didn't commit those changes. There's still an issue where it looks like the body of the request is consumed before it gets to the route that needs it. I suspect `protectedRoute` from our Keycloak package is the issue, as it uses Express v4 still.
> PIMS-2303 Express API Dependency Updates

- express-api/src/services/notifications/notificationServices.ts
- express-api/src/typeorm/Migrations/1745434734346-RemoveWatchResponseType.ts
- react-app/src/constants/agencyResponseTypes.ts
[PIMS-2307](https://citz-imb.atlassian.net/browse/PIMS-2307)
Recommend this is reviewed after PIMS-2275 is merged. Will keep in draft until then.
- Remove Watch value from enums in frontend and backend
- Adjust notification generation area to look for Subscribe instead of NOT (watch or unsubscribe)
- Create migration that moves all Watch responses to Subscribe responses. After looking at PROD to see how Watch is being used, it seems like admins occasionally attempt to use it when an agency is interested in a project. Unfortunately, Watch status acts more like Unsubscribe status at the moment. This should bring the attempted use closer to the intended behaviour.
- Make sure you have parent agencies and child agencies with emails and Send Notifications checked in your local database.
- …
> PIMS-2307 Remove Watch Agency Response Type

- express-api/src/typeorm/Migrations/1745424172379-AddWatchingAgencyErpTemplate.ts
[PIMS-2309](https://citz-imb.atlassian.net/browse/PIMS-2309)
- Added migration that adds the missing template for Watching Agencies and relevant entry in the `project_status_notification` table
This can only be properly tested once the other notification PR (PIMS-2275) is merged. Otherwise, the Watching Agency emails aren't even detected.
Once that is done:
- Pick an agency that is not a parent agency. Make sure it has a To email and Send Notifications checked.
- Create a project. Make sure the agency above is Subscribed.
- Move the project to Approved for ERP. There should be 4 emails for that agency queued. The initial email is the new one that was previously missing.
> …
> PIMS-2309 Initial ERP Notification for Watching Agencies

- express-api/src/controllers/projects/projectsController.ts
- express-api/tests/unit/controllers/projects/projectsController.test.ts
[PIMS-2323](https://citz-imb.atlassian.net/browse/PIMS-2323)
- Filters out old private note field data when exporting projects if the user isn't an admin. The column remains, but there will be no data for it.
- Try exporting the projects as an admin and see the Private Notes field
- Change self to General User and try again. Private Notes cells should be blank.
> PIMS-2323 Private notes no longer visible on export

- express-api/src/services/ches/chesServices.ts
- express-api/src/services/notifications/notificationServices.ts
- express-api/src/utilities/failedEmailCheck.ts
[PIMS-2313](https://citz-imb.atlassian.net/browse/PIMS-2313)
The system user was being used to send emails in cases where there wasn't an obvious user triggering the email. This was a problem when any of these conditions were met:
- CHES_OVERRIDE_TO is set
- CHES_SEND_TO_LIVE is not "true"
- CHES_BCC_USER is "true"
Any of these could cause the system user's email to potentially be included in the TO, CC, or BCC fields. Because the system user's email isn't a real email, actually using it in a sent email caused the email to bounce back, which notified the PO. 
- Made the user an optional argument for sendEmailAsync function.
- Removed system user from calls to this function.
- Tried to make sendEmailAsync function have more specific handling in case the system user is fed to it …
> PIMS-2313 BUG: Emails Sent to System User

- react-app/src/components/table/DataTable.tsx
- react-app/src/components/users/UsersTable.tsx
[PIMS-2341](https://citz-imb.atlassian.net/browse/PIMS-2341)
Row count wasn't showing on the User table (the only one still using client-side logic).
- Adjusted source of row count. It was more complicated before, but this simpler method seems to work too.
- Look at the main pages with tables (users, project, properties, agencies, admin areas) and see if the table row count is displayed correctly.
> PIMS-2341 Table Row Count Bug
