- openshift/README.md
- openshift/templates/app/pims-api/pims-api-build.yaml
- openshift/templates/app/pims-api/pims-api-deploy.yaml
- openshift/templates/tools/pipeline.yaml
> Openshift setup - API

- openshift/templates/app/pims-api/pims-api-deploy.yaml
Inject Keycloak (auth) settings via ENV vars
> PIMS-280 Keycloak Openshift configuration

- frontend/README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/public/keycloak.json
- frontend/src/PrivateRoute.tsx
- frontend/src/components/navigation/Header.tsx
- frontend/src/index.tsx
missed committing this on Monday, but would rather commit this separately to keep the review small.
> IE fix, reorganize package.json

- backend/Areas/Admin/Controllers/ParcelController.cs
- backend/Areas/Admin/Models/BuildingModel.cs
- backend/Areas/Admin/Models/ParcelModel.cs
- backend/Areas/Admin/Models/Parts/BuildingModel.cs
- backend/Areas/Admin/Models/Parts/ParcelBuildingModel.cs
- backend/Data/Entities/Address.cs
- backend/Data/Entities/Building.cs
- backend/Helpers/Profiles/BuildingProfile.cs
- backend/Helpers/Profiles/ParcelProfile.cs
Adding way to import parcels and properties.
Jonny should now be able to generate JSON and import a bunch of parcels and their buildings.
Please note that at some point we will be extracting all this Data Access Layer logic out of the controller endpoints (Technical Debt).
> PIMS-442 PIMS-63 PIMS-447 Updating initial migration.

- frontend/openshift/templates/nginx-runtime/nginx.conf.template
- frontend/openshift/templates/nginx-runtime/s2i/bin/run
the other change was to update the params of the pims-app dc to have an API_SERVICE_NAME of pims-api instead of api
> Enable nginx routing of /api to backend pod

- backend/.gitignore
- backend/Data/PIMSContextFactory.cs
- backend/Startup.cs
- backend/appsettings.json
- backend/pims.api.csproj
- database/mssql/README.md
- docker-compose.yml
- openshift/templates/app/pims-api/deploy.yaml
ConnectionString will now be part of a config, but the password will be a secret.
> PIMS-447 Fixing API connection string.

- backend/Areas/Admin/Models/BuildingModel.cs
- backend/Areas/Admin/Models/ParcelModel.cs
- backend/Areas/Admin/Models/Parts/ParcelBuildingModel.cs
- backend/Data/Entities/Building.cs
- backend/Data/Entities/Parcel.cs
- backend/Migrations/20200207204726_initial.Designer.cs
- backend/Migrations/20200207204726_initial.cs
- backend/Migrations/PIMSContextModelSnapshot.cs
- backend/Models/Building.cs
- openshift/templates/app/pims-api/deploy.yaml
- test/Postman/pims.json
PIMS-447 Fixing initialization seed scripts for linux.
PIMS-447 Fixing agencies seed scripts.
PIMS-441 Adding webhook for RocketChat.
> PIMS-447 Fixing DB initial migration.

- frontend/src/actionCreators/parcelsActionCreator.tsx
- frontend/src/actions/parcelsActions.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/API.tsx
- frontend/src/pages/MapView.tsx
* Request parcels from API on every map update (pan & zoom)
* Request parcel details to populate map popup upon map click
* Also, fix a few frontend linting errors
> PIMS-417 Show parcels on Map View

- backend/Data/PIMSContextFactory.cs
- backend/Program.cs
- backend/README.md
- backend/Startup.cs
- backend/pims.api.csproj
- database/README.md
- database/mssql/README.md
- database/postgres/README.md
Corrected a number of issues with documentation related to setting up the database and using the `dotnet-ef` CLI.
> PIMS-874 Cleaning up documentation and DB configuration process.

- openshift/README.md
- openshift/templates/tools/pipeline.yaml
With this PR I have cleaned up the generic `pipeline.yaml` template and provided instructions on how to create the various pipelines that support our processes.
- **cicd-pipeline** - this is our main "build" pipeline with auto-deployment to DEV
- **promote-to-test-pipeline** - this is for manual approval to TEST
A future PR will handle building from the `master` branch and promoting to PROD
> Update documentation with pipeline setup instructions

- backend/.dockerignore
- backend/.vscode/launch.json
- backend/.vscode/tasks.json
- backend/Dockerfile
- backend/Dockerfile.bak
- docker-compose.yml
* adds Docker debug configuration to VS Code
* updates Dockerfile to match debugging best practices
* allows debugging container to connect to local database (via docker-compose)
> Allow remote debugging in API docker container

- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/api/Areas/Tools/Models/PropertyModel.cs
- backend/api/Models/CodeModel.cs
- backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
- backend/dal/Helpers/Extensions/StringExtensions.cs
- backend/dal/Services/Admin/Concrete/AgencyService.cs
- backend/dal/Services/Admin/Concrete/BuildingConstructionTypeService.cs
- backend/dal/Services/Admin/Concrete/BuildingPredominateUseService.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/CityService.cs
- backend/dal/Services/Admin/Concrete/PropertyClassificationService.cs
- backend/dal/Services/Admin/Concrete/PropertyStatusService.cs
- backend/dal/Services/Admin/Concrete/PropertyTypeService.cs
- backend/dal/Services/Admin/Concrete/ProvinceService.cs
- backend/dal/Services/Admin/IAgencyService.cs
- backend/dal/Services/Admin/IBuildingConstructionTypeService.cs
- backend/dal/Services/Admin/IBuildingPredominateUseService.cs
- backend/dal/Services/Admin/IBuildingService.cs
- backend/dal/Services/Admin/ICityService.cs
- backend/dal/Services/Admin/IPimsAdminService.cs
- backend/dal/Services/Admin/IPropertyClassificationService.cs
- backend/dal/Services/Admin/IPropertyStatusService.cs
- backend/dal/Services/Admin/IPropertyTypeService.cs
- backend/dal/Services/Admin/IProvinceService.cs
- backend/dal/Services/Admin/PimsAdminService.cs
- backend/entities/ParcelEvaluation.cs
New endpoint `/api/admin/tools/import/properties`
I've created Postman collections to import the data.  Still requires a bit of manual effort.  Would love to find a clean way to iterate through a JSON dataset and submit batches.
> PIMS-945 Adding way to import Todd's data.

- backend/api/Areas/Admin/Controllers/UserController.cs
- backend/api/Controllers/UserController.cs
- backend/api/Helpers/IRequestClient.cs
- backend/api/Helpers/RequestClient.cs
- backend/api/Models/Parts/BuildingModel.cs
- backend/api/Models/Parts/ParcelBuildingModel.cs
- backend/api/Models/Parts/ParcelModel.cs
- backend/api/Profiles/BuildingProfile.cs
- backend/api/Profiles/Extensions/MappingExpressionExtensions.cs
- backend/api/Profiles/ParcelProfile.cs
- backend/dal/PimsService.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/dal/Services/Admin/IUserService.cs
- backend/dal/Services/Concrete/UserService.cs
- backend/dal/Services/IUserService.cs
- backend/test/Controllers/Admin/UserControllerTest.cs
- backend/test/Controllers/UserControllerTest.cs
- backend/test/Helpers/ControllerHelper.cs
- backend/test/Helpers/ServiceHelper.cs
- backend/test/Helpers/TestHelper.cs
Notes:
The extra changes to the automapper make our mappings pass automapper validation. Included in this push as it relates to test changes.
I made the decision to group the two new access requests under the user controller, but we could put these in an admin access request controller and non-admin request controller instead.
The restrictions on 1 agency/role are in the add access request controller.
> PIMS-1014, PIMS-979 POST/GET Access Requests

- frontend/src/App.tsx
- frontend/src/actionCreators/authActionCreator.tsx
- frontend/src/actionCreators/parcelsActionCreator.spec.tsx
- frontend/src/actionCreators/parcelsActionCreator.tsx
- frontend/src/actions/genericActions.spec.tsx
- frontend/src/actions/genericActions.tsx
- frontend/src/components/common/LookupCodeDropdown.tsx
- frontend/src/components/maps/MapNavBar.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/components/navigation/Header.test.tsx
- frontend/src/components/navigation/__snapshots__/Header.test.tsx.snap
- frontend/src/constants/API.tsx
- frontend/src/constants/reducerTypes.tsx
- frontend/src/pages/GuestAccessPage.tsx
- frontend/src/pages/Login.tsx
- frontend/src/reducers/networkReducer.tsx
- frontend/src/reducers/rootReducer.tsx
The authenticated guest page is only accessible if:
1) the user logs in (protected behind private route).
2) the user has no granted roles or has just been activated.
The auth page is just a placeholder for now. The story to add the form is PIMS-970
> PIMS-969 Authenticated Guest Page skeleton.

- openshift/pipelines/scripts/notify.groovy
e.g. "Mary's account was broken"
> Fix notifications with single quotes

- backend/test/Controllers/CodeLookupControllerTest.cs
- frontend/src/actionCreators/lookupCodeActionCreator.spec.tsx
- frontend/src/components/common/LookupCodeDropdown.test.tsx
- frontend/src/components/maps/BasemapToggle.test.tsx
- frontend/src/components/maps/MapFilterBar.test.tsx
- frontend/src/mocks/filterDataMock.ts
- frontend/src/pages/GuestAccessPage.test.tsx
UserControllerTests have decided to start giving me some errors today.. they will be included in the next PR - fixing them right now.
> PIMS 954, 1002, 1018, 1019, 1017

- backend/tools/import/Startup.cs
There was a bug in the code that required updating before I could run it against DEV.
> Fixing bug with import tool

- openshift/templates/base-images/nginx-runtime/Dockerfile
> Fix file and folder permissions on nginx-runtime

- backend/api/Areas/Admin/Controllers/UserController.cs
- backend/api/Controllers/UserController.cs
- backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- backend/api/Startup.cs
- backend/dal/Helpers/Extensions/QueryableExtensions.cs
- backend/dal/Helpers/Extensions/TypeExtensions.cs
- backend/dal/Services/Admin/Concrete/AgencyService.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/dal/Services/Admin/IBaseService`.cs
- backend/dal/Services/Admin/IUserService.cs
- backend/entities/Models/UserFilter.cs
- backend/entities/Pims.Dal.Entities.csproj
Also updated the API authentication/authorization error handling to be consistent with all our other error handling.
Created semi-generic implementation for submitting filtered queries from an endpoint to the DAL.
> PIMS-977 Adding /api/admin/users endpoint.

- backend/README.md
- backend/api/Startup.cs
- backend/api/appsettings.json
- openshift/templates/pims-api/deploy.yaml
- openshift/templates/secrets/README.md
- openshift/templates/secrets/api-health-secrets.yaml
- openshift/templates/secrets/api-sso-secrets.yaml
add new secret for webhook which overwrites appsettings uri.
revert -sso related changes.
> PIMS-1250 Update healthchecksui to use appsettings.json

- auth/keycloak/config/realm-export.json
- backend/.dockerignore
- frontend/src/App.tsx
- frontend/src/PrivateRoute.tsx
- frontend/src/components/maps/MapFilterBar.scss
- frontend/src/components/navigation/AppNavBar.scss
- frontend/src/components/navigation/AppNavBar.tsx
- frontend/src/components/navigation/Header.tsx
- frontend/src/constants/strings.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/pages/Login.test.tsx
- frontend/src/pages/Login.tsx
(using PIMS roles, not keycloak roles).
This update also includes changes to handle getting roles into the frontend from keycloak.
Needed to tweak Christine's UI to support a responsive layout (too many links to display on mobile).
PLEASE DO NOT MERGE THIS as we are about to demo.
> PIMS-141 add role based access to the App Nav Bar.

- backend/api/Areas/Admin/Models/UserModel.cs
- backend/api/Areas/Keycloak/Models/Update/UserModel.cs
- backend/api/Areas/Keycloak/Models/UserModel.cs
- backend/api/Areas/Keycloak/Profiles/Resolvers/AgencyToAgencyResolver.cs
- backend/api/Areas/Keycloak/Profiles/Resolvers/AttributeMapToAgencyResolver.cs
- backend/api/Areas/Keycloak/Profiles/Resolvers/KeycloakDisplayNameResolver.cs
- backend/api/Areas/Keycloak/Profiles/Resolvers/UserRoleToRoleResolver.cs
- backend/api/Areas/Keycloak/Profiles/UserProfile.cs
- backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- backend/api/Models/UserModel.cs
- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
- backend/dal/Configuration/UserConfiguration.cs
- backend/dal/Migrations/20200329131456_Initial.Designer.cs
- backend/dal/Migrations/20200329131456_Initial.cs
- backend/dal/Migrations/PIMSContextModelSnapshot.cs
- backend/dal/Migrations/initial/PostDeploy/01-Users.sql
- backend/dal/Options/ServiceAccountOptions.cs
- backend/dal/Services/Admin/Concrete/AgencyService.cs
- backend/dal/Services/Admin/Concrete/BaseService`.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/dal/Services/Concrete/UserService.cs
- backend/entities/Models/UserFilter.cs
- backend/entities/User.cs
Fixing keyloak DAL bugs.
Adding new properties to User to match UX/UI requirements.
Please note this requires a DB refresh.
> PIMS-974 Updating User Entity

- backend/api/Areas/Admin/Controllers/ParcelController.cs
- backend/core/Comparers/DeepPropertyCompare.cs
- backend/dal/Services/Admin/Concrete/ParcelService.cs
- backend/dal/Services/Admin/IParcelService.cs
- backend/test/Controllers/Admin/ParcelControllerTest.cs
- backend/test/Routes/Admin/ParcelControllerTest.cs
Please review the prior PR first.  Then I'll rebase and update this PR.
> PIMS-1226, PIMS-1230 Adding unit tests.

- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Controllers/BuildingController.cs
- backend/api/Models/Building/PartialBuildingModel.cs
- backend/api/Profiles/Building/PartialBuildingProfile.cs
- backend/api/Profiles/Converters/ParcelAgencyConverter.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/ParcelService.cs
- frontend/src/constants/API.tsx
Fixing Import bug.
Changing FE to user `/properties` endpoint instead of `/parcels`.  This requires frontend to be updated to make a request for `/parcels/{id}` or `/buildings/{id}` based on the `property.propertyTypeId`
0 = Parcel
1 = Building
> PIMS-599 Adding BuildingController.

- backend/test/Controllers/Admin/UserControllerTest.cs
- backend/test/Controllers/Keycloak/UserControllerTest.cs
- backend/test/Routes/Keycloak/UserControllerTest.cs
> PIMS-1009, PIMS-1011, PIMS-112

- backend/Dockerfile
- backend/api/Startup.cs
- backend/api/appsettings.json
- backend/dal/Services/Concrete/UserService.cs
- backend/tests/core/DatabaseHelper.cs
- backend/tests/core/Entities/BuildingHelper.cs
- backend/tests/core/Entities/BuildingOccupantTypeHelper.cs
Change to unit tests broke docker-compose.  This will fix it.
Also debugging why Swagger doesn't resolve in DEV.
> Fixing docker build issue

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/actionCreators/usersActionCreator.tsx
- frontend/src/actions/adminActions.tsx
- frontend/src/constants/API.tsx
- frontend/src/constants/actionTypes.tsx
- frontend/src/constants/reducerTypes.tsx
- frontend/src/pages/EditUserPage.scss
- frontend/src/pages/EditUserPage.test.tsx
- frontend/src/pages/EditUserPage.tsx
- frontend/src/pages/GuestAccessPage.test.tsx
- frontend/src/pages/ManageUsers.test.tsx
- frontend/src/pages/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/reducers/rootReducer.tsx
- frontend/src/reducers/userDetailReducer.tsx
- frontend/src/utils/YupSchema.tsx
- package-lock.json
Updated based on comments, currently has some branch conflicts will deal with those - but the code is ready for feedback again!
> Edit user information page, manage users/edit user tests

- frontend/src/forms/ParcelDetailForm.test.tsx
- package-lock.json
- Removed random package lock from root folder
- Tests for parcel details form
> PIMS-1168, 1179

- frontend/package-lock.json
This was missing in original pull request. Causing pipeline failure
> Adding missing package-lock

- frontend/src/pages/EditUserPage.tsx
I wasn't able to compile the syntax:
boolean ?
var = val :
var = otherval
changed to 
var = boolean ? val : otherval
also fixed a react warning that appeared to be causing a test failure.
> PIMS-974 fix compilation/test failures.

- frontend/src/components/maps/MapFilterBar.test.tsx
> PIMS-1098 Update unit tests for Landing Page Filter

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/pages/MapView.tsx
- frontend/src/pages/SubmitProperty.tsx
> PIMS-1350 Add ParcelMap boundaries to Landing Page

- frontend/src/actionCreators/parcelsActionCreator.spec.tsx
- frontend/src/actionCreators/parcelsActionCreator.tsx
- frontend/src/components/common/FormikPersist.tsx
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/constants/reducerTypes.tsx
- frontend/src/forms/ParcelDetailForm.test.tsx
- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/pages/MapView.tsx
- frontend/src/pages/SubmitProperty.tsx
- frontend/src/reducers/JwtSlice.tsx
- frontend/src/reducers/rootReducer.tsx
- frontend/src/utils/KeycloakEventHandler.tsx
- frontend/src/utils/RequestHeaders.tsx
Add formik persist with basic encryption.
Move jwt token storage from localstorage to redux.
> Pims 1384 - autosave

- auth/README.md
- scripts/gen-env-files.sh
scripts in the gen env files script
> Enable keycloak scripts in dev env file

- frontend/src/components/maps/MapFilterBar.test.tsx
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/API.tsx
- frontend/src/pages/MapView.tsx
- Added new field to form
- Updated relevant unit tests
> PIMS-1510 Landing Page - Municipality Filter

- frontend/src/App.tsx
- frontend/src/constants/reducerTypes.tsx
- frontend/src/contexts/authStateContext.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/index.tsx
- frontend/src/reducers/keycloakReadySlice.tsx
- frontend/src/reducers/rootReducer.tsx
- frontend/src/utils/KeycloakEventHandler.tsx
I used a React Context that exposes the ready state of keycloak, and userInfo. This allows us to always accurate userInfo properties like Groups when checking for roles. Can extend the userInfo object and use it for more advanced permission checks.
> PIMS-1550 Ensure that user is loaded on page load and if logged in

- frontend/package-lock.json
- frontend/package.json
- frontend/src/actionCreators/parcelsActionCreator.spec.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/forms/ParcelDetailForm.test.tsx
- frontend/src/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/pages/SubmitProperty.test.tsx
- frontend/src/pages/SubmitProperty.tsx
- frontend/src/pages/__snapshots__/SubmitProperty.test.tsx.snap
Only display a single view/update button on parcel popup detail depending on user agency ownership.
> PIMS-1343,PIMS-1344,PIMS-1383

- backend/tests/unit/api/Controllers/Admin/ParcelControllerTest.cs
- backend/tests/unit/dal/Services/Admin/ParcelServiceTest.cs
- frontend/src/components/maps/MapFilterBar.test.tsx
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/API.tsx
- frontend/src/pages/MapView.tsx
Botched the last PR, here is a new clean one!
> PIMS-1426, 1355

- frontend/src/actionCreators/parcelsActionCreator.spec.tsx
- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/components/maps/__snapshots__/ParcelPopupView.test.tsx.snap
- frontend/src/reducers/parcelsReducer.spec.tsx
Just a snapshot test for the parcel popup for now, to be modified as more work comes in.
Also a quick fix for a few tests causing some errors after recent merges.
> PIMS-1358 & small fix for other tests

- frontend/src/App.tsx
- frontend/src/PrivateRoute.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
Unauthenticated users cannot go to /access/request route.
Authenticated users without admin roles cannot go to /admin routes.
> PIMS-1419 Fixing secure routes

- auth/keycloak/Dockerfile
- auth/keycloak/README.md
- docker-compose.yml
- frontend/src/hooks/useKeycloakWrapper.tsx
* Improve keycloak container builds
* Fix keycloak README
* Proper null checks
> Misc fixes

- frontend/src/components/navigation/AppNavBar.test.tsx
- frontend/src/components/navigation/AppNavBar.tsx
- frontend/src/components/navigation/__snapshots__/AppNavBar.test.tsx.snap
- frontend/src/pages/SubmitProperty.test.tsx
- frontend/src/pages/__snapshots__/SubmitProperty.test.tsx.snap
Something messed up with my branching so I've created a new PR and updated the organization of the tests.
Please note that a lot of tests are no longer working after merging.
> PIMS-1419 Navigation tests

- backend/api/Areas/Admin/Models/Parcel/ParcelModel.cs
- backend/tests/unit/dal/Services/ParcelServiceTest.cs
- frontend/src/actions/parcelsActions.tsx
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/forms/subforms/BuildingForm.tsx
Just wanted to throw a draft up for now to review my 'fix' for the Update/View bug on building markers. Let me know if there is a different approach I should be taking, thanks!
> PIMS-1625, and adding asserts for fiscals/evaluations

- frontend/.eslintignore
- frontend/.prettierignore
- frontend/package-lock.json
- frontend/package.json
- check code formatting on every push
- remove lint-staged dependency
With this PR git will check for lint warnings and code formatting before you can push your changes. You won't be able to push until you resolve those.
If you need an escape hatch, use:
```bash
git push --no-verify
```
Ideally you shouldn't have to use the above workaround. All code should conform to agreed coding standards before pushing a PR.
This PR removes unused NPM dependencies and adds new ones: 
- make sure to run `npm install` on your local repo 
- delete the `frontend-node-cache` volume before rebuilding your docker containers.
> Improve lint and formatting automation

- frontend/src/buttons.scss
- frontend/src/components/common/Label.scss
- frontend/src/components/common/LookupCodeDropdown.scss
- frontend/src/components/common/TooltipIcon.scss
- frontend/src/components/layout/Footer/Footer.scss
- frontend/src/components/maps/BuildingPopupView.scss
- frontend/src/components/maps/ParcelPopupView.scss
- frontend/src/fonts.scss
- frontend/src/forms/ParcelDetailForm.scss
- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/index.scss
- frontend/src/pages/AccessRequestPage.scss
- frontend/src/pages/EditUserPage.scss
- frontend/src/pages/Login.scss
- frontend/src/pages/SubmitProperty.scss
- frontend/src/serviceWorker.ts
Now that linting and formatting are automatically enforced I had to run prettier to fix existing formatting issues.
**Tip:** to fix formatting issues, run:
```bash
npm run format
```
> Run prettier to fix formatting

- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/pages/SubmitProperty.tsx
With the help of Devin, finally got it done.
Also small change so View/Update appears in the same column for consistency.
> Bug fix - view/update on building markers

- frontend/src/components/maps/BuildingPopupView.test.tsx
- frontend/src/components/maps/__snapshots__/BuildingPopupView.test.tsx.snap
Just adding tests for BuildingPopup and slightly adjusting tests for the ParcelPopup
> Adding BuildingPopup tests

- backend/api/Mapping/Parcel/ParcelBuildingMap.cs
- backend/api/Mapping/Parcel/ParcelMap.cs
- frontend/src/OnLoadActions.tsx
- frontend/src/components/common/FormikPersist.tsx
- frontend/src/forms/ParcelDetailForm.scss
- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/forms/subforms/BuildingForm.tsx
- frontend/src/forms/subforms/LandForm.tsx
- frontend/src/forms/subforms/PidPinForm.tsx
- frontend/src/pages/SubmitProperty.scss
- frontend/src/utils/YupSchema.tsx
Contains minor "low hanging fruit" fixes either requested by Michaela or differing from the UI design. There are some outstanding larger fixes that I'll tackle later, time permitting:
1) building classification (requires DB update)
2) parent/child agency display on form (requires API update).
> PIMS-1342 Property Detail form validation.

- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
- backend/tools/keycloak/sync/Factory.cs
- backend/tools/keycloak/sync/Models/BaseModel.cs
- backend/tools/keycloak/sync/Models/ClaimModel.cs
- backend/tools/keycloak/sync/Models/Keycloak/ClientModel.cs
- backend/tools/keycloak/sync/Models/Keycloak/GroupModel.cs
- backend/tools/keycloak/sync/Models/Keycloak/RoleModel.cs
- backend/tools/keycloak/sync/Models/Keycloak/TokenModel.cs
- backend/tools/keycloak/sync/Models/Keycloak/UserModel.cs
- backend/tools/keycloak/sync/Models/PageModel`.cs
- backend/tools/keycloak/sync/Models/RoleModel.cs
- backend/tools/keycloak/sync/OpenIdConnector.cs
- backend/tools/keycloak/sync/SyncOptions.cs
- backend/tools/keycloak/sync/appsettings.json
While testing DEV discovered other issues that required additional effort.
> PIMS-1684 Fixing Manage Access Requests Issue

- frontend/src/actionCreators/parcelsActionCreator.tsx
- frontend/src/components/common/TooltipIcon.scss
- frontend/src/forms/ParcelDetailForm.scss
- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/forms/strings.ts
- frontend/src/forms/subforms/BuildingForm.tsx
- frontend/src/forms/subforms/EvaluationForm.tsx
- frontend/src/forms/subforms/LandForm.tsx
- frontend/src/forms/subforms/PagedBuildingForms.tsx
- frontend/src/forms/subforms/PidPinForm.tsx
- frontend/src/pages/SubmitProperty.scss
- frontend/src/pages/SubmitProperty.tsx
- frontend/src/utils/YupSchema.tsx
> PIMS-1720, 1718, 1742, 1743, 1744, 1747

- frontend/src/features/properties/list/PropertyListView.tsx
You can now download the current report.
> Please note that at present the Property List View doesn't provide filtering.
> PIMS-1541 Adding Export Properties Report to Property List View

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Table/Table.tsx
- frontend/src/features/properties/list/FilterBar.scss
- frontend/src/features/properties/list/FilterBar.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/columns.ts
- frontend/src/features/properties/list/index.ts
- frontend/src/features/properties/list/interfaces.ts
- frontend/src/utils/utils.tsx
Basic filtering functionality working. Some bugs still present around filtering by agencies and min/max land area. 
Some bugs are frontend but I noticed the server doesn't send the right results when land area filters are sent to the API. Once this PR is merged we can fixed those.
> PIMS-1472 Property List - Filtering

- frontend/src/components/common/form/AutoCompleteText.scss
- frontend/src/components/common/form/AutoCompleteText.tsx
- frontend/src/components/maps/MapFilterBar.test.tsx
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
*Updated 
Adding reusable auto complete component.
Will have to adjust for parent child relations ships when endpoints support this.
> Agency auto-complete

- backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
- backend/dal/Configuration/Views/PropertyConfiguration.cs
- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- backend/entities/Models/AllPropertyFilter.cs
- backend/entities/Models/BuildingFilter.cs
- backend/entities/Models/PropertyFilter.cs
- backend/tests/core/Entities/BuildingHelper.cs
- backend/tests/core/Entities/ParcelHelper.cs
- backend/tests/unit/api/Controllers/BuildingControllerTest.cs
- backend/tests/unit/api/Controllers/ParcelControllerTest.cs
- backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
- backend/tests/unit/dal/Services/PropertyServiceTest.cs
> PIMS-1541 Fixing LandArea Bug

- frontend/src/features/properties/list/FilterBar.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/interfaces.ts
When requesting the export report it must include the `all=true` parameter.  Otherwise they would have to ask for a report every page.
> PIMS-1541 Fixing Export Report Paging Bug

- backend/dal/Helpers/Extensions/IdentityExtensions.cs
While testing we discovered some agencies result in throwing an error when adding new properties.
> Fixing bug related to user agency

- frontend/src/__mocks__/react-text-mask.tsx
- frontend/src/_variables.scss
- frontend/src/components/maps/leaflet/Map.scss
- frontend/src/forms/ParcelDetailForm.test.tsx
- frontend/src/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/pages/AccessRequestPage.scss
- frontend/src/pages/AccessRequestPage.tsx
- frontend/src/pages/SubmitProperty.scss
- frontend/src/pages/__snapshots__/AccessRequestPage.test.tsx.snap
Create global variables partial and import into required scss files.
update masked input mock to be global.
> Fix Access Request Page Submit button being cut off.

- frontend/src/components/common/form/AutoCompleteText.tsx
Just cleaning things up a little
> Adding types

- frontend/src/components/common/form/AutoCompleteText.scss
- frontend/src/components/common/form/AutoCompleteText.tsx
- frontend/src/components/common/form/index.ts
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/forms/ParcelDetailForm.scss
- frontend/src/forms/ParcelDetailForm.test.tsx
- frontend/src/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/forms/subforms/AddressForm.tsx
- frontend/src/forms/subforms/BuildingForm.test.tsx
- frontend/src/forms/subforms/BuildingForm.tsx
- frontend/src/forms/subforms/LandForm.tsx
- frontend/src/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/utils/YupSchema.tsx
A few small schema changes and adding auto complete functionality to the cities field.
> Cities auto-complete and other small fixes

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-react.yml
Unable to get C# coverage reports working.  Going to leave it only as frontend coverage.
> PIMS-1685 Removing C# coverage report

- docs/VERSIONS.md
- openshift/pipelines/Jenkinsfile.cicd
provide pipeline assisted method of applying tags to built images.
-Update doc to explain how to check sha on deployed images.
> PIMS-105 Update doc and provide method to tag images.

- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/dal/Services/Admin/IUserService.cs
- backend/entities/Models/AccessRequestFilter.cs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/utils/testUtils.tsx
Agency administrators can manage access requests to their own agency, and Sys Admins can manage all access requests.
Also, removed ag-grid dependency
> PIMS-1417 Agency admins can approve access request in their own agency

- backend/core/Extensions/StringExtensions.cs
The formatting of a Postal Code resulted in a regression issue.  This PR resolves it.
> PIMS-2039 Fixing Postal Code bug

- maintenance/Caddyfile
- maintenance/README.md
- maintenance/maintenance.html
- maintenance/maintenance.sh
- openshift/templates/maintenance/caddy.bc.yaml
- openshift/templates/maintenance/caddy.dc.yaml
Add PIMS implementation of maintenance page used by GWELLS and TFRS. (This was my preferred implementation over what EAGLE and EDUC were doing).
Tested in DEV and works as expected.
> PIMS-1249 maintenance page

- backend/api/appsettings.Development.json
- backend/api/appsettings.Local.json
- backend/api/appsettings.Test.json
- backend/api/appsettings.json
The database is now initialized with a default user based on configuration.
You will either need to rebuild your local databases (`docker-compose`), or manually add the user.
Also update your local `.env`.
> Updating Connection Strings

- backend/core/Extensions/StringExtensions.cs
- frontend/src/components/common/form/Input.tsx
- frontend/src/forms/subforms/AddressForm.tsx
- frontend/src/forms/subforms/PidPinForm.tsx
- frontend/src/utils/YupSchema.tsx
Small changes
- pid formatting
- updating the postal format based off of some advice Devin gave me
- adding documentation for .FormatAsPostal()
> PID format and updating postal format

- maintenance/maintenance.sh
the json formatting provides the expected format for the latter pipe commands.
> fix overzealous use of find/replace.

- frontend/src/forms/ParcelDetailForm.tsx
- frontend/src/pages/SubmitProperty.tsx
Bug fixes for:
- auto filling agency in the parcel detail form on initial load 
- not being able to submit a second property while viewing an existing parcel detail
> PIMS-1697, 1709

- backend/dal/Configuration/ProjectConfiguration.cs
- backend/dal/Configuration/ProjectPropertyConfiguration.cs
- backend/dal/Configuration/ProjectStatusConfiguration.cs
- backend/dal/Configuration/ProjectTaskConfiguration.cs
- backend/dal/Configuration/TaskConfiguration.cs
- backend/dal/Configuration/TierLevelConfiguration.cs
- backend/dal/Migrations/20200520200830_Initial.Designer.cs
- backend/dal/Migrations/20200520200830_Initial.cs
- backend/dal/Migrations/Initial/PostDeploy/01-ProjectStatus.sql
- backend/dal/Migrations/Initial/PostDeploy/01-Tasks.sql
- backend/dal/Migrations/Initial/PostDeploy/01-TierLevels.sql
- backend/dal/Migrations/PimsContextModelSnapshot.cs
- backend/dal/PIMSContext.cs
- backend/entities/Building.cs
- backend/entities/Parcel.cs
- backend/entities/Project.cs
- backend/entities/ProjectProperty.cs
- backend/entities/ProjectStatus.cs
- backend/entities/ProjectTask.cs
- backend/entities/Task.cs
- backend/entities/TaskTypes.cs
- backend/entities/TierLevel.cs
This DB enhancement provides the following;
- a way to create projects and link properties (Parcel, Building) to the project.
- a list of project status
- a list of tier levels
- a list of tasks (checklists)
Please note that this is an initial draft design and will most likely require changes, but it should allow everyone to start building related features.
> PIMS-2056 Adding Projects to DB

- test/Postman/pims-api-collection.json
The Postman collection has been updated.
> Updating postman

- frontend/src/components/Table/PageSizeSelector.tsx
- frontend/src/components/Table/Table.tsx
- frontend/src/components/Table/__snapshots__/PageSizeSelector.test.tsx.snap
- frontend/src/components/menu/Menu.scss
- frontend/src/components/menu/Menu.tsx
- frontend/src/pages/admin/access/ManageAccessRequests.scss
- frontend/src/pages/admin/access/ManageAccessRequests.tsx
- frontend/src/pages/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/pages/admin/access/components/Filter.scss
- frontend/src/pages/admin/access/components/Filter.tsx
- frontend/src/pages/admin/access/components/RowActions.tsx
- frontend/src/pages/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/pages/admin/users/components/RowActions.tsx
Access Requests Scroll bug fixes
> PIMS-1755, PIMS-2033 PIMS-2034 PIMS-2036 Access Request page Scroll Bug Fixes

- backend/api/Areas/Project/Controllers/DisposeController.cs
- backend/api/Areas/Project/Mapping/Dispose/ProjectMap.cs
- backend/api/Areas/Project/Mapping/Dispose/ProjectPropertyMap.cs
- backend/api/Areas/Project/Mapping/Dispose/ProjectStatusMap.cs
- backend/api/Areas/Project/Mapping/Dispose/ProjectTaskMap.cs
- backend/api/Areas/Project/Mapping/Dispose/TaskMap.cs
- backend/api/Areas/Project/Models/Dispose/ProjectModel.cs
- backend/api/Areas/Project/Models/Dispose/ProjectPropertyModel.cs
- backend/api/Areas/Project/Models/Dispose/ProjectStatusModel.cs
- backend/api/Areas/Project/Models/Dispose/ProjectTaskModel.cs
- backend/api/Areas/Project/Models/Dispose/TaskModel.cs
- backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
- backend/api/Controllers/LookupController.cs
- backend/api/Mapping/Converters/AgencyConverter.cs
- backend/dal/Helpers/Extensions/ServiceCollectionExtensions.cs
- backend/dal/IPimsService.cs
- backend/dal/Migrations/Initial/PostDeploy/01-Tasks.sql
- backend/dal/PimsService.cs
- backend/dal/Services/Concrete/LookupService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/dal/Services/Concrete/TaskService.cs
- backend/dal/Services/ILookupService.cs
- backend/dal/Services/IProjectService.cs
- backend/dal/Services/ITaskService.cs
- backend/entities/ProjectTask.cs
- test/Postman/pims-api-collection.json
Basic endpoints for managing projects.
The following are the new endpoints that provide a way to view, add, update and delete projects.
- GET : /api/projects/disposal/{projectNumber}
- POST : /api/projects/disposal
- PUT: /api/projects/disposal/{projectNumber}
- DELETE : /api/projects/disposal/{projectNumber}
- GET : /api/lookup/project/tier/levels
- GET : /api/lookup/all
The following provide the project status/stages and checklists.
- GET : /api/projects/disposal/workflow
- GET : /api/projects/disposal/tasks
> Please note I have only tested this with Postman and I did not add/remove properties from the project yet.
> PIMS-2044 Disposal Project endpoints

- backend/api/Areas/Project/Controllers/SearchController.cs
- backend/api/Areas/Project/Mapping/Search/ProjectMap.cs
- backend/api/Areas/Project/Models/Search/ProjectFilterModel.cs
- backend/api/Areas/Project/Models/Search/ProjectModel.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/dal/Services/IProjectService.cs
- backend/entities/Models/ProjectFilter.cs
- backend/entities/Views/Property.cs
Adding way to search for projects and the ability to page through the results of a filter.
- GET : /api/projects/search/page?{filter}
- POST : /api/projects/search/page/filter
> Initial endpoint will most likely need to be enhanced once requirements are completed.
> PIMS-2070 Adding Search Projects

- backend/api/appsettings.json
- backend/dal/Configuration/ProjectConfiguration.cs
- backend/dal/Configuration/ProjectNumberConfiguration.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Migrations/20200522153222_Initial.Designer.cs
- backend/dal/Migrations/20200522153222_Initial.cs
- backend/dal/Migrations/Initial/PostDeploy/01-ProjectNumbers.sql
- backend/dal/Migrations/PimsContextModelSnapshot.cs
- backend/dal/Options/PimsOptions.cs
- backend/dal/Options/ProjectOptions.cs
- backend/dal/PIMSContext.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/entities/ProjectNumber.cs
When adding new project this will auto-generate the Project Number.
The format of the number is configurable in the appsettings.config.
> This will require another DB refresh.
> PIMS-2077 Project Number Auto-Generation

- frontend/src/components/layout/AppNavBar/AppNavBar.test.tsx
- frontend/src/components/layout/AppNavBar/AppNavBar.tsx
Updated navigation to only show "Dispose Properties".
> PIMS-1655 Update nav menu

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/project/disposal/ApprovalConfirmation.test.tsx
- frontend/src/components/project/disposal/ApprovalConfirmation.tsx
- frontend/src/components/project/disposal/StepActions.test.tsx
- frontend/src/components/project/disposal/StepActions.tsx
- frontend/src/components/project/disposal/__snapshots__/ApprovalConfirmation.test.tsx.snap
- frontend/src/components/project/disposal/__snapshots__/StepActions.test.tsx.snap
@devinleighsmith can you chime in here. I can use some guidance
> PIMS-1841 Confirm approval

- backend/api/Areas/Admin/Controllers/RoleController.cs
- backend/api/Areas/Project/Controllers/DisposeController.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/entities/Task.cs
- backend/tests/core/DatabaseHelper.cs
- backend/tests/core/Entities/ProjectHelper.cs
- backend/tests/core/Entities/ProjectStatusHelper.cs
- backend/tests/core/Entities/TaskHelper.cs
- backend/tests/core/Entities/TierLevelHelper.cs
- backend/tests/unit/api/Controllers/ParcelControllerTest.cs
- backend/tests/unit/api/Controllers/Project/DisposeControllerTest.cs
- backend/tests/unit/api/Controllers/Project/SearchControllerTest.cs
- backend/tests/unit/api/Controllers/Property/SearchControllerTest.cs
- backend/tests/unit/api/Routes/Admin/ClaimControllerTest.cs
- backend/tests/unit/api/Routes/Admin/RoleControllerTest.cs
- backend/tests/unit/api/Routes/Project/DisposeControllerTest.cs
- backend/tests/unit/api/Routes/Project/SearchControllerTest.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
- openshift/templates/pims-db/mssql-deploy.yaml
Expanding API unit-test to include new controllers.
> PIMS-2095 Adding Unit-Tests

- backend/core/Extensions/DictionaryExtensions.cs
- backend/core/Helpers/StringHelper.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/tests/core/Entities/TaskHelper.cs
- backend/tests/unit/dal/Core/Extensions/ArrayExtensionsTest.cs
- backend/tests/unit/dal/Core/Extensions/CollectionExtensionsTest.cs
- backend/tests/unit/dal/Core/Extensions/DictionaryExtensionsTest.cs
- backend/tests/unit/dal/Core/Helpers/CsvHelperTest.cs
- backend/tests/unit/dal/Core/Helpers/ExceptionHelper.cs
- backend/tests/unit/dal/Core/Helpers/StringHelperTest.cs
- backend/tests/unit/dal/Core/Helpers/XmlHelperTest.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
Additional unit-tests to cover add/update projects.
Additional unit-tests to cover core library functions.
> Fixed a few minor bugs while testing that were not effecting us yet.
> Adding API Coverage

- backend/api/Pims.Api.csproj
- backend/api/Startup.cs
- backend/api/appsettings.Local.json
- backend/api/appsettings.json
- backend/core/Pims.Core.csproj
- backend/dal.keycloak/Pims.Dal.Keycloak.csproj
- backend/dal/Pims.Dal.csproj
- backend/entities/Pims.Dal.Entities.csproj
- backend/keycloak/Pims.Keycloak.csproj
- backend/tests/core/Pims.Core.Test.csproj
- backend/tests/unit/api/Pims.Api.Test.csproj
- backend/tests/unit/dal/Pims.Dal.Test.csproj
- openshift/templates/backup/deploy.yaml
- openshift/templates/pims-api/build.yaml
- openshift/templates/pims-api/deploy.yaml
- openshift/templates/pims-db/mssql-deploy.yaml
Continued work on the production pipeline.
- Updating dependencies
- Forcing DB migration on API startup.  This isn't ideal, but the amount of effort to do it in the DevOps pipeline is becoming ridiculous.
- Removing HealthCheck UI from API
> PIMS-61 Forcing DB migration on API startup

- frontend/src/components/common/form/Input.tsx
Found another bug with my changes, should be fixed now.
> Restricted input fix

- frontend/src/components/maps/BuildingPopupView.test.tsx
- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/features/projects/dispose/steps/DocumentationStep.test.tsx
- frontend/src/features/projects/dispose/steps/ProjectDraftStep.test.tsx
- frontend/src/features/projects/dispose/steps/ReviewProjectStep.test.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.test.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/DocumentationStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ProjectDraftStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
Base layer of tests to build off of. I have remaining stories that I will be using these and adding more tests to. Also small changes to existing tests for the popup views.
> PIMS-2068, 2076, 2097

- openshift/templates/maintenance/caddy.bc.yaml
- openshift/templates/maintenance/caddy.dc.yaml
Updating Proxy Caddy build and deployment configuration.
Adding route to proxy caddy.
> PIMS-61 Maintenance Pod

- backend/api/Areas/Project/Mapping/Search/ProjectPropertyMap.cs
- backend/api/Areas/Project/Models/Search/ProjectPropertyModel.cs
- backend/api/Models/Parcel/ParcelModel.cs
- backend/dal/Helpers/Extensions/IdentityExtensions.cs
- backend/dal/Helpers/Extensions/ParcelExtensions.cs
- backend/dal/Services/Concrete/ParcelService.cs
- frontend/src/features/projects/list/interfaces.ts
- frontend/src/features/projects/list/properties/columns.tsx
- frontend/src/forms/subforms/BuildingForm.tsx
- frontend/src/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/pages/SubmitProperty.tsx
Editing if within active project
> PIMS-2217 Disable Property

- frontend/src/components/common/form/FastSelect.tsx
- frontend/src/components/common/form/LimitedSelect.test.tsx
- frontend/src/components/common/form/__snapshots__/LimitedSelect.test.tsx.snap
- frontend/src/constants/classifications.ts
- frontend/src/features/projects/dispose/components/columns.tsx
- frontend/src/features/projects/dispose/forms/disposalYupSchema.ts
**Ready for re-review**
*Update:
-  ~~separate component `LimitedSelect` which allows you to restrict what options you can select by passing an array of labels you wish to have appear~~
- added the functionality to `FastSelect` no longer a separate component 
- existing value will load with the option attribute hidden so it will not appear in drop down but be visible initially
> Unit tests for Classification Options

- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/ProjectDisposeView.tsx
- frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeLayout.test.tsx.snap
- frontend/src/features/projects/dispose/forms/disposalYupSchema.ts
- frontend/src/features/projects/dispose/hooks/useStepper.ts
- frontend/src/features/projects/dispose/interfaces.ts
- frontend/src/features/projects/dispose/steps/__snapshots__/ProjectDraftStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
Now when navigating to **Dispose Properties** it will start at the route `/draft` once the minimum of a name is entered you may click save/next and the project will be created and the project number (draft) will be generated.
Moved around some code in a way that made sense in my mind in order to accomplish this. Please let me know if there is something that looks out of the ordinary.
> PIMS-2389 - Don't create project until name is entered

- frontend/src/features/projects/dispose/components/StepActions.test.tsx
- frontend/src/features/projects/dispose/components/StepActions.tsx
- frontend/src/features/projects/dispose/hooks/useStepForm.tsx
- frontend/src/forms/ParcelDetailForm.tsx
Also update formik status errors to be more user friendly if possible.
> PIMS-2450 conditionally disable save/next buttons based on permissions.

- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
Fixing bug I introduced after my last PR
> PIMS-2457 (Fix stepper not loading on refresh)

- frontend/src/features/projects/dispose/steps/DocumentationStep.test.tsx
- frontend/src/features/projects/dispose/steps/DocumentationStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/DocumentationStep.test.tsx.snap
Still working out kinks in the other tests I've written but throwing this one up in the meantime
> PIMS-2205 (Checklist validation)

- backend/api/Areas/Project/Controllers/DisposeController.cs
- backend/dal/Migrations/Initial/PostDeploy/01-WorkflowProjectStatus.sql
- backend/dal/Services/Concrete/ProjectService.cs
- backend/dal/Services/IProjectService.cs
- backend/tests/core/Entities/ProjectStatusHelper.cs
- backend/tests/core/Entities/WorkflowHelper.cs
- backend/tests/unit/api/Controllers/Project/DisposeControllerTest.cs
- backend/tests/unit/dal/Services/BuildingServiceTest.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
Unit-tests for project status workflow updates.
Fixing validation bugs related to incomplete tasks.
> PIMS-2379 Workflow Project Status Update

- backend/tools/keycloak/sync/README.md
There were some missing documented details for getting a new instance of Keycloak running.
I have updated the documentation to reflect this.
> Updating Keycloak Sync Document

- backend/dal/Services/Concrete/ProjectService.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
When updating projects it should return the project with the updated information (i.e. RowVersion)
> PIMS-2043 Returning updated project

- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/forms/PropertyListViewSelect.test.tsx
- frontend/src/features/projects/dispose/forms/UpdateInfoForm.test.tsx
- frontend/src/features/projects/dispose/forms/__snapshots__/PropertyListViewSelect.test.tsx.snap
- frontend/src/features/projects/dispose/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/dispose/steps/DocumentationStep.tsx
- frontend/src/features/projects/dispose/steps/ProjectDraftStep.test.tsx
- frontend/src/features/projects/dispose/steps/ProjectDraftStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/ProjectDraftStep.test.tsx.snap
Unit tests and bug fix for read only view on preDraft state in  Dispose Properties.
To go in after Jeremy's and Devin's PRs - might need to adjust tests.
Marked some files as outdated via comments as they will be covered by Devin's PR and removed from this PR after merge
> PIMS-2461, 2400, 2391, 2088

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Migrations/Initial/PostDeploy/01-ProjectStatus.sql
- backend/dal/Migrations/Initial/PostDeploy/01-ProjectStatusTransitions.sql
- backend/dal/Services/Concrete/ProjectService.cs
- backend/tests/core/Entities/ProjectStatusHelper.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/ProjectWorkflowComponents.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveActions.tsx
- frontend/src/features/projects/dispose/components/SelectProjectPropertiesPage.tsx
- frontend/src/features/projects/dispose/forms/ReviewApproveForm.scss
- frontend/src/features/projects/dispose/forms/ReviewProjectForm.scss
- frontend/src/features/projects/dispose/forms/ReviewProjectForm.tsx
- frontend/src/features/projects/dispose/forms/UpdateInfoForm.test.tsx
- frontend/src/features/projects/dispose/hooks/useStepForm.tsx
- frontend/src/features/projects/dispose/hooks/useStepper.ts
- frontend/src/features/projects/dispose/interfaces.ts
- frontend/src/features/projects/dispose/projectConverter.ts
- frontend/src/features/projects/dispose/projectsActionCreator.ts
- frontend/src/features/projects/dispose/slices/projectSlice.ts
- frontend/src/features/projects/dispose/slices/projectWorkflowSlice.ts
- frontend/src/features/projects/dispose/steps/DocumentationStep.test.tsx
- frontend/src/features/projects/dispose/steps/DocumentationStep.tsx
- frontend/src/features/projects/dispose/steps/ProjectDraftStep.test.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.tsx
- frontend/src/features/projects/dispose/steps/ReviewProjectStep.test.tsx
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.test.tsx
Refactor project dispose layout and useStepForm to simplify code and
communication with backend.
> PIMS-2453 PIMS-2444, PIMS-2452

- frontend/src/features/projects/list/ProjectListView.tsx
> quick fix for listview links.

- backend/dal/Helpers/Extensions/ServiceExtensions.cs
- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/ProjectDisposeView.tsx
- frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeLayout.test.tsx.snap
- frontend/src/features/projects/list/ProjectListView.tsx
> Remove debugger statement.

- frontend/src/buttons.scss
- frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeLayout.test.tsx.snap
- frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeView.test.tsx.snap
- frontend/src/features/projects/dispose/components/StepActions.tsx
- frontend/src/features/projects/dispose/components/__snapshots__/StepActions.test.tsx.snap
- frontend/src/features/projects/dispose/hooks/useStepForm.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.test.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.tsx
updating permissions to be in sync with latest changes.
> Pims 2448, PIMS-2450

- backend/api/Areas/Project/Mapping/Dispose/ProjectMap.cs
- backend/api/Areas/Project/Mapping/Dispose/ProjectTaskMap.cs
- backend/api/Areas/Project/Models/Dispose/ProjectModel.cs
- backend/api/Areas/Project/Models/Dispose/ProjectTaskModel.cs
- backend/dal/Services/Concrete/ProjectService.cs
- frontend/src/components/common/form/Select.tsx
- frontend/src/constants/API.ts
- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveActions.test.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveActions.tsx
- frontend/src/features/projects/dispose/forms/AppraisalCheckListForm.tsx
- frontend/src/features/projects/dispose/forms/FirstNationsCheckListForm.tsx
- frontend/src/features/projects/dispose/forms/ReviewApproveForm.tsx
- frontend/src/features/projects/dispose/forms/ReviewProjectForm.tsx
- frontend/src/features/projects/dispose/forms/UpdateInfoForm.tsx
- frontend/src/features/projects/dispose/hooks/useStepForm.tsx
- frontend/src/features/projects/dispose/hooks/useStepper.ts
- frontend/src/features/projects/dispose/interfaces.ts
- frontend/src/features/projects/dispose/projectConverter.ts
- frontend/src/features/projects/dispose/projectsActionCreator.ts
- frontend/src/features/projects/dispose/steps/ApprovalConfirmationStep.tsx
- frontend/src/features/projects/dispose/steps/DocumentationStep.test.tsx
- frontend/src/features/projects/dispose/steps/DocumentationStep.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.test.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.tsx
- frontend/src/features/projects/dispose/steps/ReviewProjectStep.test.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/interfaces.ts
Also correct bugs in frontend introduced by https://github.com/bcgov/PIMS/pull/333
> Update frontend to use status codes not IDs.

- backend/api/Mapping/Parcel/ParcelMap.cs
- frontend/src/forms/subforms/PidPinForm.tsx
Bug 1 - Project number is now read only for SRES until they click the edit button
Bug 2 - Project number no longer disappears when updating a parcel
> PIMS-2586, 2587

- frontend/src/features/projects/dispose/forms/ReviewProjectForm.tsx
Tiny thing I noticed while doing some testing, just wanted to get it in in case it is blocking anyone.
> Documentation Review Bug

- frontend/src/features/projects/dispose/components/ApprovalActions.tsx
- frontend/src/features/projects/dispose/hooks/useStepForm.tsx
- frontend/src/features/projects/dispose/steps/ApprovalStep.test.tsx
- frontend/src/features/projects/dispose/steps/ApprovalStep.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.test.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/ApprovalStep.test.tsx.snap
- frontend/src/features/projects/dispose/strings.ts
Completes PIMS-2570 (first pass at PIMS-2548 already provided basic cancellation functionality).
> Cancellation logic improvements. Tests.

- backend/dal/Services/Concrete/NotificationQueueService.cs
I had originally locked down notifications, but the reality is they are generated by other workflows (`project-add`, `project-edit`).
> PIMS-2613 Fixing permissions with notifications

- backend/dal/Services/Concrete/ProjectService.cs
- frontend/src/features/projects/dispose/components/ExemptionRequest.scss
- frontend/src/features/projects/dispose/components/ReviewApproveActions.test.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveActions.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveExemption.test.tsx
Also quick fix so SPP number is generated with `Submitted Exemption`
> Small UI tweaks

- backend/api/appsettings.json
- backend/dal/Options/ProjectOptions.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/tests/core/ControllerHelper.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
Task validation should only occur when a status changes, additionally it shouldn't be required if **Denying** or **Cancelling** a project is triggered.
> PIMS-2628 Task Validation Change

- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/components/ApprovalActions.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveActions.test.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveActions.tsx
- frontend/src/features/projects/dispose/components/ReviewApproveExemption.test.tsx
- frontend/src/features/projects/dispose/forms/ApprovalForm.tsx
- frontend/src/features/projects/dispose/hooks/useStepForm.tsx
- frontend/src/features/projects/dispose/steps/ReviewApproveStep.tsx
- frontend/src/features/projects/dispose/tabs/EnhancedReferralTab.tsx
- Also update review approval form to allow deny with no validation.
- Correct potential race condition with usage of set... and useState().
> PIMS-2623, PIMS-2624, PIMS-2627, PIMS-2629

- frontend/src/features/projects/dispose/forms/ReviewApproveForm.tsx
> Remove alert

- openshift/pipelines/Jenkinsfile.cicd
- openshift/pipelines/Jenkinsfile.test-to-prod
- openshift/player.sh
- openshift/scripts/common.sh
- openshift/scripts/oc-backup.sh
- openshift/scripts/oc-build.sh
- openshift/scripts/oc-deploy.sh
- openshift/templates/jenkins/generic-pipeline.yaml
Quick PR to address a couple things found:
- Renamed env var `JOB_NAME` to `OC_JOB_NAME` - name was already taken by Jenkins
- Make the `player.sh` wrapper script fail when any of the `oc-commands` fail
- Rename apply option to `-apply` --> `player.sh <...> -apply`
> Devops pipeline improvements and bug fixes

- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- backend/tests/unit/dal/Services/ParcelServiceTest.cs
- frontend/src/components/common/form/AutoCompleteText.tsx
- frontend/src/components/common/form/Select.tsx
- frontend/src/features/properties/components/forms/ParcelDetailForm.test.tsx
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/LandForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/utils/utils.ts
> PIMS-1831 (SRES ability to edit agency)

- openshift/templates/pims-api/deploy.yaml
Need to update the OpenShift deployment configuration to include CHES secrets.
> Fixing CHES integration environment config

- backend/api/Areas/Notification/Controllers/QueueController.cs
- backend/dal/Services/Concrete/NotificationQueueService.cs
- backend/dal/Services/Concrete/NotificationTemplateService.cs
I incorrectly only allowed `system-admin` claim to fetch notification templates.
> PIMS-1984 Fixing fetch template permission

- backend/ches/ChesService.cs
- backend/core/Extensions/EnumerableExtensions.cs
DEV behaves differently than locally for some reason.  Not sure why CHES complains about empty string values.
> PIMS-1984 Removing empty values from email

- frontend/src/features/projects/assess/forms/ReviewApproveForm.tsx
- frontend/src/features/projects/assess/steps/ReviewApproveStep.tsx
Few changes so that it matches up with the new workflow layout - previously could not approve for exemption after changes
> Exemption Approve Bug Fix

- backend/api/Areas/Project/Mapping/Search/ProjectPropertyMap.cs
- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/api/Areas/Tools/Mapping/Import/ProjectAgencyResponseMap.cs
- backend/api/Areas/Tools/Mapping/Import/ProjectMap.cs
- backend/api/Areas/Tools/Mapping/Import/ProjectNoteMap.cs
- backend/api/Areas/Tools/Models/Import/ImportPropertyModel.cs
- backend/api/Areas/Tools/Models/Import/ProjectAgencyResponseModel.cs
- backend/api/Areas/Tools/Models/Import/ProjectModel.cs
- backend/api/Areas/Tools/Models/Import/ProjectNoteModel.cs
- backend/api/Startup.cs
- backend/core/Exceptions/HttpClientRequestException.cs
- backend/core/Extensions/IdentityExtensions.cs
- backend/core/Extensions/TypeExtensions.cs
- backend/core/Http/OpenIdConnectRequestClient.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ProjectService.cs
- backend/tests/unit/api/Controllers/Project/WorkfowControllerTest.cs
- backend/tests/unit/api/Controllers/Tools/ImportControllerTest.cs
- backend/tests/unit/api/Routes/Tools/ImportControllerTest.cs
Adding unit tests for better coverage.
Resolving some SonarQube related issues.
> PIMS-1984 Adding tests

- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/spl/steps/SplStep.test.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
Also need to add tests for the transition workflow(s) - keeping the PRs small.
> SPL workflow tests.

- frontend/src/buttons.scss
- frontend/src/features/projects/assess/forms/ReviewApproveForm.scss
- frontend/src/features/projects/common/ProjectRouter.tsx
- frontend/src/features/projects/spl/steps/SplStep.test.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
low hanging fruit:
-Made the buttons slightly more disabled looking. Changed disabled cursor.
-Removed yellow boxes on review project disposal form.
-Fixed display of some terminal statuses.
> low hanging fruit:

- frontend/src/components/SearchBar/FilterBar.tsx
- frontend/src/components/common/form/AutoCompleteText.tsx
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/features/admin/users/components/UsersFilterBar.tsx
- frontend/src/features/projects/list/ProjectListView.scss
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
Polishing up the filter bar for project list view. Now resets properly and UI has been tweaked
> PIMS-2888 (Reset Filter on Project List View)

- backend/ches/ChesService.cs
Currently we are BCCing SRES when sending test notifications.
After this update emails will only go to the current account when testing.
> Fixing BCC notification issue

- frontend/src/components/common/form/Input.tsx
The data was there but the input field was not being updated with Formik values due to PID running custom logic to format the value
> PIMS-2685 Submit Property - Unsaved Draft - Not saving PID

- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
- backend/core/Extensions/EnumerableExtensions.cs
- backend/dal/Helpers/Extensions/EntityExtensions.cs
- backend/dal/Helpers/Extensions/IdentityExtensions.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/ParcelService.cs
- backend/dal/Services/Admin/Concrete/ProjectService.cs
- backend/dal/Services/Concrete/TaskService.cs
- backend/entities/ProjectTask.cs
- backend/tests/unit/api/Controllers/Tools/ImportControllerTest.cs
- backend/tests/unit/dal/Services/Admin/ParcelServiceTest.cs
Project import now includes all tasks.
> Adding tasks to Project import

- backend/api/Areas/Property/Controllers/BuildingController.cs
- backend/api/Areas/Property/Controllers/ParcelController.cs
- backend/api/Areas/Property/Controllers/SearchController.cs
- backend/api/Helpers/Middleware/ResponseTimeMiddleware.cs
- backend/api/Startup.cs
- backend/tests/unit/api/Routes/Property/BuildingControllerTest.cs
- backend/tests/unit/api/Routes/Property/ParcelControllerTest.cs
- frontend/src/constants/API.ts
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useApi.ts
The Property List View currently takes far too long to respond since importing the latest SIS data.
This change removes the incorrect HTTP query parameter `agencies` from the standard request.
- Moved controllers and updated routes.
- Added middleware to provide response time information
> Improving performance on Property List View

- .gitignore
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/utils/YupSchema.ts
> PIMS-1746 Add lot size validation to map filter form

- frontend/src/features/account/Login.tsx
- frontend/src/features/projects/erp/tabs/ErpTabs.tsx
- frontend/src/hooks/use-query.ts
- frontend/src/utils/PrivateRoute.tsx
PIMS-2864 after login redirect link
> PIMS-2900 ExemptionERP Tab label,

- frontend/src/components/layout/AppNavBar/AppNavBar.scss
- frontend/src/components/layout/AppNavBar/AppNavBar.tsx
- frontend/src/components/layout/AppNavBar/__snapshots__/AppNavBar.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
Updating the building form with the bug fix from last sprint. And preliminary home button
> Building agency bug

- adr/ches.md
- adr/database.md
- adr/geocoder.md
- adr/monorepo.md
- openshift/README.md
- openshift/SSL_CERTIFICATES.md
Document how to request and install SSL certificates for DNS record.
Also cleaned up existing documentation a bit (mainly typos)
> PIMS-2568 DevOps - Update pims.gov.bc.ca DNS record

- backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- tools/converters/excel/Configuration/ActionArgumentOptions.cs
- tools/converters/excel/Configuration/ActionOptions.cs
- tools/converters/excel/Configuration/RowOptions.cs
- tools/converters/excel/Configuration/SourceOptions.cs
- tools/converters/excel/Converter.cs
- tools/converters/excel/Converters/GeoLocationConverter.cs
- tools/converters/excel/Converters/StringConverters.cs
- tools/converters/excel/appsettings.json
Currently having issues importing properties into production.
- Cleaning up import data
- Adding logging to bad requests
> Import Improvements and Prod Debug

- frontend/src/components/Table/Table.scss
- frontend/src/components/Table/Table.tsx
- frontend/src/features/projects/list/properties/index.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
Still ironing out some bugs in my last few tasks - putting this up in the meantime to split things up
> UI for grouping buildings

- backend/dal/Migrations/Initial/PostDeploy/01-Tasks.sql
> Fixing spelling in Tasks

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
Fix - Property Detail View was disabled when adding new properties.
Fix - Submitting properties with 0 Rentable Area
Fix - Transfer within GRE
> PIMS-2489 Fix editing properties

- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
Still need to figure out why the agency is not updating for the parcel
> Show building agency for everyone

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
Project Status needed to be forced loaded.
> Fix parcel project loading bug.

- frontend/package.json
- frontend/src/components/common/form/SppButton.test.tsx
- frontend/src/components/common/form/__snapshots__/SppButton.test.tsx.snap
- frontend/src/components/layout/Footer/Footer.test.tsx
- frontend/src/components/layout/Footer/__snapshots__/Footer.test.tsx.snap
- frontend/src/features/admin/access/components/AccessRequestActions.test.tsx
- frontend/src/features/admin/access/components/__snapshots__/AccessRequestActions.test.tsx.snap
- frontend/src/features/projects/erp/tabs/EnhancedReferralTab.test.tsx
- frontend/src/features/projects/erp/tabs/__snapshots__/EnhancedReferralTab.test.tsx.snap
- frontend/src/features/properties/components/forms/ParcelDetailForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/PidPinForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PidPinForm.test.tsx.snap
- frontend/src/pages/401/AccessDenied.test.tsx
- frontend/src/pages/401/__snapshots__/AccessDenied.test.tsx.snap
- frontend/src/pages/404/NotFoundPage.test.tsx
- frontend/src/pages/404/__snapshots__/NotFoundPage.test.tsx.snap
- frontend/src/utils/testUtils.ts
Added unit tests for geocoder integration. Also added a bunch of snapshots to increase code coverage.
> PIMS-2740 geocoder tests

- backend/tests/unit/dal/Services/ProjectServiceTest.cs
Adding unit tests for shared note notifications.
> PIMS-2861 Shared note notification unit test

- frontend/src/components/Table/Table.tsx
- frontend/src/features/properties/list/FilterBar.test.tsx
- frontend/src/features/properties/list/FilterBar.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
Include buildings in property list in addition to them being grouped with the parcel - but do not show a folder for buildings
> Include buildings in property list

- frontend/src/actions/parcelsActions.ts
- frontend/src/components/maps/BuildingPopupView.test.tsx
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/__snapshots__/BuildingPopupView.test.tsx.snap
- frontend/src/components/maps/__snapshots__/ParcelPopupView.test.tsx.snap
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/features/properties/components/forms/ParcelDetailForm.scss
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/LandForm.tsx
- frontend/src/features/properties/components/forms/subforms/PidPinForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PidPinForm.test.tsx.snap
- frontend/src/mocks/filterDataMock.ts
- frontend/src/utils/YupSchema.ts
> Devin is on vacation.  To rebase his branch I've cloned and re-posted this PR.
Adding `Name` and `Description` to Parcels and Buildings.
> PIMS-2160 add name and description to parcel/building detail and popups.

- backend/api/Areas/Property/Models/Search/PropertyFilterModel.cs
- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- backend/entities/Models/AllPropertyFilter.cs
- backend/entities/Models/ParcelFilter.cs
- frontend/src/actionCreators/parcelsActionCreator.spec.ts
- frontend/src/actionCreators/parcelsActionCreator.ts
- frontend/src/components/maps/MapFilterBar.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/constants/API.ts
- frontend/src/features/projects/common/components/FilterBar.tsx
- frontend/src/features/projects/common/interfaces.ts
- frontend/src/features/projects/dispose/hooks/useTable.ts
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/properties/list/FilterBar.test.tsx
- frontend/src/features/properties/list/FilterBar.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/__snapshots__/FilterBar.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/properties/list/interfaces.ts
- frontend/src/features/properties/map/MapView.tsx
- frontend/src/features/properties/submit/SubmitProperty.tsx
You can now search by PID or PIN on the Landing Page, Property List View and the Project Select Properties View.
> Thanks Jonny!
> PIMS-2610 Search by PID or PIN

- frontend/src/features/properties/components/forms/ParcelDetailForm.scss
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/submit/SubmitProperty.scss
Took me a bit longer than I would have liked but here it is!
> Submit hover

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
Attempting to improve the SQL to reduce the chance of the memory bug.
> Clean up Property List View query

- .github/CODEOWNERS
- Makefile
- auth/README.md
- auth/keycloak/README.md
- auth/keycloak/config/realm-export.json
- docker-compose.yml
- frontend/public/keycloak.json
- scripts/gen-env-files.sh
- tools/keycloak/sync/realm.development.json
- tools/keycloak/sync/realm.json
- tools/keycloak/sync/realm.local.json
- tools/keycloak/sync/realm.test.json
Fixed keycloak initialization.
Cleaned up `make` file.
Tested setup.
> Fixing keycloak setup

- backend/dal/Configuration/AddressConfiguration.cs
- backend/dal/Configuration/BuildingConfiguration.cs
- backend/dal/Configuration/BuildingEvaluationConfiguration.cs
- backend/dal/Configuration/BuildingFiscalConfiguration.cs
- backend/dal/Configuration/CityConfiguration.cs
- backend/dal/Configuration/ParcelConfiguration.cs
- backend/dal/Configuration/ParcelEvaluationConfiguration.cs
- backend/dal/Configuration/ParcelFiscalConfiguration.cs
- backend/dal/Migrations/20200925194028_v01.00.01.Designer.cs
- backend/dal/Migrations/20200925194028_v01.00.01.cs
- backend/dal/Migrations/Initial/PostDeploy/01-Agencies.sql
- backend/dal/Pims.Dal.csproj
- backend/dal/Services/Concrete/PropertyService.cs
- docker-compose.yml
Presently the database container in OpenShift run out of memory when a large query is submitted.  To resolve this the container maximum memory has been increased, along with improving indexes for performance.
- Improving indexes
- Fixing seed script
- Fixing ef migration issue
> PA-203 mssql server memory issue

- frontend/src/features/properties/map/MapView.tsx
I reinstalled husky and it reinitialized my hooks, I think I'm good now.
> prettier fix.

- frontend/src/features/properties/components/forms/ParcelDetailForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
updating existing unit tests to add checks for name and description.
> PA-594 Unit tests for Name & Description

- backend/dal/Services/Concrete/PropertyService.cs
- backend/tests/unit/dal/Services/PropertyServiceTest.cs
Fixed API properties searching paging.
> pa-203 Fixing paging

- frontend/src/features/properties/components/forms/subforms/PagedBuildingForms.test.tsx
- frontend/src/features/properties/components/forms/subforms/PagedBuildingForms.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
Ended up removing my modal test as it was causing havoc. Original test still works for testing of removal functionality.
> Popup for deleting building 

- Makefile
- scripts/gen-env-files.sh
Updated setup script to include the `.env` for the DAL.
Updated setup password generation to include by default 3 specific characters to ensure the password meets the minimum requirements for MS SQL.
> pa-201 Updating setup script

- frontend/src/features/properties/components/forms/ParcelDetailForm.test.tsx
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
Really quick story! Will ask in RC what to pull in next.
> PIMS-809, 810

- backend/dal/Migrations/20200930210531_DisableRoles.cs
- frontend/src/App.scss
- frontend/src/constants/toasts.ts
Override default toast style with pims colors.
> Use Pims colors in toasts.

- backend/dal/Migrations/20200930210531_DisableRoles.cs
- frontend/src/components/common/Stepper.scss
- frontend/src/features/projects/dispose/ProjectDisposeView.scss
All breakpoints create a reasonably sized stepper for the corresponding screen width.
Vertical stepper only in use in mobile-sized screens.
> Create media breakpoints for dispose project stepper. 

- test/Integration/SubmitDeleteProperty.py
Integration test example of submitting and deleting a property for learning purposes. Structure to change (separate into individual tests etc.), also may switch over to groovy as that is what other teams have done. (**Do we still want this in source?**)
> Integration example

- frontend/src/features/properties/components/forms/ParcelDetailForm.test.tsx
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/EvaluationCols.tsx
- frontend/src/features/properties/components/forms/subforms/EvaluationForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
> PA-980, 993

- frontend/src/features/account/Login.scss
- frontend/src/features/account/Login.test.tsx
- frontend/src/features/account/Login.tsx
- frontend/src/features/account/__snapshots__/Login.test.tsx.snap
> Login page changes

- frontend/src/features/account/Login.scss
- frontend/src/features/account/Login.tsx
- frontend/src/features/account/__snapshots__/Login.test.tsx.snap
- frontend/src/features/projects/common/components/ManualLink.scss
- frontend/src/features/projects/common/components/ManualLink.tsx
- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
> Parcel Detail View - Link to policy

- frontend/src/features/account/Login.tsx
- frontend/src/features/account/__snapshots__/Login.test.tsx.snap
Minor change to meet requirements
> Login page tweak

- frontend/src/features/properties/components/forms/ParcelDetailForm.tsx
Format GeoCoder format when Conflicting PID popup appears on the parcel detail form.
> Property Detail View - Geocoder PID Format

- backend/dal/Services/Concrete/ProjectReportService.cs
- backend/tests/core/Entities/ProjectReportHelper.cs
- backend/tests/core/Entities/ProjectSnapshotHelper.cs
- backend/tests/unit/api/Controllers/Project/ReportControllerTest.cs
- backend/tests/unit/dal/Services/ProjectReportServiceTest.cs
- frontend/src/App.scss
- frontend/src/features/splReports/components/ReportControls.tsx
- frontend/src/features/splReports/components/SplReportLayout.scss
report controller and service tests. Also contains some fixes to backend issues found during testing and one frontend issue found during regression testing.
> PA-635 Backend tests and related code fixes.

- Makefile
> Removing duplicate make cmd

- frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
- frontend/src/components/maps/leaflet/LayerPopup/constants/index.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeLayout.test.tsx.snap
- frontend/src/features/projects/dispose/components/__snapshots__/StepActions.test.tsx.snap
- frontend/src/features/projects/erp/forms/__snapshots__/ExemptionEnhancedReferralCompleteForm.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/splReports/containers/__snapshots__/SplReportContainer.test.tsx.snap
- frontend/src/setupTests.ts
After a meeting with Mikaela and Lindsay, we came up with a list of fields to be displayed in the layer popup. This ticket changes the layer popup content to match the requirements. 
Also, I noticed that we have added lots of styled-components and the tests did not include/import the jest-styled-components for consistent classNames. I imported the `jest-styled-components` globally in the test setup to address that.
> PA-1514 change layer popup contents

- frontend/src/components/maps/leaflet/Map.tsx
@goemen you must have done a `--no-verify` push.
> Fixing format

- frontend/src/buttons.scss
- frontend/src/components/SearchBar/__snapshots__/FilterBar.test.tsx.snap
- frontend/src/components/common/GenericModal.tsx
- frontend/src/components/common/form/ResetButton.tsx
- frontend/src/components/common/form/SearchButton.tsx
- frontend/src/components/maps/__snapshots__/MapFilterBar.test.tsx.snap
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/features/admin/access/components/Details.tsx
- frontend/src/features/admin/access/components/Filter.tsx
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/help/components/HelpModal.tsx
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/dispose/components/StepActions.tsx
- frontend/src/features/projects/dispose/components/__snapshots__/StepActions.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/FilterBar.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/splReports/components/ReportControls.tsx
Changed some button definitions to match the BCGov style guide and changed some button calls  for more visual consistency
> Edited button definition and calls

- backend/dal/Migrations/20201106185406_v01.02.01.Designer.cs
- backend/dal/Migrations/20201106185406_v01.02.01.cs
- backend/dal/Migrations/v01.02.01/Up/PostUp/01-AdministrativeAreas.sql
Adding a migration to seed the administrative area with municipality records extracted from the layer.
> PA-1213 seed database with Municipality  Administrative areas

- Makefile
- backend/dal/Services/Concrete/ParcelService.cs
Resolves a bug when attempting to add or delete buildings.
Also adds new `make rebuild` command to speed up development.
> PA-1210 Fixing api updating buildings

- backend/api/Areas/Project/Controllers/DisposeController.cs
- backend/api/Areas/Project/Mapping/Dispose/BuildingMap.cs
- frontend/src/features/properties/list/PropertyListView.test.tsx
This should resolve the issue currently blocking the ability to add properties to projects.
> Fix disposal project bug

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
Adding layers to the map and updating unit-tests.  Was unable to entirely fix the unit-tests for the map, but was able to resolve a number of issues with them.
- https://catalogue.data.gov.bc.ca/dataset/tantalis-crown-land-leases
- https://catalogue.data.gov.bc.ca/dataset/tantalis-crown-land-inventory
- https://catalogue.data.gov.bc.ca/dataset/tantalis-crown-land-inclusions
- https://catalogue.data.gov.bc.ca/dataset/alc-agricultural-land-reserve-lines
> PA-992 Adding Layers to map

- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/__snapshots__/ParcelPopupView.test.tsx.snap
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/features/properties/hooks/useDraftMarkerSynchronizer.tsx
fix view only mode display of parcel pins.
> fix delay in draft pin updates.

- frontend/src/components/SearchBar/FilterBar.tsx
- frontend/src/components/SearchBar/ParentGroupedFilter.test.tsx
- frontend/src/components/SearchBar/__snapshots__/ParentGroupedFilter.test.tsx.snap
- frontend/src/components/common/form/PlusButton.tsx
- frontend/src/features/admin/agencies/EditAgencyPage.test.tsx
- frontend/src/features/admin/agencies/ManageAgencies.test.tsx
- frontend/src/features/admin/agencies/__snapshots__/EditAgencyPage.test.tsx.snap
- frontend/src/features/admin/agencies/__snapshots__/ManageAgencies.test.tsx.snap
- frontend/src/features/admin/edit-user/EditUserPage.test.tsx
- frontend/src/features/admin/users/ManageUsers.test.tsx
- frontend/src/features/admin/users/ManageUsersPage.tsx
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/admin/users/components/UsersFilterBar.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/utils/YupSchema.ts
New grouped filter now added to users section and project list view
**Update: now with frontend unit tests**
> Adding group filter to user management/proj list

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/Stepper.tsx
- frontend/src/components/common/form/StepForm/SteppedForm.md
- frontend/src/components/common/form/StepForm/SteppedForm.tsx
- frontend/src/components/common/form/StepForm/StepperField.md
- frontend/src/components/common/form/StepForm/StepperField.tsx
- frontend/src/components/common/form/StepForm/context.tsx
- frontend/src/components/common/form/StepForm/index.ts
- frontend/src/components/common/form/StepForm/types.ts
- frontend/src/features/projects/dispose/__snapshots__/ProjectDisposeLayout.test.tsx.snap
- frontend/src/features/projects/dispose/components/GeneratedDisposeStepper.tsx
- frontend/styleguide.config.js
A component to display a stepped form controlled by formik. @jdtoombs  can start using the component while I added the persistence with formik and writing unit tests.
Read the component usage example for more on how to use
I also added styleguidist tooling to help with the documentation of our shared react components. https://react-styleguidist.js.org/docs/getting-started/.  In your local environment, `cd frontend && npm install && npm run docu:server`, and you can view the default documentation generated by styleguidist at `http://localhost:6060`.  I will give a detailed demo of how it works on Thursday knowledge sharing.
> PA-1665 StepperForm component

- backend/tests/unit/dal/Libraries/Ches/ChesExceptionTest.cs
Added 5 tests for the ChesException constructors.
> PA 645 - ChesExceptions test cases

- backend/tests/unit/dal/Libraries/Ches/ChesExceptionTest.cs
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/UpdateInfoForm.tsx
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/common/strings.ts
- frontend/src/features/projects/dispose/forms/ReviewProjectForm.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
> PA-1424: Update Dispose Properties tooltips

- .github/workflows/api-dotnetcore.yml
- .github/workflows/app-react.yml
I believe this is why Goeme's PR is stuck!
> add dev-alpha to github actions

- frontend/src/components/common/TooltipIcon.scss
- frontend/src/components/common/form/FastSelect.tsx
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/features/admin/access/ManageAccessRequests.tsx
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/admin/agencies/__snapshots__/EditAgencyPage.test.tsx.snap
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
- frontend/src/features/mapSideBar/containers/__snapshots__/MapSideBarContainer.test.tsx.snap
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/UpdateInfoForm.tsx
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/common/strings.ts
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/strings.ts
- frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
- frontend/src/features/properties/components/forms/subforms/InformationForm.tsx
- frontend/src/features/properties/components/forms/subforms/LandForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
Created some tool tips/text that Jonny can add to the new add building/land wizard. Also fixed other small spelling/wording issues
> Pa-1668: property detail view tooltips

- frontend/src/components/maps/BuildingPopupView.scss
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.scss
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/PopupView.tsx
- frontend/src/components/maps/__snapshots__/BuildingPopupView.test.tsx.snap
- frontend/src/components/maps/__snapshots__/ParcelPopupView.test.tsx.snap
- frontend/src/components/maps/hooks/useMarkerZoom.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/__snapshots__/MapProperties.test.tsx.snap
- frontend/src/features/properties/hooks/useDraftMarkerSynchronizer.tsx
- frontend/src/features/properties/map/MapView.tsx
Adds a zoom button that takes you to a level where you should be able to differentiate points (as long as they aren't on the exact same lat/lng).
> Provide zoom to marker functionality on the mapview.

- frontend/src/components/Table/Table.scss
- frontend/src/components/Table/Table.tsx
- frontend/src/components/layout/Header/Header.tsx
- frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
> pa-1693,1483: change folder icon colour, BC logo to BC Gov website

- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
The query to determine existing buildings was flipped incorrectly.  This should resolve this issue.
> Fixed building import

- openshift/pipelines/Jenkinsfile.cicd
Fix bug with the alpha pipeline where the app name environment variable was being ignored.
> Ensure app name env var is used.

- frontend/src/components/SearchBar/ParentGroupedFilter.tsx
- frontend/src/components/common/form/Typeahead.tsx
Fix agency filter populating with id on change.
Based off of Jeremy's solution and Devin's comment!
> Agency filter fix

- backend/api/Areas/Reports/Mapping/Project/ProjectMap.cs
- backend/api/Areas/Reports/Models/Project/ProjectModel.cs
- frontend/src/features/projects/list/ProjectListView.tsx
> PA-1874: Project List View Export Fields

- backend/api/Areas/Property/Mapping/Search/PropertyMap.cs
- backend/api/Areas/Property/Models/Search/PropertyModel.cs
- backend/dal/Configuration/Views/PropertyConfiguration.cs
- backend/entities/EvalutationKeys.cs
- backend/entities/Views/Property.cs
- frontend/src/components/Table/Table.scss
- frontend/src/components/Table/Table.tsx
- frontend/src/constants/evaluationKeys.ts
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingValuationForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ValuationForm.scss
- frontend/src/features/mapSideBar/components/MapSideBarLayout.scss
- frontend/src/features/mapSideBar/components/MapSideBarLayout.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/mapSideBar/containers/__snapshots__/MapSideBarContainer.test.tsx.snap
- frontend/src/features/properties/components/forms/ParcelDetailForm.test.tsx
- frontend/src/features/properties/components/forms/__snapshots__/ParcelDetailForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/BuildingForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/EvaluationForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/PagedBuildingForms.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/columns.tsx
- frontend/src/features/properties/map/MapView.scss
Add new Improvements Evaluation
update backend to support returning most recent improvements during search.
updated styling of table within the parcel/building forms
corrected issue causing the sidebar close animation to display incorrectly.
> Correct Sidebar closing animation and update valuation forms for parcel/building

- backend/core/Helpers/CsvHelper.cs
- backend/tests/unit/dal/Core/Helpers/CsvHelperTest.cs
- backend/tests/unit/dal/Core/Helpers/XmlHelperTest.cs
This update will allow the Excel exports to better handle `null` values and their appropriate data type.
> PA-1867 Modied CsvHelper to generate Excel

- frontend/src/App.scss
- frontend/src/colors.scss
- frontend/src/features/properties/components/GeocoderAutoComplete.scss
Ran changes past Bobbi, she approves
> PA-1905: Update Toast styling to match rest of site

- backend/api/Areas/Project/Mapping/Dispose/ProjectMap.cs
- backend/api/Areas/Project/Models/Dispose/ProjectModel.cs
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/ApprovalTransitionPage.tsx
- frontend/src/features/projects/common/ProjectLayout.scss
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/components/ProjectFinancialTable.tsx
- frontend/src/features/projects/common/forms/UpdateInfoForm.tsx
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/common/tabs/ProjectInformationTab.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
Added Estimated Sales Costs
Added Estimated Program Recovery Fees
> PA-1722 Added fields to Financial Information

- backend/dal/Services/Concrete/ProjectReportService.cs
Fixing existing bug with SPL report
> PA-1875 Removed cancelled projects from SPL report

- frontend/src/features/account/IENotSupportedPage.test.tsx
- frontend/src/features/account/IENotSupportedPage.tsx
- frontend/src/features/account/Login.scss
- frontend/src/features/account/Login.tsx
- frontend/src/features/account/__snapshots__/IENotSupportedPage.test.tsx.snap
- frontend/src/router.tsx
Bobbi and Mikaela approve of the page look
> PA-747: Direct IE user to use Edge, Chrome or Firefox

- backend/api/Areas/Reports/Controllers/ProjectController.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/entities/Models/ProjectFilter.cs
Report was still including cancelled project when exporting to Excel.
> PA-1875 Removed cancelled project form SPL Report

- frontend/src/constants/strings.tsx
- frontend/src/features/mapSideBar/components/MapSideBarLayout.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
fix link to policy on submit property form
> PA-2035,1914: "Rentable Area" -> "Net Rentable Area", fix link 

- backend/tests/unit/dal/Libraries/Ches/ChesServiceCollectionTest.cs
> PA-645 adding ChesServiceCollectionTest

- frontend/src/components/common/form/StepForm/SteppedForm.tsx
- frontend/src/components/common/form/StepForm/context.tsx
- frontend/src/components/common/form/StepForm/types.ts
- frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandUsageForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ValuationForm.scss
- frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
1) rework the css to promote reuse between the review forms.
2) remove vertical line component logic, replace with css.
3) create new associated land review page.
> PA-1701 Review page changes.

- frontend/src/components/common/form/ParentSelect.test.tsx
- frontend/src/components/common/form/__snapshots__/ParentSelect.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/ClassificationForm.test.tsx.snap
- frontend/src/features/properties/components/forms/strings.ts
Getting rid of double field description on classification form and tests for `ClassificationForm.tsx` and `ParentSelect.tsx`
> Some tests and double field description fix

- backend/api/Areas/Property/Controllers/SearchController.cs
Originally wanted to test the ability to quickly add server side caching for some endpoints, but I think it's causing memory issues in the docker container.
> Removing Server Side Cache

- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingValuationForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/OccupancyForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/OccupancyForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingValuationForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/OccupancyForm.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/projects/list/columns.tsx
- frontend/src/features/properties/components/GeocoderAutoComplete.scss
- Unit tests for `BuildingReviewPage`, `OccupancyForm`, and `BuildingValuationForm`
- Renaming of `TenancyForm.tsx` -> `OccupancyForm.tsx`
- Few tiny grammar things
> Unit tests and small tech debt

- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Admin/Concrete/ProjectService.cs
- backend/dal/Services/Admin/Concrete/ProjectStatusService.cs
- backend/tests/core/PrincipalHelper.cs
- backend/tests/core/ServiceHelper.cs
- backend/tests/core/TestHelper.cs
- backend/tests/core/TestHelperExtensions.cs
- backend/tests/unit/api/Controllers/Tools/ImportControllerTest.cs
- backend/tests/unit/api/Routes/Tools/ImportControllerTest.cs
- Code cleanup
- Additional unit-tests
> PA-2141 Imported Projects Assign to Agency

- backend/api/ches.Development.json
- backend/api/ches.Local.json
- backend/api/ches.Test.json
- backend/api/ches.json
Domain names have changed for CHES.
> PA-2190 Updated CHES Domain Name

- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/forms/AppraisalCheckListForm.tsx
- frontend/src/features/projects/common/forms/FirstNationsCheckListForm.tsx
Renamed label and fixed formatting.
> PA-2207 Renamed Appriasal Note Label

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/entities/Models/ProjectFilter.cs
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
Filter the projects by their actual or forecasted fiscal year.
> PA-1873 Added Fiscal Year Filter to Project List

- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/spl/forms/CloseOutPurchaseInformationForm.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
> Added Assessed and Appraised to Close out Form

- backend/api/Areas/Reports/Controllers/ProjectController.cs
- backend/api/Areas/Reports/Controllers/PropertyController.cs
- backend/api/Helpers/Reporting/ReportHelper.cs
- backend/core/Helpers/CsvHelper.cs
- backend/tests/unit/dal/Core/Helpers/CsvHelperTest.cs
- backend/tests/unit/dal/Core/Helpers/XmlHelperTest.cs
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/splReports/hooks/useProjectSnapshotApi.ts
- frontend/src/pages/Test.ignore.tsx
SPL Report sheet name and filename updated.  This improves the ability to import it into the existing Excel file from SRES.
> PA-1933 Updated SPL Report

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- frontend/src/components/maps/FindMorePropertiesButton.tsx
- frontend/src/features/properties/filter/PropertyFilter.scss
- update LINQ query to ensure no buildings 
- take out small screen variation as it is broken and unnecessary
> Filterbar revamp hotfix

- backend/api/Areas/Property/Controllers/SearchController.cs
- backend/entities/Models/AllPropertyFilter.cs
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/mapUtils.tsx
Critical bugfix ensures that the map boundary is actually used when passed to the API.
> Correct map not using bounds to filter api response.

- frontend/src/actions/parcelsActions.ts
- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/components/common/form/StepForm/context.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ParcelIdentificationForm.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/mapSideBar/hooks/useQueryParamSideBar.tsx
- frontend/src/features/properties/components/GeocoderAutoComplete.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/hooks/useDraftMarkerSynchronizer.tsx
- frontend/src/features/properties/hooks/useParcelLayerData.tsx
- frontend/src/features/properties/map/MapView.tsx
- frontend/src/reducers/parcelsReducer.ts
- frontend/src/utils/YupSchema.ts
> PA-2303, PA-2304, PA-2305, PA-2307, PA-2306, PA-2308

- frontend/src/features/properties/components/forms/subforms/BuildingForm.test.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- Updated "Sq ft" to "Sq M"
- updated tenancy fields to match alpha-dev
> PA-1923,2229 Tenancy updates, sq m (dev)

- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/IdentificationForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandUsageForm.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/OccupancyForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/OccupancyForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/OccupancyForm.test.tsx.snap
- frontend/src/features/mapSideBar/components/MapSideBarLayout.scss
- frontend/src/features/properties/components/forms/subforms/LatLongForm.tsx
- Removed requested fields from tenancy/occupancy forms (it was requested that Tenancy % have an "updated date" field, I created a new story for this)
- Fixed spacing for some of the inputs (PA-2264)
- Updated required field styling
- Changed "Sq ft" to "Sq M" (PA-2229)
> PA-1923 Update Tenancy/Occupancy pages

- frontend/src/components/maps/ParcelPopupView.test.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
Now gets project route and changes link on project number accordingly
> Fix broken SPP link on popup

- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/OccupancyForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/OccupancyForm.test.tsx.snap
> PA-2340 Change "Net Rentable Area" to "Net Usable Area"

- frontend/src/colors.scss
- frontend/src/features/properties/filter/PropertyFilter.scss
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/list/PropertyListView.scss
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/properties/map/MapView.tsx
- fixed filter resizing for smaller screens so that search fields now wrap and aren't cut off at the bottom of the filter bar, made sure map view and property list view matched
https://user-images.githubusercontent.com/33818575/103322151-e56cf080-49f1-11eb-8844-cba38853d14a.mp4
> PA-2297 Filter Bar Sizing

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/features/properties/filter/PropertyFilter.scss
- Add padding above titles
- Vertical line spacers should be lighter grey
- Search bar should be disabled when Find More Properties window open has been moved to another story
> PA-2327 Update "Find Available Properties" button styling

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
Same as the other pull request, this one just adds the changes in dev rather than alpha
> PA-2340 Change "Net Rentable Area" to "Net Usable Area" (dev)

- COMPLIANCE.yaml
- backend/api/Areas/Reports/Mapping/Property/PropertyMap.cs
- backend/api/Areas/Reports/Models/Property/PropertyModel.cs
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/properties/list/columns.tsx
- frontend/src/features/properties/list/interfaces.ts
> PA-1954 Added Name to Property List View

- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Services/Concrete/ProjectService.cs
- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/features/projects/common/components/FormikTable.tsx
- frontend/src/features/projects/common/components/columns.tsx
- frontend/src/features/projects/erp/forms/AgencyInterest.tsx
- frontend/src/features/projects/erp/forms/AgencyInterestColumns.tsx
- frontend/src/features/projects/erp/forms/AgencyResponseForm.tsx
- frontend/src/features/projects/erp/steps/ErpStep.tsx
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/tabs/EnhancedReferralTab.test.tsx
- frontend/src/features/projects/erp/tabs/__snapshots__/EnhancedReferralTab.test.tsx.snap
User can now select specific agencies and add their responses to projects within ERP.
> PA-2255 Enhanced Referral Process Agency Responses

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
Someone, somehow submitted a formatting issue :P
> fix format

- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/dispose/ProjectDisposalExemptionSubmitted.tsx
- frontend/src/features/projects/dispose/ProjectDisposeLayout.tsx
- frontend/src/features/projects/dispose/index.ts
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
- frontend/src/router.tsx
Submitting a Disposal Project with an Exemption will now have it's own relevant summary page.
> PA-1951 Submit Disposal Project Exemption Page

- frontend/src/components/SearchBar/ParentGroupedFilter.tsx
- frontend/src/components/Table/ColumnFilter.tsx
- frontend/src/components/Table/Table.scss
- frontend/src/components/Table/Table.tsx
- frontend/src/components/Table/types.ts
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/features/admin/agencies/__snapshots__/ManageAgencies.test.tsx.snap
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/dispose/forms/PropertyListViewSelect.test.tsx
- frontend/src/features/projects/dispose/forms/__snapshots__/PropertyListViewSelect.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
- frontend/src/features/projects/erp/tabs/__snapshots__/EnhancedReferralTab.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/filter/IPropertyFilter.ts
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/list/PropertyListView.scss
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/properties/list/columns.tsx
- frontend/src/hooks/useRouterFilter.ts
Implementing table column filter. The table is configurable using column settings. The table header is wrapped with formik and render the filterable columns as a form.
> Implementing properties column filter

- frontend/src/features/mapSideBar/SidebarContents/SubmitPropertySelector.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/SubmitPropertySelector.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/SubmitPropertySelector.test.tsx.snap
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/mapSideBar/hooks/useQueryParamSideBar.tsx
- frontend/src/features/mapSideBar/hooks/useSideBarParcelLoader.tsx
Thought I'd fix up the variable names too just to avoid confusion later on
> pa-2408 Change Raw Land to Bare land

- frontend/src/features/mapSideBar/components/MapSideBarLayout.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
> PA-2359 Clarify edit button.

- README.md
> PA-2379 Add project Lifecycle badge

- frontend/src/buttons.scss
- frontend/src/components/SearchBar/__snapshots__/FilterBar.test.tsx.snap
- frontend/src/components/common/form/ParentSelect.scss
- frontend/src/components/common/form/ResetButton.tsx
- frontend/src/components/maps/FindMorePropertiesButton.tsx
- frontend/src/features/admin/agencies/__snapshots__/ManageAgencies.test.tsx.snap
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/properties/filter/PropertyFilter.scss
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/PropertyFilterOptions.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/list/PropertyListView.scss
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Made sure the map view and property list view matched
> PA-2351 Fix up filterbar styling

- frontend/src/components/common/form/FastSelect.tsx
> Fix fast select not updating formik touch parameters.

- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
This PR includes:
- formatting of the fiscal year for financial values in building/land review sections
- removal of validation checkmark on location field (in the review section for building/land)
> PA-2353, 2354

- openshift/4.0/README.md
- openshift/4.0/templates/persistent-volume-claims/pims-db-storage.yaml
OCP4.0 persistent volume claim storage configuration.
> PA-2384 DEV Storage setup

- frontend/src/features/properties/filter/PropertyFilterOptions.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Got removed in revamp by accident
> Hotfix for PID search

- openshift/4.0/README.md
- openshift/4.0/templates/api/build.yaml
- openshift/4.0/templates/api/deploy-swagger.yaml
- openshift/4.0/templates/api/deploy.yaml
- openshift/4.0/templates/database/mssql-build.yaml
- openshift/4.0/templates/database/mssql-deploy.yaml
- openshift/4.0/templates/logging/deploy-elasticsearch.yaml
- openshift/4.0/templates/logging/deploy-kibana.yaml
- openshift/4.0/templates/network-security-policy/nsp.yaml
API is now running in OCP4.0.
Still unable to get Kibana to work to look at the logs.
> PA-2381 OCP4.0 Setup DEV API

- frontend/src/components/common/form/StepForm/SteppedForm.tsx
- frontend/src/components/layout/AppNavBar/AppNavBar.tsx
- frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/components/MapSideBarLayout.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/mapSideBar/hooks/useQueryParamSideBar.tsx
Re-add functionality to warn when user navigates away with unsaved changes.
> PA-2302 handle case when all associated lands are removed.

- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/api/Areas/Tools/Mapping/Import/PropertyMap.cs
- backend/api/appsettings.Local.json
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/ParcelService.cs
- backend/dal/Services/Admin/IBuildingService.cs
- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/PopupView.tsx
- frontend/src/components/maps/__snapshots__/BuildingPopupView.test.tsx.snap
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/hooks/useApi.ts
- tools/converters/excel/appsettings.json
Update API to have an endpoint that will delete properties from inventory.
Fixed property popup information.  Now when viewing a property on the map it will initially display the data it has and make a separate AJAX request to fetch the rest of the data.
> PA-2460 Adding config for delete properties

- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/dal/Services/Admin/Concrete/BuildingService.cs
- backend/dal/Services/Admin/Concrete/ParcelService.cs
- backend/dal/Services/Admin/IBuildingService.cs
- tools/converters/excel/appsettings.json
My updates to handle deleting properties resulted in breaking importing.  This should resolve this issue.
> PA-2460 Resolving importing issue

- frontend/src/components/common/form/Typeahead.tsx
Adjust filter bar to alpha changes
> Filterbar fix

- backend/api/Areas/Property/Mapping/Parcel/ParcelFiscalMap.cs
- backend/dal/Services/Concrete/ParcelService.cs
Updating financial values in properties with buildings would fail if a second attempt was made.
> Fixing updating properties

- backend/dal/Migrations/v01.05.05/Up/PostUp/01-BuildingPredominantUses.sql
After reviewing a rollback and update discovered issue with removing Zebra Feeding Station.  This will resolve it.
> Fixed DB Migration

- frontend/src/components/common/form/Typeahead.tsx
Changing back to prior implementation, will be changed after Devin's changes get in but fixing it for the next release to production
> Filter fix

- frontend/src/components/maps/FindMorePropertiesButton.tsx
- frontend/src/features/properties/filter/PropertyFilter.test.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/PropertyFilterOptions.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
https://user-images.githubusercontent.com/33818575/104638096-92827280-565a-11eb-812a-3175eaee7496.mp4
> PA-2356 Disable search bar when Surplus Properties window open

- frontend/src/features/properties/list/PropertyListView.tsx
Closing other PR for this and using this one, other branch is too messed up so this was easier! 
- default to land when loading inventory list view
> Default to land in inventory list

- frontend/src/features/properties/components/forms/subforms/BuildingForm.tsx
- frontend/src/features/properties/components/forms/subforms/EvaluationForm.tsx
- frontend/src/features/properties/components/forms/subforms/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/columns.tsx
> Quick fix for Building Assessed value table

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
> PA-2481 Surplus Properties search - UX Updates

- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useRouterFilter.ts
- Zoom to municipality using data from municipality layer
- Reapply filter in list view from map view, query municipality layer and zoom to result
> Reapply filter in list view from map view, query municipality layer and zoom to result

- frontend/src/components/maps/BuildingPopupView.tsx
- frontend/src/components/maps/ParcelPopupView.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/constants/strings.tsx
I also increased the zoom level
> PA-1728 Zoom into property on Edit/View

- frontend/src/features/projects/erp/steps/ErpStep.test.tsx
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/spl/steps/SplStep.test.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
- frontend/src/features/projects/spl/tabs/CloseOutFormTab.tsx
Mikaela requested that the Financing Information section be removed as well
> PA-1969 Reconfigure Project Notes

- frontend/src/components/maps/leaflet/Legend/LegendControl.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/ZoomOut/ZoomOutButton.tsx
https://user-images.githubusercontent.com/33818575/105398379-27dfb280-5bd7-11eb-8af1-f63de71fd3fe.mp4
Also added a tool tip for the marker legend
> PA-2502 View Entire Province

- .github/CODEOWNERS
> Updating Code Owners

- openshift/4.0/README.md
- openshift/4.0/templates/logging/deploy-elasticsearch.yaml
- openshift/4.0/templates/logging/deploy-kibana.yaml
We now have Kibana and Elasticsearch running.  
- https://pims-kibana.apps.silver.devops.gov.bc.ca/app/kibana
Note - that the storage should be updated to a backup type, although it isn't critical.  Additionally a Kibana dashboard hasn't been configured.
> PA-2396, PA-2398 Setup Kibana + Elasticsearch

- frontend/src/actions/parcelsActions.ts
- frontend/src/components/maps/leaflet/InfoSlideOut/BuildingAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.scss
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelPIDPIN.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
- frontend/src/components/maps/leaflet/LayersControl/LayersControl.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/components/maps/providers/PropertyPopUpProvider.tsx
- frontend/src/mocks/filterDataMock.ts
https://user-images.githubusercontent.com/33818575/105923191-d8dbb800-5ff0-11eb-9900-eededfdf1571.mp4
https://user-images.githubusercontent.com/33818575/105924540-4f79b500-5ff3-11eb-9dda-e4b23ab2ec2c.mp4
I'm sure there's a few things here that could be improved, please let me know!
https://user-images.githubusercontent.com/33818575/106067729-22410b80-60b4-11eb-9730-d3b85a8fc1ae.mp4
Now can view slide out from property list view
> PA-2479 Slide out for owning agency, view land

- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/IdentificationForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandUsageForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/ClassificationForm.test.tsx.snap
- frontend/src/features/properties/components/forms/strings.ts
Conditional text that is rendered when Surplus Active or Surplus Encumbered is entered on the `ClassificationForm.tsx`
> Text for Surplus Active/Surplus Encumbered on Classification Form

- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
- frontend/src/features/properties/components/forms/strings.ts
Add missing description text from inventory policy when Surplus Active is selected in the `ClassificationForm.tsx`
> Add text for Surplus Active desc

- frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/IdentificationForm.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandUsageForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ParcelIdentificationForm.scss
- frontend/src/utils/YupSchema.ts
PA-2566 Make Harmful if Released more obvious
PA-2579 Net Usable area greater than total area.
> PA-2558 Remove empty tooltip

- backend/core/Http/OpenIdConnectRequestClient.cs
- backend/core/Pims.Core.csproj
- tools/core/Pims.Tools.Core.csproj
- tools/keycloak/sync/Pims.Tools.Keycloak.Sync.csproj
- tools/keycloak/sync/Program.cs
- tools/keycloak/sync/Properties/launchSettings.json
- tools/keycloak/sync/SyncFactory.cs
- tools/keycloak/sync/realm.development.json
- tools/keycloak/sync/realm.test.json
Updated configuration to support new environment.
Updated tool to handle when there are more than 50 users to sync.
> PA-1742 Fixed Keycloak Sync Tool

- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
- backend/tests/unit/api/Controllers/Tools/ImportControllerTest.cs
Importing SRES Disposal Projects will only apply the `MarketedOn` date if the project is in an appropriate status.
> PA-2181 Fixed Project Import

- backend/dal/Services/Concrete/BuildingService.cs
- frontend/src/components/maps/leaflet/InfoSlideOut/BuildingAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.scss
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelPIDPIN.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ThreeColumnItem.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- Still needs a fix, associated land/buildings are not being pulled properly and not populating
> PA-2662 Fix up slide out styling

- backend/dal/Configuration/ProjectNoteConfiguration.cs
- backend/dal/Helpers/Extensions/ProjectExtensions.cs
- backend/dal/Migrations/20210128205552_v01.06.05.Designer.cs
- backend/dal/Migrations/20210128205552_v01.06.05.cs
- backend/dal/Migrations/20210128205552_v01.07.00.Designer.cs
- backend/dal/Migrations/20210128205552_v01.07.00.cs
- backend/dal/Services/Concrete/ProjectService.cs
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/columns.tsx
- frontend/src/features/projects/list/interfaces.ts
Can now delete properties from the Project List View
> Delete project functionality

- frontend/src/constants/propertySteps.ts
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/columns.tsx
> PA-2616 Move Associated Land/Building to review page

- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingValuationForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/columns.tsx
Picking some low hanging fruit... 
- tooltip added for assessment values
> PA-2658: Tooltip for assessment values

- frontend/src/features/splReports/components/SplReportLayout.scss
- frontend/src/features/splReports/components/SplReportLayout.tsx
https://user-images.githubusercontent.com/33818575/107098430-0cbe9680-67c4-11eb-9eb6-b94088bc8d4a.mp4
> PA 2703 SPL Report Sidebar arrow icon fix

- frontend/src/components/maps/leaflet/InfoSlideOut/BuildingAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelAttributes.tsx
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- Also added the changes from @devinleighsmith PR
> Pa 2480, 2641, 2672 Slide out: Land - non-owning agency, Building - both

- openshift/4.0/templates/api/README.md
- openshift/4.0/templates/api/deploy.yaml
Modified Deployment Configuration file to follow latest standards.
Network Security Policy now included.
> PA-2389 Updated API DevOps Config

- openshift/4.0/templates/app/build.yaml
- openshift/4.0/templates/app/deploy.yaml
Applying some standard conventions to existing config templates.
> PA-2390 Updated APP DevOps Config

- backend/dal/Helpers/Constants/ClassificationTypes.cs
- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- backend/dal/Migrations/Initial/Up/PostUp/01-PropertyClassifications.sql
- backend/dal/Services/Concrete/BuildingService.cs
- backend/dal/Services/Concrete/ParcelService.cs
- frontend/src/constants/classifications.ts
- frontend/src/features/mapSideBar/SidebarContents/subforms/ClassificationForm.tsx
- frontend/src/features/properties/components/forms/strings.ts
- frontend/src/features/properties/filter/PropertyFilter.tsx
Add demolished and subdivided classifications.
- only buildings can select classification of demolished 
- only SRES can select demolished and subdivided 
- demolished and subdivided not displayed on map or list view
- only SRES can filter Demolished/Subdivided
> PA-2700, 2341: Demolished/ Subdivided

- backend/dal/Migrations/v01.06.00/Down/PreDown/RemoveRolesAndClaims.sql
The rollback script needed to be updated so that it would work.
> Fixed v01.06.00 Migration Rollback

- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
- backend/api/Areas/Tools/Models/Import/ImportProjectModel.cs
- backend/entities/Models/DisposalProjectMetadata.cs
- tools/converters/excel/Converter.cs
- tools/converters/excel/Converters/StringConverters.cs
- tools/converters/excel/appsettings.json
Updating Converter tool to include `ExemptionRequested` and **Exemption from ERP** status.
> PA-1898 Updated Project Import

- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/components/ProjectNotes.tsx
- frontend/src/features/projects/common/forms/AppraisalCheckListForm.tsx
> Add text below Appraisal Notes title

- backend/dal/Services/Concrete/ProjectReportService.cs
SPL Report shouldn't include projects that are transferred by GRE.  This issue was introduced when we enabled SPL projects to be transferred by GRE.
> PA-1910 Fixed SPL Report

- backend/dal/Migrations/v01.07.01/Up/PostUp/01-Agencies.sql
Disabled school districts that are no longer in use.
> PA-2742 Disabled some schools

- frontend/src/components/maps/leaflet/Legend/Legend.scss
- frontend/src/components/maps/leaflet/Legend/LegendControl.scss
- frontend/src/features/projects/assess/steps/ReviewApproveStep.test.tsx
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/ApprovalConfirmationForm.tsx
- frontend/src/features/projects/dispose/ProjectDisposeLayout.test.tsx
- frontend/src/features/projects/dispose/components/ApprovalConfirmation.test.tsx
- frontend/src/features/projects/dispose/components/__snapshots__/ApprovalConfirmation.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- Fixed the wording as per Mikaela's request
- Also noticed the marker legend was looking squished on my lower resolution screen so fixed it up so the marker icons were easier to see
Before:
After:
> PA 2571 I, User, have approval

- frontend/src/components/layout/AppNavBar/AppNavBar.tsx
Users can now use Disposal Projects.
> Display Disposal Projects

- frontend/src/features/projects/common/components/PropertyListViewSelect.tsx
- frontend/src/features/projects/common/forms/GreTransferForm.tsx
Fixing infinite loop after selecting an agency to transfer to within GRE.
> Fixed Transfer with GRE agency

- backend/dal/Configuration/NotificationQueueConfiguration.cs
- backend/dal/Migrations/20210217204245_v01.08.00.Designer.cs
- backend/dal/Migrations/20210217204245_v01.08.00.cs
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/columns.tsx
Fix error on delete from notifications not cascading on delete, as well as ensure the trash icon does not appear if the user does not have permission to do so.
They have permission if:
- it is still a draft and they are the one who made it
- they have project edit claim and it is in draft mode
- they are SRES
> Notification cascade on delete

- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/interfaces.ts
Surplus Filter now working as expected on list view
> ERP/SPL Filter in list ivew bug fix

- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/ValuationForm.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingValuationForm.test.tsx.snap
- frontend/src/features/properties/components/forms/subforms/EvaluationForm.tsx
- Also swapped the tables as per the ticket
> PA 2767 Add text to building valuation

- frontend/src/features/projects/erp/forms/AgencyResponseForm.tsx
- frontend/src/features/projects/erp/steps/ErpStep.test.tsx
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/tabs/__snapshots__/EnhancedReferralTab.test.tsx.snap
Examples on different screens:
> PA 2761 Add read only copy of ERP email note

- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/components/maps/leaflet/SelectedPropertyMarker/SelectedPropertyMarker.tsx
- frontend/src/components/maps/leaflet/mapUtils.tsx
- Now highlights selected pin in a cluster, and any pin on click rather than just when the detail view is open
https://user-images.githubusercontent.com/33818575/108274048-3d3df300-7129-11eb-973e-e3bfb7d48810.mp4
> PA 2459 highlight active pin

- frontend/src/components/Table/ViewPropertyCell.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
Breaking this off from my other stories as I am trying to iron a few things out
> PIMS-2776: New tab view inventory page

- frontend/src/components/maps/leaflet/InfoSlideOut/AssociatedBuildingsList.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/AssociatedParcelsList.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/AssociatedTab.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/BuildingAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/HeaderActions.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.scss
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoSlideOut.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/AssociatedTab.test.tsx.snap
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/HeaderActions.test.tsx.snap
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoContent.test.tsx.snap
https://user-images.githubusercontent.com/33818575/108557198-11e41100-72ad-11eb-84bd-cb7b22fe7294.mp4
- Also added a bunch of tests
> PA 2782 Tab for associated land on a building

- tools/converters/excel/appsettings.json
Updated configuration in Converter Tool to support the additional project status values in latest export.
> PA-2807 Updated Converter Tool Config

- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/AssociatedTab.test.tsx.snap
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/HeaderActions.test.tsx.snap
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoContent.test.tsx.snap
- frontend/src/hooks/useLookupCodes.tsx
This was the first thing that came to mind for me, if there's a better way to do it let me know (I still have trouble figuring out endpoints...)
> PA 2797 Show full agency name in slide out

- frontend/src/App.scss
- Just added the blue highlight so the parent values would look clickable like the other values
https://user-images.githubusercontent.com/33818575/109082233-6675fa80-76b8-11eb-9e2a-77456f92e0ad.mp4
> Add shade behind values in ParentSelect

- frontend/src/components/SearchBar/FindMorePropertiesForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/SubmitPropertySelector.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/SubmitPropertySelector.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/SubmitPropertySelector.test.tsx.snap
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
replacing "bare land" with "land"
> PA-2830: Change "Submit Bare Land" to "Submit Land"

- openshift/4.0/templates/api/deploy-alt-routes.yaml
- openshift/4.0/templates/api/deploy-routes.yaml
- openshift/4.0/templates/app/deploy-alt-routes.yaml
- openshift/4.0/templates/app/deploy-routes.yaml
Added separate route deployment configuration files for the API and APP.  These are not required, as they already exist in the current deployment configuration files.  They make it easier to remove/replace/update the routes independent of all the other objects.
> Added separate deploy configs

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
This query will be more efficient and should correctly return properties in ERP and/or SPL.
Jonny, please test once merged to determine if it handles all scenarios.
> Updated SPL/ERP Query

- openshift/4.0/templates/jenkins/README.md
- openshift/4.0/templates/jenkins/rolebinding.yaml
The rolebinding configuration was missing.  I have added it but am uncertain if it is correct.
> Added Jenkins RoleBinding Config

- maintenance/RESTORE_BACKUPS.md
- openshift/4.0/templates/sonarqube/README.md
- openshift/4.0/templates/sonarqube/sonarqube-postgresql-template.yaml
Note that a lot of this is dependent on @goemen PR, status, thus the DRAFT PR. Will need to make updates to his CICD pipeline to re enable sonarqube.
> Doc for PA-2401,2400,2406

- frontend/src/features/projects/assess/steps/ReviewApproveStep.tsx
- frontend/src/features/projects/dispose/forms/disposalYupSchema.ts
> PA-2879 Fixed Deny Project Validation

- frontend/src/features/projects/erp/components/ExemptionDetails.tsx
- frontend/src/features/projects/erp/forms/ExemptionEnhancedReferralCompleteForm.test.tsx
- frontend/src/features/projects/erp/forms/__snapshots__/ExemptionEnhancedReferralCompleteForm.test.tsx.snap
> PA-2874 Allow Editing Exemption Rationale

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
Updated filter to not include properties that are part of completed projects (cancelled, denied, disposed, transferred with GRE).
> Fixed SPP Filter

- frontend/src/features/help/components/text/DetailNavigationHelpText.tsx
- frontend/src/features/help/components/text/DetailViewHelpText.tsx
- frontend/src/features/help/components/text/InventoryFilterHelpText.tsx
- frontend/src/features/help/components/text/InventoryListHelpText.tsx
- frontend/src/features/help/components/text/InventoryNavigationHelpText.tsx
- frontend/src/features/help/components/text/LandingMapHelpText.tsx
- frontend/src/features/help/components/text/LandingNavigationHelpText.tsx
> PA 2883 Update wording on Help feature

- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ParcelAttributes.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/ThreeColumnItem.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/AssociatedTab.test.tsx.snap
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/HeaderActions.test.tsx.snap
- frontend/src/components/maps/leaflet/InfoSlideOut/__snapshots__/InfoContent.test.tsx.snap
- frontend/src/components/maps/leaflet/LayerPopup/LayerPopupContent.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/properties/list/columns.tsx
Add PID to inventory list view, and also disable animation on another zoom button as well
Also add assessed building(s) to property slideout
> Add PID to table, add assessed building(s) to property slideout

- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
Was opening on same page previously
> Open associated building in new tab

- backend/api/Areas/Tools/Helpers/ImportProjectsHelper.cs
- backend/api/Areas/Tools/Models/Import/ImportProjectModel.cs
- tools/converters/excel/appsettings.json
When importing projects from SIS data it will copy the `Location` information into the `Description`.
> PA-2829 Import Project Location

- frontend/src/components/Table/Table.scss
- frontend/src/components/Table/Table.tsx
- frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
- frontend/src/components/maps/leaflet/LayersControl/data.ts
- frontend/src/features/projects/common/interfaces.ts
- frontend/src/features/splReports/columns.tsx
- frontend/src/features/splReports/components/ReportForm.tsx
- frontend/src/features/splReports/containers/SplReportContainer.test.tsx
- frontend/src/features/splReports/containers/SplReportContainer.tsx
- frontend/src/features/splReports/hooks/useProjectSnapshotApi.ts
- frontend/src/features/splReports/interfaces.ts
> Add filtering to SPL reports

- openshift/4.0/templates/app/README.md
- openshift/4.0/templates/app/deploy-alt-routes.yaml
- openshift/4.0/templates/app/deploy-routes.yaml
- openshift/4.0/templates/app/deploy.yaml
Removed route from app DC to prevent future updates to the DC from removing route SSL certificates.
> SSL Route Config

- frontend/src/components/maps/leaflet/FilterBackdrop/index.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/properties/map/MapView.scss
https://user-images.githubusercontent.com/4842061/109880807-3d131c80-7c2c-11eb-952b-2cf0323b4adf.mp4
> Blur Page until Map Requests Complete

- backend/api/Helpers/Exceptions/AuthenticationException.cs
- backend/api/Helpers/Middleware/ErrorHandlingMiddleware.cs
- backend/api/Startup.cs
When authentication fails due to an invalid JWT or communication with Keycloak this will now be easier to debug.
> Added JWT Error Handling

- .vscode/launch.json
- tools/keycloak/sync/Models/UserModel.cs
- tools/keycloak/sync/SyncFactory.cs
Resolve issue when Keycloak had duplicate agencies attached to users.
Also added way to run and debug Keycloak Sync Tool within VSCode.
> PA-2903 Fixed Keycloak Sync

- frontend/src/features/projects/common/components/FilterBar.tsx
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
Adding the ability to filter by location to the select properties step of disposal projects
> Add location to Select Properties filter

- backend/dal/Migrations/v01.09.03/Up/PostUp/01-NotificationTemplates.sql
Updating DB Migration `v01.09.03` notification template addressed to "Good morning / Good afternoon".
> PA-2885 Updated Notification AddressTo

- backend/dal/Migrations/v01.08.01/Up/Postup/01-NotificationTemplates.sql
Fixed the first notification sent when submitting a project.  This will require you to do a rollback/update to your DB to resolve.
> Fixed NotificationTemplate

- backend/dal/Migrations/v01.08.01/Up/Postup/01-Buildings.sql
- backend/dal/Migrations/v01.08.01/Up/Postup/01-Parcels.sql
Resolving issue with production data issues in the DB migration when deleting UBC properties.
> Fixed UBC DB Migration Script

- .vscode/launch.json
- openshift/4.0/templates/api/README.md
- openshift/4.0/templates/api/deploy-routes.yaml
- openshift/4.0/templates/api/deploy.yaml
Removed the routes from the standard API deployment configuration to eliminate issue when deploying to production.  Making it a separate step to ensure the SSL certificate information is correctly added.
> Updated API Routes Deployment Config

- backend/dal/Migrations/v01.08.01/Up/Postup/01-NotificationTemplates.sql
- backend/dal/Migrations/v01.09.06/Up/PostUp/01-NotificationTemplates.sql
Error in order of operation...
> Fixed Notfiication Template

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/router.tsx
Splitting off some small work into separate PRs 
- change tab name for SPL reports 
- make sure inERP and inSPL reset in URL in relation to the filter
> PA-2437, 2865: Default values and reports tab

- frontend/src/components/common/form/ParentSelect.tsx
Open to feedback here
I assigned a `parentId` of `-1` to parent agencies that have no children. This helps the component group them together and ensure they are in the list. 
Is there a better value than -1 I could use for the id? 
These childless parent agencies show as bold like the other parents in the list.
> Add missing childless agencies to agency list

- openshift/4.0/pipelines/Jenkinsfile.cicd
Thanks to @WadeBarnes for pointing this deficiency out
> use secrets instead of strings for cicd tokens.

- frontend/src/components/layout/Header/Header.tsx
- frontend/src/components/layout/Header/__snapshots__/Header.test.tsx.snap
- frontend/src/components/maps/leaflet/LayersControl/data.ts
- frontend/src/utils/YupSchema.ts
Now that these values are initialized to false we need to check if one of them is true now instead of the default required check.
> Validation bug

- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
- frontend/src/constants/toasts.ts
- frontend/src/features/mapSideBar/SidebarContents/AssociatedLandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.test.tsx
- frontend/src/features/projects/erp/forms/ExemptionEnhancedReferralCompleteForm.test.tsx
- frontend/src/features/projects/erp/forms/ExemptionEnhancedReferralCompleteForm.tsx
- frontend/src/features/properties/hooks/useParcelLayerData.tsx
fix associated land agency defaults
re-add some disabled tests.
reduce duplicated toast messages.
> PA-3005 editing parcels/buildings defaults to last page.

- frontend/.prettierignore
- frontend/src/components/Table/ColumnFilter.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.test.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/columns.tsx
Allowing  Press ENTER to submit filter when a typeahead component is used in the filter
> PA-2835 fix table column filter

- backend/api/Areas/Reports/Mapping/Project/SurplusPropertyListMap.cs
- backend/dal/Services/Concrete/ProjectService.cs
Exporting the SPL Report to Excel has been updated to use the existing status names rather than the original report status names.
> PA-3008 SPL Report Status Updated

- openshift/4.0/templates/network-security-policy/ingress-permissive.yaml
Capturing the basic most permissive network policy provided by the Lab.
> Added Permissive NetworkPolicy

- frontend/src/features/mapSideBar/SidebarContents/subforms/OccupancyForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/TenancyForm.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/OccupancyForm.test.tsx.snap
Tooltip for tenancy percentage as well as making field a little longer as Bobbi requested
> Tenancy % tooltip

- .github/CODEOWNERS
> adding Bruce and Sharala to code owners

- backend/ches/ChesService.cs
- backend/core/Http/HttpRequestClient.cs
- backend/tests/unit/dal/Libraries/Ches/ChesServiceCollectionTest.cs
Issues have been discovered while testing in DEV.  There appears to be some kind of communication problem with CHES.
Added additional logging for errors that occur during HTTP requests and deserialization.
> Add request logging

- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
- frontend/src/features/projects/spl/steps/__snapshots__/SplStep.test.tsx.snap
An out of place bracket was breaking the logic
> Fix Remove from SPL fields not appearing

- frontend/src/features/projects/spl/forms/SurplusPropertyListForm.tsx
Add logic to show desired fields for requested status
> PIMS-31: Show additional fields for Not in SPL

- Makefile
- openshift/4.0/templates/jenkins/generic-pipeline.yaml
Using the `make db-script from={value} to={value}` command will generate the SQL.
> Add db-script command

- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/common/strings.ts
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
Removing net from tier tool tips
> PIMS-32: Change Description for the Tier's

- backend/api/Areas/Reports/Controllers/ProjectController.cs
- backend/api/Areas/Reports/Mapping/Project/ProjectMap.cs
- backend/api/Areas/Reports/Models/Project/ProjectModelExcel.cs
Created a new model to hold a formatted fiscal year as a string instead of a number.
> PIMS-37 new model for project export to excel

- backend/api/Controllers/UserController.cs
- backend/dal/Services/Concrete/NotificationQueueService.cs
- backend/dal/Services/INotificationQueueService.cs
Added an overloaded method for GenerateNotification.
> PIMS-44: Change to PIMS Access Request Email

- backend/api/Areas/Reports/Mapping/Property/AllFieldsPropertyMap.cs
- backend/api/Areas/Reports/Mapping/Property/PropertyMap.cs
- backend/core/Extensions/StringExtensions.cs
Changes to the property map and adding format extension to AllFieldsPropertyMap.
For the export to CSV, if a project contains multiple project numbers you need to "wrap text" on the project number column.
> PIMS-28: How Project Numbers display

- backend/dal/Services/Concrete/NotificationQueueService.cs
This will resolve the issue we're seeing with notifications.  Note that this was caused by the upgrade to .NET 5.0
> Fix project notifications issue

- frontend/src/components/common/form/Check.tsx
- frontend/src/features/projects/assess/forms/ReviewApproveForm.tsx
- frontend/src/features/projects/common/components/NotificationCheck.tsx
Fix that saves the state of the checkbox on save while approving
> PIMS-49: Save notification checked state on save

- frontend/src/constants/strings.tsx
updating email address to RPD email address
> PIMS-59: Change contact email

- openshift/4.0/pipelines/Jenkinsfile.cicd
- openshift/4.0/templates/app/deploy.yaml
This should resolve the DevOps issue caused by a miss-spelled word.
> Fix app deployment config

- openshift/4.0/templates/sonarqube/deploy.yaml
I've update the image, but the deployment appears to be really slow.  Not sure if it's working atm.
> Fix Sonarqube log4j security issue

- frontend/src/components/maps/hooks/useActiveFeatureLayer.test.tsx
- frontend/src/components/maps/leaflet/LayerPopup/hooks/useBoundaryLayer.tsx
- frontend/src/components/maps/leaflet/LayerPopup/hooks/useLayerQuery.tsx
- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.test.tsx
Had to add back the red toast error for the error handling as that was breaking too many frontend tests. 
Maybe we can deal with it in a future PR?
> Pims 24 - using both public and private layers for parcels

- openshift/4.0/pipelines/Jenkinsfile.cicd
Trying to get the master pipeline to work again.  It keeps timing out.
> Increase build timeout

- frontend/src/constants/reducerTypes.ts
- frontend/src/features/projects/common/index.ts
- frontend/src/features/projects/common/tabs/NotificationList.tsx
- frontend/src/features/projects/common/tabs/NotificationTab.tsx
- frontend/src/features/projects/common/tabs/columns.tsx
- frontend/src/features/projects/constants/SPPApprovalTabs.ts
- frontend/src/features/projects/dispose/testUtils.ts
- frontend/src/features/projects/erp/steps/ErpStep.test.tsx
- frontend/src/features/projects/erp/steps/__snapshots__/ErpStep.test.tsx.snap
- frontend/src/features/projects/erp/tabs/ErpTabs.tsx
- frontend/src/features/projects/interfaces/INotification.ts
- frontend/src/features/projects/interfaces/INotificationFilter.ts
- frontend/src/features/projects/interfaces/index.ts
- frontend/src/hooks/useApiDisposal.ts
The Notifications tab in disposal projects will display the statuses of notifications in the queue for a specific project.
Note, that this will check the CHES api and update the status as you "page" through the list.
> PIMS-56: UI to present email errors on the project

- frontend/src/features/properties/list/columns.tsx
adding tool tips to building list view on Inventory page
> PIMS-80: Property list building view financials not saving

- frontend/src/features/projects/common/projectConverter.ts
> Fix disposal project property assessment

- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/toApiProperty.ts
Resolve issues with Property Inventory List View.
- Was not adding or editing the current assessed value year
- Was not display correct values after editing and/or cancelling
> PIMS-89 Fix property inventory list

- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
- frontend/src/features/properties/list/columns.tsx
Just removing the market value column from the view inventory pages, Maggie doesn't need this on the inventory side of the application: https://apps.itsm.gov.bc.ca/jira/browse/PIMS-80
> PIMS-80: Removing the market value column and all market value references

- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/__snapshots__/ProjectSummaryView.test.tsx.snap
- frontend/src/features/projects/common/components/columns.tsx
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/dispose/forms/__snapshots__/PropertyListViewSelect.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/erp/steps/__snapshots__/GreTransferStep.test.tsx.snap
The unused market value column should no longer show:
> PIMS-80: Removing market value column from projects

- .github/CODEOWNERS
- .vscode/launch.json
- backend/.vscode/launch.json
- backend/api/Areas/Reports/Mapping/Property/PropertyMap.cs
- backend/api/Areas/Reports/Models/Property/PropertyModel.cs
- backend/core/Helpers/CsvHelper.cs
- backend/dal/Configuration/Views/PropertyConfiguration.cs
- backend/dal/Migrations/20220308190231_v01.16.00.Designer.cs
- backend/dal/Migrations/20220308190231_v01.16.00.cs
- backend/dal/Migrations/v01.16.00/Down/PostDown/01-ViewProperties.sql
- backend/dal/Migrations/v01.16.00/Up/Postup/01-ViewProperties.sql
- backend/entities/Views/Property.cs
Adding building and land assessed dates, UpdatedOn and Updated by fields to report, new db migration, changes to the property model and mapping, removing market value from the property list report.
Changes to the .vscode .NET version.
Also adding Sharala to code owners.
> PIMS-102: Report to validate updates have been completed

- frontend/src/features/projects/list/ProjectApprovalRequestListView.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/SPLProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/SPLProjectListView.test.tsx.snap
Adding props to the ProjectListView component to show or hide default status options. Changes to the SPLProjectListView and ProjectApprovalRequestView components.
> PIMS-77: changes to default filter and fixing snapshots and frontend tests

- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingValuationForm.test.tsx.snap
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/hooks/useLookupCodes.tsx
I'm not 100% sure if this is the right claim to use, but I changed the claim from `ADMIN_PROPERTIES` to `PROPERTY_EDIT`
> PIMS-113: Classification Status "Demolished" should be available for buildings

- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
I added logic that will copy the property information when creating a new sub-division.  I don't see any related code that use to do this, so I suspect it never did.
> PIMS-111 Fix add subdivision

- .gitignore
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/properties/map/MapView.tsx
When adding a subdivision the map will pan and zoom to the property for the specified PID.
> PIMS-111 Update Add Subdivision

- frontend/src/features/projects/disposals/information/ProjectProperties.tsx
If there are no properties on a project it will now display the error message.
> PIMS-131 Add validation error

- .github/workflows/app-react.yml
Upgrading the node version in Github so that the Github actions uses Node 14.
> testing the changed node version

- frontend/.devcontainer/Dockerfile
- frontend/.devcontainer/devcontainer.json
- frontend/.devcontainer/library-scripts/node-debian.sh
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/components/columns.tsx
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.tsx
- frontend/src/utils/utils.ts
A few tweaks to help with the frontend devcontainer.
> TNO-188 Fix Building Assessed Date

- frontend/src/components/common/form/ParentSelect.tsx
- frontend/src/components/tabs/styled/Tabs.tsx
- frontend/src/features/projects/common/components/columns.tsx
- frontend/src/features/projects/disposals/erp/AgencyInterest.tsx
- frontend/src/features/projects/disposals/erp/utils/addAgency.ts
- frontend/src/features/projects/disposals/interfaces/IProjectAgencyResponseForm.ts
- frontend/src/hooks/api/projects/disposals/interfaces/IProjectAgencyResponseModel.ts
- frontend/src/index.scss
Resolved issue with the agency response not working correctly.
> PIMS-281 Fix Agency Interest

- frontend/.dockerignore
- frontend/.gitignore
- frontend/src/features/help/components/text/TutorialHelpText.tsx
- frontend/src/features/help/constants/HelpText.tsx
- frontend/src/features/help/interfaces.tsx
- openshift/4.0/templates/api/deploy-routes.yaml
- openshift/4.0/templates/app/deploy.yaml
- openshift/4.0/templates/app/pvc.yaml
Adding Tutorial video links within the help section of the website.
Click each tutorial videos.
> PIMS-55 Add tutorial videos

- .github/CODEOWNERS
Please include a summary of the change and which issue is fixed.
N/A
> Adding Zach Bourque and Brady Mitchell to CodeOwners File

- frontend/src/features/properties/filter/PropertyFilter.tsx
Clicking the reset filter will clear current values.
Fixes # PIMS-304
Please describe the tests that you ran to verify your changes. 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
> PIMS-304 Fix reset filter

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/components/maps/leaflet/PointClusterer.tsx
- frontend/src/customAxios.ts
This fixes the bug which wasn't loading any properties on the View Property Information page.
Fixes the invalid hook error.
> removing the useMemo and console.logs

- frontend/package-lock.json
- frontend/package.json
Updated react-router-dom from version 6.2.1 to 6.3.0
Fixes [#266](https://apps.itsm.gov.bc.ca/jira/secure/RapidBoard.jspa?rapidView=294&projectKey=PIMS&view=detail&selectedIssue=PIMS-266)
> Bumped react-router-dom from 6.2.1 to 6.3.0

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/layout/Header/Header.tsx
- frontend/src/features/admin/admin-areas/EditAdminArea.tsx
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/mapSideBar/hooks/useBuildingApi.tsx
- frontend/src/features/projects/common/hooks/useStepForm.tsx
- frontend/src/store/slices/hooks/agencyActionCreator.ts
- frontend/src/store/slices/hooks/buildingActionCreator.ts
- frontend/src/store/slices/hooks/parcelsActionCreator.ts
- frontend/src/store/slices/hooks/useAccessRequest.ts
- Updated axios from version 0.26.0 to 0.27.2
- Changed instances of AxiosError to AxiosError<any> per the new update
- Ran `npm audit fix` which resolved:
- 4 critical vulnerabilities
- 2 high vulnerabilities
Fixes [PIMS-227](https://apps.itsm.gov.bc.ca/jira/secure/RapidBoard.jspa?rapidView=294&projectKey=PIMS&view=detail&selectedIssue=PIMS-227)
> Pims 227 - Updated axios / ran npm audit fix

- frontend/src/components/SearchBar/FilterBar.scss
- frontend/src/components/common/form/Button.tsx
- frontend/src/components/common/form/PlusButton.tsx
- frontend/src/components/maps/leaflet/InventoryLayer.tsx
- frontend/src/components/router/AppRouter.tsx
- frontend/src/features/admin/admin-areas/EditAdminArea.tsx
- frontend/src/features/admin/admin-areas/ManageAdminAreas.tsx
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/properties/map/MapView.tsx
Fixed most of the admin pages project list view, search bar filter. Should be able to view and edit users, agencies, and administrative areas now.
Fixed some of the routes on the "AppRouter.tsx" component.
The admin access requests page still needs to be tested properly as there are no access requests and we will need to figure out how to create one locally.
The drop downs should be populating on all the filter bars on most of the pages now that the lookupcodes "all" api is being called.
You should be able to edit an agency, although there is an intermittent 400 error (Bad Request) when clicking the "Save Changes" button for some reason. Clicking it a second time was successful with no errors.
The admin pages should be loading properly, although there are still some console errors to be …
> Fixing admin pages, project view filter bar

- frontend/src/features/admin/access-request/AccessRequestPage.tsx
- frontend/src/features/admin/access/components/Filter.tsx
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
Fixed the admin access request page console errors, populating dropdowns on the edit user, agency, and access request pages.
Tested an access request  by enabling the login using IDIR, see this to enable logging into localhost using your IDIR account: https://github.com/bcgov/PIMS/tree/dev/backend/keycloak, and I was getting some inconsistent errors, but was able to submit an access request in the end. This may need further testing on our local machines just to make sure it's working properly without any errors.
Fix was enclosing the Select object within <> </>
Fix was to set initial value of the position to either user.position or empty string ‘’:
position: user.position ?? ''
Fix was to enclose the FaArrowAltCircleLeft with <a> anchor tags. …
> Fixing admin access request page and various console errors

- codecov.yml
Codecov checks are failing in our recent pull requests, adding the target as 55..
https://docs.codecov.com/docs/commit-status
> Adding target in Codecov.yml

- .github/workflows/app-react.yml
- openshift/4.0/templates/app/build.yaml
> Changed git workflow for frontend node verison

- frontend/Dockerfile
> Add dumb-init to frontend dockerfile

- frontend/Dockerfile
- openshift/4.0/templates/app/build.yaml
> Undo build.yaml and changes to frontend dockerfile

- frontend/package-lock.json
- frontend/package.json
- openshift/4.0/templates/base-images/nodejs-16.yaml
Upgrading react-redux to try to solve this console error in the build-app step of the pims-pipeline for the dev environment.
Need to merge before a fix can be verified in Openshift.
> Upgrade react-redux to 7.2.9

- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
Changed frontend image in Dockerfile to this redhat image that I believe is a base image for the image we use in openshift.  
https://catalog.redhat.com/software/containers/ubi8/nodejs-16/615aee9fc739c0a4123a87e1?container-tabs=gti
Works locally. Need to merge and see if it works in OpenShift.
> Changed frontend image to redhat docker image

- frontend/Dockerfile
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
Changed npm version to 8.5.5 which removes the legacy peer deps errors.  
We will eventaully have to update dependencies that satisfy deep dependencies with the latest version of npm.
> Change npm version in frontend Dockerfile

- frontend/src/components/maps/leaflet/LayerPopup/LayerPopUpContent.test.tsx
- frontend/src/components/maps/leaflet/LayerPopup/__snapshots__/LayerPopUpContent.test.tsx.snap
- frontend/src/components/maps/leaflet/ZoomOut/ZoomOutButton.tsx
Fixing unit tests for the PopUpLayerContent and changes to leaflet syntax for the ZoomOutButton.
[PIMS-411](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-411) Fix LayerPopupContent tests 
[PIMS-412](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-412) Zoom out btn on map doesn't work
[![](https://img.shields.io/badge/known_issues-blueviolet?style=for-the-badge)](h …
> PIMS-411 & 412 fixing unit tests for PopUpLayerContent and zoom out button

- backend/dal/Pims.Dal.csproj
Fixed vulnerability issue w.r.t System.Dat.SqlClient(backend-api) based on the depend a bot alert.
[pims-413](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-413)
[depend a bot alert #51](https://github.com/bcgov/PIMS/security/dependabot/51)
- None listed.
[![](https://img.shields.io/badge/known_issues-blueviolet?style=for-the-badge)](https://hamzamohdzubair.gith …
> pims-413 - Fixed vulnerability issue w.r.t System.Dat.SqlClient(backend-api)

- frontend/src/components/maps/leaflet/Map.tsx
It seems that in react-leaflet version 3, [the url prop for the TileLayer is immutable](https://react-leaflet.js.org/docs/v3/api-components/#tilelayer), so apparently changing the url from a react perspective won't work.
The fix was to add a new tile layer in the toggle method of the Map.tsx and then adding a new layer and then setting the url of the layer that way.
Hopefully this doesn't create any new React issues, so this definitely needs some thorough testing on all the pages which use the map.
[//]: # (THESE COMMENTS …
> PIMS-424: Satellite basemap doesn't work 

- frontend/src/components/common/form/InputGroup.scss
- frontend/src/components/common/form/InputGroup.tsx
- frontend/src/components/common/form/Select.scss
- frontend/src/components/common/form/Select.tsx
- frontend/src/features/admin/access-request/__snapshots__/AccessRequestPage.test.tsx.snap
- frontend/src/features/admin/agencies/__snapshots__/EditAgencyPage.test.tsx.snap
- frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
- frontend/src/features/admin/users/__snapshots__/ManageUsers.test.tsx.snap
- frontend/src/features/admin/users/components/UsersFilterBar.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/projects/assess/steps/__snapshots__/ReviewApproveStep.test.tsx.snap
- frontend/src/features/projects/common/forms/__snapshots__/UpdateInfoForm.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/ReviewProjectStep.test.tsx.snap
- frontend/src/features/projects/dispose/steps/__snapshots__/SelectProjectPropertiesStep.test.tsx.snap
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/SPLProjectListView.test.tsx.snap
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/filter/PropertyFilterAgencyOptions.tsx
- frontend/src/features/properties/filter/PropertyFilterOptions.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilter.test.tsx.snap
- frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Tweaks to the positioning of elements within the filter bars.
- [PIMS-423](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-423) Fix filter bar input positioning
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove …
> Filter bar styling

- frontend/package-lock.json
- frontend/package.json
- frontend/src/features/admin/edit-user/EditUserPage.tsx
Upgraded keycloak-js from 15.1.1 to 20.0.1.
Resolved the following error, thanks @LawrenceLau2020  for the help.
- [PIMS-242](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-242) Upgrade keycloak-js.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN …
> Upgraded keycloak-js from 15.1.1 to 20.0.1

- frontend/package-lock.json
- frontend/package.json
- frontend/src/store/store.ts
Replaced redux-devtools-extension with @redux-devtools/extension.
Used within the jest tests.
- [PIMS-396](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-396) Replace redux-devtools-extension.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR …
> Replaced redux-devtools-extension which was deprecated

- backend/api/ches.Development.json
- backend/api/ches.Local.json
- backend/api/ches.Test.json
- backend/api/ches.json
This ticket is to address the changes to the host and auth urls for the CHES api which need to be done before Dec.31, 2022.
An access request was submitted for the new credentials to the new CHES api in "dev" as well as "test". I will submit the request for access to the new CHES API in production once we've at least migrated to DEV.
When this PR gets merged to DEV, we will need to update the CHES_PASSWORD and CHES_USERNAME secrets in OpenShift and then the same when it gets migrated to TEST and Production.
For testing locally, you'll need to update your /backend/api/.env file with the new Ches__Username and CHES__Password credentials that I will email …
> PIMS-425: CHES api url changes 

- frontend/.dockerignore
- frontend/Dockerfile
- frontend/package-lock.json
Changing the npm clean install in frontend dockerfile to just install.  
package-lock should be generated every time from the package.json
- None listed.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove …
> Changed npm clean install to install

- backend/api/ches.Test.json
- backend/api/ches.json
I forgot to change the AuthUrl in the previous ticket.
- None listed.
- None listed. …
> fixing the AuthUrls for test and prod

- frontend/src/features/projects/list/ProjectListView.scss
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/properties/list/PropertyListView.scss
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Added a number count to projects and properties on View Property Inventory and View Project pages.
<p align="center">
</p>
- [PIMS-368](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-368) Add number count when searching projects/inventory in PIMS.
[![](https://img.shields.io/badge/known_issues-blueviolet?style=for-the-badge)](https://hamzamohdzubair.github.io/re …
> Added count to View Property Inventory and View Projects pages

- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/SPLProjectListView.test.tsx.snap
Moved outside of the scope of hasCliam so users without the REPORTS_VIEW claim viewing the project list can see the project count.
- None listed.
[//]: …
> Moved project count outside of the hasClaim scope

- frontend/.gitignore
- frontend/package-lock.json
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/features/admin/admin-areas/EditAdminArea.tsx
- frontend/src/features/admin/admin-areas/__snapshots__/EditAdminArea.test.tsx.snap
- frontend/src/features/admin/agencies/EditAgencyPage.scss
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/admin/agencies/__snapshots__/EditAgencyPage.test.tsx.snap
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
Removed workflow note from Info Content, leaving only the status.
- [PIMS-127](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-127)
[//]: # (Please include …
> Removed workflow note from Info Content

- frontend/.gitignore
- frontend/package-lock.json
- frontend/src/components/Table/Table.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.test.tsx
- frontend/src/components/maps/leaflet/InfoSlideOut/InfoContent.tsx
- frontend/src/features/admin/access/__snapshots__/ManageAccessRequests.test.tsx.snap
- frontend/src/features/admin/admin-areas/EditAdminArea.tsx
- frontend/src/features/admin/admin-areas/__snapshots__/EditAdminArea.test.tsx.snap
- frontend/src/features/admin/agencies/EditAgencyPage.scss
- frontend/src/features/admin/agencies/EditAgencyPage.tsx
- frontend/src/features/admin/agencies/__snapshots__/EditAgencyPage.test.tsx.snap
- frontend/src/features/admin/edit-user/EditUserPage.tsx
- frontend/src/features/admin/edit-user/__snapshots__/EditUserPage.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectApprovalRequest.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/projects/list/__snapshots__/SPLProjectListView.test.tsx.snap
- frontend/src/features/projects/list/columns.tsx
- Modified the "Status" column in the View Disposal Projects table/page to use [Bootstrap Badges](https://react-bootstrap.github.io/components/badge/#pill)
- [PIMS-462](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-462)
[//]: # (THESE …
> PIMS 462 - Disposal Projects Status Badges

- frontend/src/components/layout/Header/Header.tsx
- frontend/src/layouts/PublicLayout.tsx
The test environment was showing the development theme because it saw 'dev' in the url path. Now it should correctly identify the environment.
- None listed.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no need to remove …
> Fix test environment theme

- docker-compose.yml
- scripts/gen-env-files.sh
- Updated the zip file for db seed data to use 'pims-local' database username.
- Updated gen-env-files script.
- [PIMS-476](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-476)
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no …
> Updated gen-env-files script for new db seed data

- scripts/gen-env-files.sh
Updated gen-env-files script to use 'admin' as the username for DAL DB migrations.
[PIMS-490] : https://apps.itsm.gov.bc.ca/jira/browse/PIMS-490
[//]: # …
> PIMS-490: Update username to admin

- backend/Dockerfile.ocp
The dev pipeline stopped working because it couldn't find the image for dotnet-aspnet. We are seeing if we can change it to pull an image from redhat container registry.
- None listed.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS …
> Changed opc dockerfile image for dotnet

- backend/Dockerfile.ocp
Workdirectories needed adjusting after changing the dockerfile. Still testing to see if this works in openshift.
- None listed.
[//]: # (Please include …
> Fix dockerfile workdirs

- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
- frontend/src/features/account/Login.tsx
- frontend/src/features/account/index.ts
- frontend/src/store/slices/networkSlice.ts
- Backend now no longer calls out to keycloak on access request approval
- Frontend redirects to access request page if user is a new user, or if they have no roles
- None listed.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS …
> Access Request Fix

- backend/api/Areas/Project/Mapping/Dispose/ProjectMap.cs
Resolves the issue when saving changes to any of the three financial values in the "**Properties**" tab in the "**Information**" section of a project: 
- Estimated Market Value
- Estimated Sales Costs
- Estimated Program Recovery Fees
These fees were not being accounted for in the "**Net Proceeds**" field of the SPL report, unless you were saving the project in the "**Close Out"** form.
There was just a missing calculation:
`Net Proceeds = Estimated Market Value – estimated sales costs – estimated program recovery fee – net book value. `
that needed to be added to the ProjectMap.cs class which maps a ProjectModel to the Project entity in the database. …
> PIMS-378 - Finance Reports

- frontend/src/components/layout/Header/UserProfile.tsx
- frontend/src/features/account/Login.tsx
- frontend/src/features/routes/IsAuthenticatedRoute.tsx
- frontend/src/features/routes/PrivateRoute.tsx
This PR updates the redirect urls passed to keycloak when performing login/logout actions. 
Changes:
- Keycloak's login and logout functions now use window.location.origin as the redirect url, as opposed to the previous window.location.href
- Removed remnants of unused/not working redirect functionality
- None listed. …
> Keycloak Redirect URL Fix

- backend/api/Areas/Project/Mapping/Dispose/ProjectMap.cs
- frontend/src/components/layout/Header/UserProfile.tsx
- frontend/src/features/account/Login.tsx
- frontend/src/features/routes/IsAuthenticatedRoute.tsx
- frontend/src/features/routes/PrivateRoute.tsx
- None listed.
- None listed.
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS …
> PIMS v02.03.00 To Test

- frontend/src/components/layout/Header/UserProfile.tsx
- frontend/src/features/account/Login.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useConfiguration.ts
- frontend/src/index.tsx
Fixed bug in which refreshing the page would case an invalid redirect_uri error from keycloak. This was caused due to the keycloak.init function not being passed a redirectUri, which caused it to implicitly use the current href. Due to there being a lack of wildcard support in keycloak gold production, we must pass the `window.location.origin` to the `redirectUri` field when making keycloak calls.
[//]: # (Please include a list of Jira …
> Keycloak Refresh Bug Fix

- backend/dal/Services/Admin/Concrete/UserService.cs
Fixed conditional value in UserService.cs
- None listed.
- None listed.
[//]: # (THESE …
> Fixed incorrect variable name for conditional in UserService.cs

- backend/dal/Services/Admin/Concrete/UserService.cs
Fixed conditional in UserService.cs which was testing for an incorrect value. In appsettings.Test.json, the configuration Pims:Environment:Name is set as "Testing" not "Test" as previously thought.
- None listed.
[//]: # (THESE COMMENTS …
> Backend Environment Name Fix

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- frontend/src/constants/claims.ts
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/hooks/useMyAgencies.ts
This is a new feature which gives a user the ability to only view all properties within PIMS.
Added a new "composite" role in Keycloak Gold called "**View Only Properties**" which contains the following claims: "**property-view**", "**admin-properties**" (which allows them to view all agencies properties), and the new claim "**view-only-properties**".
Right now, we have to manually assign a user the "**View Only Properties**" role in Keycloak, as the user admin page in PIMS is currently not getting the roles from Keycloak yet. (There will be a new ticket created for this.)
Once a user has this role, they will only have "read only" access to the map page …
> PIMS-472 - Viewing access role

- backend/dal/Helpers/Extensions/PropertyExtensions.cs
- frontend/src/constants/claims.ts
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/hooks/useMyAgencies.ts
> Release to Test: PIMS-472

- database/mssql/Dockerfile
DEV was already using 2022 tag, updating the local version before changing TEST.  
When testing, run `make setup`. It will error on the last step, which is the db migrations step, but running `make setup` again after the database container has updated its files to the 2022 versions it should work.
- [PIMS-493](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-493) …
> Updated mssql image tag from 2019 to 2022

- frontend/Dockerfile
Updates local frontend image to node 18, before testing in OpenShift.
- [PIMS-524](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-524)
[//]: # (Please …
> PIMS-524: Update Node Image to v18

- frontend/src/components/common/form/UserRoleSelector.tsx
- frontend/src/features/admin/users/ManageUsers.tsx
I mistakenly removed the wrong line to fix a test.
- None listed.
- None listed.
[//]: …
> Fix useEffect in recent EditUserPage changes

- frontend/package-lock.json
- frontend/package.json
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
- [PIMS-534](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-534)
[//]: # (Please include a list of known …
> Resolve high severity vulnerability in webpack

- backend/api/Areas/Admin/Models/User/GoldUserModel.cs
- backend/api/Areas/Reports/Mapping/User/UserMap.cs
- backend/api/Areas/Reports/Models/User/UserModel.cs
- Issue - Not able to export a list of users to Excel.
- Reason - There is a date field in the Users table, called CreatedOn, which is somehow being set as "0001-01-01 00:00:00.0000000" for some users.
- Cause - not known as of yet.
- Fix - removed 4 fields from the user export report: CreatedOn, UpdatedOn, UpdatedByName, UpdatedByEmail, & RowVersion.
- …
> PIMS-523 - Unable to export user list to Excel

- frontend/cypress.config.ts
- frontend/cypress/e2e/disposalProjects.cy.ts
Now the test will create a Submitted Exemption project, approve it to Approved for Exemption, and then clean up.
- [PIMS-541](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-541)
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, …
> Add approval step to cypress Disposal Projects test

- backend/Dockerfile.migrations
For some reason, the db-migration step in the dev pipeline failed due to a permissions issue. According to this github issue: 
https://github.com/dotnet/core/issues/7868, a possible fix is to add an environment variable "XDG_DATA_HOME" to set the proper directory location.
`Fetching connection information
Running database migration in 354028-dev
If you don't see a command prompt, try pressing enter.
Using project '/src/dal/Pims.Dal.csproj'.
Using startup project '/src/dal/Pims.Dal.csproj'.
Writing '/src/dal/obj/Pims.Dal.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpZ1iyUZ.tmp …
> Fixing issue with db-migration

- .vscode/launch.json
- backend/.vscode/launch.json
- backend/api/Areas/Admin/Controllers/UserController.cs
- backend/api/Areas/Admin/Mapping/User/UserMap.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
- backend/entities/User.cs
- backend/tests/unit/api/Controllers/Admin/UserControllerTest.cs
- frontend/src/features/admin/users/ManageUsers.tsx
- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/utils/YupSchema.ts
- Updating a user no longer overrides the CreatedBy, CreatedOn, LastLogin, ApprovedBy, and ApprovedOn fields.
- BCeID firstname and Lastname should now be populated correctly in the Access Request Form.
- Fixed debugging in VSCode for .Net 6.0
- [PIMS-581](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-581) …
> Updating a User incorrectly set CreatedBy, CreatedOn, LastLogin, ApprovedBy, and ApprovedOn fields

- .github/workflows/cypress-app-dev.yml
- [PIMS-595](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-595)
- None listed.
[//]: # …
> Added npm install to cypress github action

- backend/api/Pims.Api.csproj
- backend/ches/Pims.Ches.csproj
- backend/core/Pims.Core.csproj
- backend/dal/Pims.Dal.csproj
- backend/entities/Pims.Dal.Entities.csproj
- backend/notifications/Pims.Notifications.csproj
- backend/tests/core/Pims.Core.Test.csproj
- backend/tests/unit/api/Pims.Api.Test.csproj
- backend/tests/unit/dal/Pims.Dal.Test.csproj
- backend/tests/unit/dal/Services/ProjectReportServiceTest.cs
- backend/tests/unit/dal/Services/ProjectServiceTest.cs
Updating package transitive dependencies to resolve the 10 high and 7 medium issues in Snyk and fixing broken unit tests due to having upgraded **FluentAssertions** to version 6.10.0 from 5.10.3.
Should test the SPL reports to make sure they still work properly.
- [PIMS-582](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-582) …
> PIMS- 582 - Snyk security vulnerabilities in backend

- backend/api/Areas/Admin/Controllers/UserController.cs
- backend/api/Controllers/UserController.cs
- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
- backend/entities/GoldUser.cs
- backend/entities/User.cs
- frontend/src/store/slices/hooks/useAccessRequest.ts
- frontend/src/store/slices/hooks/usersActionCreator.ts
When an access request is accepted, it will now properly set the user's agency and role, both for the database and keycloak.
- [PIMS-586](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-586)
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS …
> Fixed access request agency and role

- backend/api/Areas/Admin/Controllers/UserController.cs
- backend/api/Areas/Admin/Mapping/User/UserMap.cs
- [PIMS-593](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-593)
- None listed.
[//]: # …
> Fix last login not showing in Admin > Users page

- frontend/src/features/projects/common/components/PropertyListViewSelect.tsx
- frontend/src/features/projects/disposals/information/ProjectProperties.tsx
Clicking on a property in the disposal projects pages redirects to the mapview and opens the property details.
- [PIMS-590](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-590)
[//]: # (THESE COMMENTS ARE HIDDEN WHEN THE PR IS PUBLISHED, no …
> Fixed property redirect from projects pages

- backend/api/Pims.Api.csproj
- backend/dal/Pims.Dal.csproj
- backend/entities/Pims.Dal.Entities.csproj
- backend/notifications/Pims.Notifications.csproj
- tools/converters/excel/Pims.Tools.Converters.ExcelConverter.csproj
This PR should address most of the outstanding Snyk backend vulnerabilities.
- [PIMS-582](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-582)
- None listed.
All backend and front end tests passed, did a brief check on local frontend was able to create a new project.
> PIMS-582.1 - Snyk security vulnerabilities in backend

- .github/labeler.yaml
Using /**/* instead of /* to include sub directory files.
- None.
- None listed.
> Edited the labeler.yaml

- .github/workflows/cypress-app-dev.yml
> Updated cypress github action

- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/properties/components/GeocoderAutoCompleteStyled.tsx
- frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
Fixed the address suggestions displaying over input field on 'Add Land' form.
- [PIMS-604](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-604)
- None listed.
Visually correct on page.
> Fixed Address suggestions displaying over input field

- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandSearchForm.tsx
- frontend/src/features/properties/hooks/useGeocoder.tsx
- frontend/src/features/properties/hooks/useParcelLayerData.tsx
- Changed 'Drop A Pin' tab title to 'Select a Parcel from the Map'.
- Fixed some fields from staying populated after selecting a new parcel.
- [PIMS-607](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-607)
- If you search for a parcel and then click on a new parcel, the Street Address field will stay populated with the old value until you click on another parcel.
Selecting parcels in Add Land form of 'Submit Property' nav bar tab.
- I have commented my code, particularly in …
> Tweaks to Add Land Form

- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/LandForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/__snapshots__/BuildingReviewPage.test.tsx.snap
- frontend/src/features/properties/components/GeocoderAutoCompleteStyled.tsx
- frontend/src/features/properties/filter/PropertyFilter.scss
- frontend/src/features/properties/filter/__snapshots__/PropertyFilterOptions.test.tsx.snap
Address suggestions was cut off from the search filter on mapview.
- [PIMS-611](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-611)
- None listed.
Visually correct.
> Fix search filter address suggestions

- .github/workflows/cypress-app-dev.yml
- backend/api/Areas/Admin/Controllers/AccessRequestController.cs
- backend/api/Areas/Admin/Controllers/AdministrativeAreaController.cs
- backend/api/Areas/Admin/Controllers/AgencyController.cs
- backend/api/Areas/Admin/Controllers/ClaimController.cs
- backend/api/Areas/Admin/Controllers/RoleController.cs
- backend/api/Areas/Admin/Controllers/UserController.cs
- backend/api/Areas/Keycloak/Controllers/RoleController.cs
- backend/api/Areas/Keycloak/Controllers/UserController.cs
- backend/api/Areas/Notification/Controllers/QueueController.cs
- backend/api/Areas/Notification/Controllers/TemplateController.cs
- backend/api/Areas/Project/Controllers/DisposeController.cs
- backend/api/Areas/Project/Controllers/ReportController.cs
- backend/api/Areas/Project/Controllers/SearchController.cs
- backend/api/Areas/Property/Controllers/BuildingController.cs
- backend/api/Areas/Property/Controllers/ParcelController.cs
- backend/api/Areas/Property/Controllers/SearchController.cs
- backend/api/Areas/Reports/Controllers/ProjectController.cs
- backend/api/Areas/Reports/Controllers/PropertyController.cs
- backend/api/Areas/Reports/Controllers/UserController.cs
- backend/api/Areas/Tools/Controllers/ChesController.cs
- backend/api/Areas/Tools/Controllers/ImportController.cs
- backend/api/Controllers/AuthController.cs
- backend/api/Controllers/UserController.cs
- frontend/src/features/projects/disposals/DisposalProject.tsx
It seems that the project status bar doesn't always load when clicking on a project from the project list view. After debugging, I noticed that the project "state" variable was undefined for some reason.
- [PIMS-613](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-613)
- None listed.
Tested locally, can't seem to reproduce the bug anymore.
- My …
> PIMS-613 - When Project status bar doesn't load, it creates an error when saving a project

- frontend/package-lock.json
- frontend/package.json
Overrides yaml dependency versions less than 2.2.2 and sets them to 2.2.2
- [PIMS-622](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-622)
- None listed.
Application runs, and vulnerability is no longer reported in npm.
> Resolve vulnerability in yaml

- frontend/cypress/e2e/disposalProjects.cy.ts
- frontend/package-lock.json
Updated disposalProjects Cypress test to work again.
- None listed.
Cypress test passes.
> Update Cypress Test

- backend/api/Areas/Admin/Controllers/UserController.cs
Missed removing the ValidateAntiForgery attributes on the UserController endpoints.
- [PIMS-608](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-608)
- None listed.
> PIMS-608- quickfix

- .github/helpers/check-npm-dependency-versions.js
- .github/workflows/cypress-app-dev.yml
- .github/workflows/frontend-npm-dependency-updates.yml
- Changed cypress action to run on a cron job instead of push to dev. Once we update our pipeline we can run after deploying but for now theres no way to tell once the pipeline has completed so it can run tests against dev.
- Updated npm dependency action formatting and cron job.
- None listed.
Tested formatting in github comment.
- I have made …
> Updated schedule for cron job actions

- .github/workflows/app-cypress-dev.yml
- .github/workflows/app-npm-dependency-updates.yml
- frontend/package.json
Possible fix for Cypress Workflow and updated naming of workflows for consistency.
- None listed.
Will need to run workflow once merged.
> Possible fix for Cypress Workflow

- .github/workflows/app-cypress-dev.yml
- .github/workflows/app-npm-dependency-updates.yml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/maps/leaflet/MapProperties.test.tsx
- Updated the react-resize-detector to 9.1.0
- Needed to remove one line in the MapProperties.test.tsx in order to resolve a failing test.
- [PIMS-634](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-634)
- None listed.
All front and back end tests are passing.
> PIMS-634 - Update react-resize-detector to v9.1.0

- nginx/html/index.html
Just updating the maintenance page which gets displayed during the Openshift builds.
- None listed.
> Updating the maintenance page

- frontend/package.json
Fixing a typo in the package.json
- [PIMS-645](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-645)
- None listed.
> PIMS-645 - Fixing typo in package.json

- frontend/Dockerfile.ocp
- [PIMS-647](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-647)
- None listed.
> Added Frontend Dockerfile.ocp

- frontend/Dockerfile.ocp
- frontend/package.json
- [PIMS-000](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-000)
- None listed.
> Removed cross-env from ocp build

- .github/workflows/app-npm-dependency-updates.yml
Now runs once a week on Tuesdays at 7-8am PT.
- [PIMS-646](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-646)
- None listed.
> Changed NPM Action Schedule

- frontend/package.json
- [PIMS-000](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-000)
- None listed.
> Moved redux dev tools to standard dep

- frontend/Dockerfile.ocp
- [PIMS-000](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-000)
- None listed.
> Removed omit dev deps from Dockerfile.ocp

- .github/workflows/app-cypress-dev.yml
Wasn't installing packages correctly.
- None listed.
> Updated Cypress Action Install Deps Step

- frontend/Dockerfile.ocp
- [PIMS-000](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-000)
- None listed.
> Forgot to switch FROM instruction after testing

- frontend/src/components/maps/leaflet/InventoryLayer.tsx
There was a bug in the InventoryLayer.tsx file, it was just missing some code in the filter which would return the parcels.
- [PIMS-648](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-648)
- None listed.
All frontend tests are passing, and able to view parcels in the map view.
> PIMS-648 - Land Markers Don't Show Up On Map

- .github/helpers/check-npm-dependency-versions.js
- .github/helpers/github-api-requests.js
- .github/helpers/npm-dependencies-create-issue.js
- .github/workflows/app-npm-dependency-updates.yml
- npm-dependency-versions.js helper now takes in the path to the package.json as an environment variable instead of command line args.
- Added github-api-requests.js helper script that provides functions for calling the github rest API.
- Added npm-dependencies-create-issue.js helper script that creates a github issue and closes an old one if it exists.
- Changed the app-npm-dependency-updates workflow to use the new helper scripts to call the github api.
- [PIMS-643](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-643)
- None listed. …
> NPM GitHub Workflow - Closes Old Issues

- .github/workflows/app-cypress-dev.yml
Trying to get cypress to use the right variables and config options.
- None listed.
Need to test after merge.
> Cypress Workflow

- .github/helpers/github-api-requests.js
- .github/helpers/npm-dependencies-create-issue.js
- .github/workflows/app-npm-dependency-updates.yml
- Commented about where to find API Specification Docs.
- Added an example usage comment.
- Moved GITHUB_OWNER and GITHUB_REPO variables to the api requests file to reduce duplication of code.
- [PIMS-654](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-654)
- None listed.
Will require running in GitHub Actions.
> Additional Commenting on GitHub API Requests Helper

- frontend/src/components/maps/leaflet/Map.tsx
- frontend/src/features/projects/list/ProjectListView.tsx
- frontend/src/features/properties/filter/PropertyFilter.tsx
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/hooks/useLookupCodes.tsx
Fixing some of the data issues being sent to Snowplow.
- [PIMS-657](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-657)
- Only thing not fixed is the fourth issue mentioned in Dan's email where the statuses are being sent to Snowplow as a list of numbers instead of strings. Currently the codebase doesn't have a lookup for project statuses and we'll need to make one.
Console logged the changes made.
- I have made …
> Pims 657 - Fixing data issues for Snowplow

- frontend/src/hooks/useKeycloakWrapper.tsx
- frontend/src/utils/YupSchema.ts
Should allow BCeID users to submit an access request.
- [PIMS-660](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-660)
- None listed.
> BCeID Access Request

- frontend/cypress.config.ts
- frontend/cypress/e2e/disposalProjects.cy.ts
- frontend/cypress/e2e/navBar.cy.ts
- frontend/src/features/projects/disposals/documentation/ProjectDocumentation.tsx
Upped the timeout for cypress actions and changed the address for the properties search so that the property existed in both local and dev.
- None listed.
Tested `npm run cypress:e2e` and `npm run cypress:e2e-dev`
> Updated Cypress Tests

- .github/workflows/app-cypress-dev.yml
- frontend/cypress/e2e/disposalProjects.cy.ts
- frontend/cypress/e2e/navBar.cy.ts
Cypress Tests are finally working in GitHub Actions so this is just some clean up.
- Removed timeouts from the tests as the timeout was upped to 15000 in the cypress config.
- Trying to set the install command through the cypress action.
- None listed.
Tests run locally.
- My changes …
> Cypress Cleanup

- docker-compose.yml
- frontend/Dockerfile
- frontend/nginx.conf
Adds the required Docker configurations for testing the production build locally, as it would work in DEV, TEST, PROD.
Updated documentation: https://github.com/bcgov/PIMS/wiki/OpenShift#testing-the-production-build-locally
<br />
- [PIMS-661: Local Testing of Prod Build](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-661)
<br />
```
```
[CHECKLIST]: …
> PIMS-661: Local Testing of Prod Build

- frontend/package.json
- frontend/src/components/common/form/FastDatePicker.test.tsx
- frontend/src/components/maps/leaflet/LayersControl/LayersControl.test.tsx
- frontend/src/features/admin/admin-areas/ManageAdminAreas.test.tsx
- frontend/src/features/admin/admin-areas/__snapshots__/ManageAdminAreas.test.tsx.snap
- frontend/src/features/admin/edit-user/EditUserPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.test.tsx
- frontend/src/features/projects/common/forms/UpdateInfoForm.test.tsx
- frontend/src/features/projects/dispose/forms/PropertyListViewSelect.test.tsx
- frontend/src/features/projects/dispose/forms/__snapshots__/PropertyListViewSelect.test.tsx.snap
- frontend/src/features/projects/dispose/steps/SelectProjectPropertiesStep.test.tsx
- frontend/src/features/projects/list/ProjectListView.test.tsx
- frontend/src/features/projects/list/__snapshots__/ProjectListView.test.tsx.snap
- frontend/src/features/properties/components/LastUpdatedBy.test.tsx
- frontend/src/features/properties/components/forms/subforms/PidPinForm.test.tsx
- frontend/src/features/properties/filter/PropertyFilter.test.tsx
- frontend/src/features/properties/list/PropertyListView.test.tsx
- frontend/src/features/properties/list/__snapshots__/PropertyListView.test.tsx.snap
Missing act warnings are enabled in the global setup that comes with @testing-library/react. To disable the act warning,  the global variable IS_REACT_ACT_ENVIRONMENT is set to false.
- [PIMS-550](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-550)
- None listed.
> PIMS-550: Resolve act() warnings in jest tests

- .github/helpers/check-npm-dependency-versions.js
- .github/workflows/app-npm-dependency-updates.yml
Updated Formatting in npm Dependency Check
<br />
- [PIMS-674](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-674)
<br />
```
```
> PIMS-674: Updated Formatting in npm Dependency Check

- frontend/package.json
Update react router dom to 6.13.0
- [PIMS-673](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-673)
- None listed.
Ran npm-refresh and application loads, nav links work.
> Update react router dom to 6.13.0

- frontend/package.json
Update bootstrap to 5.3.0
<br />
- [PIMS-669: Update bootstrap to 5.3.0](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-669)
<br />
```
```
> Update bootstrap to 5.3.0

- frontend/package.json
Upgrade @typescript-eslint/eslint-plugin from version 5.59.6 to 5.60.0
- [PIMS-689: Upgrade @typescript-eslint/eslint-plugin](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-689)
<br />
```
```
> PIMS-689: Upgrade @typescript-eslint/eslint-plugin

- frontend/package.json
- Change node-sass to sass for MacOS compatibility.
- Fix vulnerabilities with semver
<br />
- [PIMS-686: Change node-sass to sass for MacOS compatibility](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-686)
<br />
```
```
> PIMS-686: Change node-sass to sass for MacOS compatibility

- frontend/package.json
Upgrade dotenv from version 16.0.3 to 16.3.1
<br />
- [PIMS-692: Upgrade dotenv](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-692)
<br />
```
```
> PIMS-692: Upgrade dotenv

- frontend/package.json
Upgrade @typescript-eslint/parser  from version 5.59.6 to 5.60.1
<br />
- [PIMS-691: Upgrade @typescript-eslint/parser](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-691)
<br />
```
```
> PIMS-691: Upgrade @typescript-eslint/parser

- frontend/package.json
Upgrade eslint  from version 8.40.0 to 8.43.0
<br />
- [PIMS-694: Upgrade eslint ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-694)
<br />
```
```
> PIMS-694: Upgrade eslint 

- frontend/package.json
Upgrade @types/jest from version 29.5.2 to 29.5.3
[PIMS-697](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-697)
> PIMS-697: Upgrade @types/jest

- frontend/package.json
[PIMS-698](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-698)
> PIMS-698: Upgrade babel-jest

- frontend/package.json
[PIMS-695](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-695)
Upgrade typescript from version 5.0.4 to 5.1.6
> PIMS-695: Upgrade typescript

- frontend/package.json
[PIMS-705](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-705)
Upgrade @types/react-paginate from version 6.2.1 to 7.1.1
> PIMS-705: Upgrade @types/react-paginate

- .github/CODEOWNERS
[PIMS-105: Give Taylor and Dylan access to Github](https://citz-imb.atlassian.net/browse/PIMS-105)
> Adding Dylan and Taylor to PIMS github

- frontend/package.json
[PIMS-702](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-702)
Upgrade @types/react-leaflet from version 2.8.2 to 3.0.0
> PIMS-702: Upgrade @types/react-leaflet

- frontend/package.json
[PIMS-108: ](https://citz-imb.atlassian.net/browse/PIMS-108)
Update @babel/core from version 7.22.8 to 7.22.9 
> PIMS-108 update @babel/core

- frontend/package.json
- frontend/src/actions/parcelsActions.ts
- frontend/src/components/common/form/FastCurrencyInput.tsx
- frontend/src/components/common/form/FastInput.tsx
- frontend/src/components/common/form/Input.tsx
- frontend/src/components/common/form/Typeahead.tsx
- frontend/src/features/mapSideBar/SidebarContents/LandForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.scss
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandSearchForm.tsx
- frontend/src/features/mapSideBar/components/tables/ChargeTable.tsx
- frontend/src/features/mapSideBar/components/tables/OwnershipTable.tsx
- frontend/src/features/mapSideBar/components/tabs/HeaderDivider.tsx
- frontend/src/features/mapSideBar/components/tabs/ParcelDetails.tsx
- frontend/src/features/mapSideBar/components/tabs/TabStyles.ts
- frontend/src/features/mapSideBar/components/tabs/TitleOwnership.tsx
- frontend/src/features/mapSideBar/components/tabs/UsageValuation.tsx
- frontend/src/features/properties/components/forms/subforms/AddressForm.tsx
- frontend/src/hooks/useApi.ts
- frontend/src/utils/index.ts
- frontend/src/utils/postalCodeFormatter.ts
> Merge dev to master

- frontend/package.json
Merging dev and master v02.06.06
> Merging Master and dev v02.06.06

- frontend/src/features/mapSideBar/components/tabs/TitleOwnership.tsx
[PIMS-155: ](https://citz-imb.atlassian.net/browse/PIMS-155?atlOrigin=eyJpIjoiMmE5ODEyMzcyZGU3NGZkN2FlMmY3ZjI0YjY0NGJkMjMiLCJwIjoiaiJ9) change Market Value to Sales History in Title & Ownership Tab
> [PIMS-155] change Market Value to Sales History

- frontend/.eslintrc.cjs
Quick fix to a duplicate enum issue that seems to be popping up.
Changed to a warning (from previous error) for now. 
Should review whether that duplicate enum is a necessity or if we can improve it.
> eslint config - warn for duplicate enums

- frontend/package.json
- frontend/src/components/common/Stepper.tsx
- frontend/src/features/projects/disposals/validation/documentationSchema.ts
- frontend/src/features/projects/disposals/validation/erpCompleteSchema.ts
- frontend/src/features/projects/disposals/validation/erpDisposedSchema.ts
- frontend/src/features/projects/disposals/validation/erpExemptionSchema.ts
- frontend/src/features/projects/disposals/validation/informationProjectSchema.ts
- frontend/src/features/projects/disposals/validation/informationPropertiesSchema.ts
- frontend/src/features/projects/disposals/validation/notSplSchema.ts
- frontend/src/features/projects/disposals/validation/splApprovalSchema.ts
- frontend/src/features/projects/disposals/validation/splContractInPlaceSchema.ts
- frontend/src/features/projects/disposals/validation/splMarketingSchema.ts
- frontend/src/features/projects/disposals/validation/splTransferWithinGRESchema.ts
- frontend/src/features/projects/disposals/validation/useProjectValidation.ts
- frontend/src/features/projects/dispose/forms/disposalYupSchema.ts
- frontend/src/features/properties/list/PropertyListView.tsx
- frontend/src/utils/YupSchema.ts
[PIMS-145: ](https://citz-imb.atlassian.net/browse/PIMS-145?atlOrigin=eyJpIjoiMTc2NmNiMTg4MmZmNDViOGI0MzlkNTE4MDIzZGQzYjMiLCJwIjoiaiJ9) Update yup package
v1.x.x includes many syntax changes.
1. .then and .otherwise properties changed like this:
```ts
// from this
then: Yup.object({
id: Yup.string().required(),
label: Yup.string().required(),
value: Yup.string().required()
}),
// to this
then: () => // change is here 👈
Yup.object({
id: Yup.string().required(),
label: Yup.string().required(),
value: Yup.string().required()
}),
```
2. .shape() usually isn't needed
```ts
Yup.object().shape({});
// becomes
Yup.object({})
```
There are a couple of cases where shape is needed, such as when two properties depend on each other. Yup specifically recommends against doing this, but it is used in …
> [PIMS-145] yup package update

- backend/api/appsettings.json
The LTSA url for production was incorrect. Updated with 'login' portion.
> Correct LTSA prod AuthUrl

- frontend/package.json
[PIMS-159: ](https://citz-imb.atlassian.net/browse/PIMS-159)
Update @babel/core from version 7.22.9 to 7.22.10
> PIMS-159 Update @babel/core

- frontend/package.json
[PIMS-160: ](https://citz-imb.atlassian.net/browse/PIMS-160)
Update formik from version 2.4.2 to 2.4.3
> PIMS-160 update formik

- frontend/package.json
[PIMS-166: ](https://citz-imb.atlassian.net/browse/PIMS-166)
Update from babel-jest version 29.6.2 to 29.6.3
> Update from babel-jest

- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/BuildingReviewPage.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/LandReviewPage.scss
- frontend/src/features/mapSideBar/components/tabs/BuildingDetails.tsx
- frontend/src/features/mapSideBar/components/tabs/OccupancyValuation.tsx
- frontend/src/features/mapSideBar/components/tabs/ParcelDetails.tsx
- frontend/src/features/mapSideBar/components/tabs/TitleOwnership.tsx
- frontend/src/features/mapSideBar/components/tabs/UsageValuation.tsx
[PIMS-208: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-208)
Testing details:
Select a Building marker. 
View details/Review page.
Existing issue:
I haven't been able to get MUI to cooperate with the .scss files. Leaving the styling as is for now, with the hope to go back to it later.
> [PIMS-208] Building Review Page Update

- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/subforms/AssociatedLandReviewPage.tsx
- frontend/src/features/mapSideBar/components/tabs/ParcelDetails.tsx
- frontend/src/features/mapSideBar/components/tabs/UsageValuation.tsx
[PIMS-211: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-211)Add Associated Land Page formatting should be updated
Updated the Associated Land Review tab to use the components from the regular Land Review page.
Testing instructions:
- Select a building marker. 
- On the final review page, enable edit mode and choose Modify Associated Land.
- Go to step 5 (Review & Submit) to view changes.
Future suggestions:
The way the tabs for each piece of associated land work with this review page (where all land is visible regardless of the tab selected) seems confusing. Maybe this could use a rework.
> - I …
> [PIMS-211] Associated land style update

- frontend/package.json
[PIMS-238: ](https://citz-imb.atlassian.net/browse/PIMS-238)
Update @testing-library/user-event from version 14.4.3 to 14.5.0
> PIMS-238 update @testing/library/user-event

- frontend/package.json
[PIMS-324: ](https://citz-imb.atlassian.net/browse/PIMS-234)
Update react-datepicker from version 4.16.0 to 4.17.0
> PIMS-234 update react-datepicker

- frontend/package.json
[PIMS-237: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-237)updated sass to 1.67.0
> [PIMS-237] updated sass to 1.67.0

- frontend/package.json
[PIMS-235: ](https://citz-imb.atlassian.net/browse/PIMS-235)
> PIMS-235: update-react-icons

- frontend/Dockerfile
- frontend/Dockerfile.ocp
- frontend/package.json
[PIMS-251: ](https://citz-imb.atlassian.net/browse/PIMS-251?atlOrigin=eyJpIjoiOTQyN2UxMjg0OGFjNDI1NmE5MDljYjY2NDcxOGNlOTgiLCJwIjoiaiJ9)
Moved the dependencies for vite from the Dockerfiles to the package.json.
I hope this will allow us to better track them when they update. 
> PIMS-251: Prod Build Failing on SVG Imports

- frontend/Dockerfile
- frontend/Dockerfile.ocp
- frontend/package.json
[PIMS-251: ](https://citz-imb.atlassian.net/browse/PIMS-251?atlOrigin=eyJpIjoiYTIwZGY1NzAxOWIzNGQ0YzhhMDZmMzMxNWQxNjU2NDgiLCJwIjoiaiJ9) Dev container fix/SVG fix
The last change, which moved the Vite dependencies into package.json, broke the development container. 
This fix moves them back to the Dockerfile, but also specifies the version.
We should find a long-term solution to this at a later date, as we don't have any checks for these version updates.
Tested with both dev and prod container builds.
> PIMS-251: Fix developer container

- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.scss
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
[PIMS-210: ](https://citz-imb.atlassian.net/browse/PIMS-210) - General Small Touchups
Fixing spacing with the button when modifying associated land from the building form.
> PIMS-210: General Small Touchups

- frontend/package.json
PIMS-276 :  Update react-datepicker from version `4.17.0` to `4.18.0`                             
[PIMS-276](https://citz-imb.atlassian.net/browse/PIMS-276)
> PIMS-276: Update react-datepicker

- frontend/package.json
[PIMS-283: ](https://citz-imb.atlassian.net/browse/PIMS-283)
Update cypress from version `13.1.0` to `13.3.0`
> PIMS-283_update_cypress

- frontend/package.json
[PIMS-275: ](https://citz-imb.atlassian.net/browse/PIMS-275)
[PIMS-280: ](https://citz-imb.atlassian.net/browse/PIMS-280)
Update @babel/core from version `7.22.15` to `7.23.0`
Update @babel/preset-typescript from version `7.22.15` to `7.23.0`
> PIMS-275 PIMS-280 @babel/core and @babel/preset-typescript

- frontend/package.json
[PIMS-281: ](https://citz-imb.atlassian.net/browse/PIMS-281?atlOrigin=eyJpIjoiNjQ2Y2I5MjNmZjMxNGZiMWE1MjU5N2FjNmQ4ODRiYzgiLCJwIjoiaiJ9)Update axios-mock-adapter to 1.22.0
> [PIMS-281] Update axios-mock-adapter to 1.22.0

- frontend/src/features/mapSideBar/components/tables/OwnershipTable.tsx
[PIMS-250: ](https://citz-imb.atlassian.net/browse/PIMS-250?atlOrigin=eyJpIjoiOTU1OWU2N2E4OWU0NDgxOThlYmU2YjExNWUwMGVkODEiLCJwIjoiaiJ9)
Added condition that will round ownership percentages to 2 decimal places but only if it's not a whole number already.
> [PIMS-250] Ownership Percentages Infinite Repeat 

- frontend/package.json
PIMS-279: Update yup from version `1.2.0` to `1.3.1`                                       
[PIMS-279](https://citz-imb.atlassian.net/browse/PIMS-279)
> PIMS-279: Update yup

- frontend/package.json
[PIMS-284: ](https://citz-imb.atlassian.net/browse/PIMS-284)
Update eslint
> PIMS-284 Update eslint

- frontend/package.json
[PIMS-278: ](https://citz-imb.atlassian.net/browse/PIMS-278)
Update sass
> PIMS-278 Update sass

- frontend/src/utils/YupSchema.ts
PIMS-220:   Save Updates has hidden requirements on Building Review page
- Removed the validation on 'Net Usable Area' and 'Updated On' on the Building Occupancy page. This removes the restriction on clicking 'Save updates' on the Building review page.
[PIMS-220](https://citz-imb.atlassian.net/browse/PIMS-220)
> PIMS-220: Save Updates has hidden requirements on Building Review page

- frontend/package.json
PIMS-331: Update jest-styled-components from version `7.1.1` to `7.2.0` 
[PIMS-331](https://citz-imb.atlassian.net/browse/PIMS-331)
> PIMS-331 - Update jest-styled-components from version `7.1.1` to `7.2.0`

- frontend/package.json
[PIMS-311: ](https://citz-imb.atlassian.net/browse/PIMS-311)
Update react-bootstrap from version `2.8.0` to `2.9.0`
> PIMS-311 update react-bootstrap

- frontend/package.json
[PIMS-328: ](https://citz-imb.atlassian.net/browse/PIMS-328)
Update @types/react-datepicker from version `4.15.0` to `4.19.0`
> PIMS-328 update @types/react-datepicker

- frontend/package.json
[PIMS-325: ](https://citz-imb.atlassian.net/browse/PIMS-325?atlOrigin=eyJpIjoiMDliNDBlOGQ4MmQxNGZlMWI0MWVjNzNhMjUxN2RlMzAiLCJwIjoiaiJ9)
Updated bc-sans to version 2.1.0
Tested building container and navigating around site. No visible issues.
> [PIMS-325] Update bc-sans@2.1.0

- .github/helpers/jira-api/README.md
[DEVOP-159: ](https://citz-imb.atlassian.net/browse/DEVOP-159)
Updating documentation on service account.
> updating documentation on service account

- .github/helpers/jira-api/README.md
[DEVOP-159: ](https://citz-imb.atlassian.net/browse/DEVOP-159)
Updating Documentation to accurately represent steps necessary to update the Jira API key.
> Updating API storage doc

- frontend/package.json
[PIMS-342: ](https://citz-imb.atlassian.net/browse/PIMS-342?atlOrigin=eyJpIjoiMWFhNjEzNjM3NDI2NDMzNjkyMTNjMDlhNzFmOGRiYmMiLCJwIjoiaiJ9)
Updates the crypto-js package to 4.2.0
This only appears to be used when processing forms (saving, retrieving, etc.). 
No issues noticed when creating and saving forms in the frontend.
> PIMS-342: Update crypto-js to 4.2.0

- frontend/package.json
PIMS-343: Update react-datepicker from version `4.20.0` to `4.21.0`
[PIMS-343](https://citz-imb.atlassian.net/browse/PIMS-343)
> PIMS-343: Update react-datepicker from version `4.20.0` to `4.21.0`

- backend/api/Pims.Api.csproj
[PIMS-358: ](https://citz-imb.atlassian.net/browse/PIMS-358) - SNYK - Azure.Identity Remote Code Execution vulnerability
[PIMS-359: ](https://citz-imb.atlassian.net/browse/PIMS-359) - SNYK - Microsoft.Rest.ClientRuntime vulnerability
According to Snyk there is one high and one medium vulnerability in the /backend/api/Pims.Api.csproj which is being introduced through these packages: “Azure.Identity” and "AspNetCore.HealthChecks.SqlServer".
Adding the explicit package version to "Azure.Identity" and "Microsoft.Rest.ClientRuntime" resolves the issue, and have tested this in my remote PIMS dev branch.
Rebuilt the backend, and the api still works.
The screenshot below, shows the 2 vulnerabilities in the backend/api/Pims.Api.csproj, and the one below shows them as resolved after merging this PR …
> PIMS-358 & PIMS-359 - Snyk Vulnerabilities in Pims.Api.csproj

- frontend/package.json
[PIMS-357: ](https://citz-imb.atlassian.net/browse/PIMS-357?atlOrigin=eyJpIjoiNjQ1YjA1MjNiNmFkNDcxNTk4YjVkYTcxM2U2M2YyODEiLCJwIjoiaiJ9)Update cypress to 13.4.0
> PIMS-357 Update cypress to 13.4.0

- frontend/package.json
[PIMS-355: ](https://citz-imb.atlassian.net/browse/PIMS-355?atlOrigin=eyJpIjoiOTQ0MWViNzg3YjI1NGI3OTgzMmZiNDU3ODNlYTQ2ZGUiLCJwIjoiaiJ9)Update axios to 1.6.0
Tests passing. Container builds. No errors noticed when navigating site.
> PIMS-355 Update axios to 1.6.0

- frontend/package.json
[PIMS-356: ](https://citz-imb.atlassian.net/browse/PIMS-356?atlOrigin=eyJpIjoiYzBhM2NhN2MxOWFiNGQ5MWE1NDlhNDBmMWI4NjZhMDkiLCJwIjoiaiJ9)Update react-router-dom to 6.18.0
Tests passing. Container builds. Navigated site and didn't notice any errors.
> PIMS-356 Update react-router-dom to 6.18.0

- frontend/README.md
[PIMS-67](https://citz-imb.atlassian.net/browse/PIMS-67?atlOrigin=eyJpIjoiOTYwNGU3MmNhODYyNDc1ZjkyYzY0M2NlMWNjZTVmZmYiLCJwIjoiaiJ9)
Updating the README file for the frontend in light of the recent Vite changes.
> PIMS-67 Documentation Update

- frontend/package.json
Example: PIMS-393 Update react-icons from version `4.11.0` to `4.12.0`                                     
[PIMS-393](https://citz-imb.atlassian.net/browse/PIMS-393)
> PIMS-393: Update react-icons from version `4.11.0` to `4.12.0`

- frontend/package.json
[PIMS-395: ](https://citz-imb.atlassian.net/browse/PIMS-395) - Update @testing-library/react from version `14.0.0` to `14.1.0`
> PIMS-395: Update @testing-library/react from version `14.0.0` to `14.1.0`

- .gitignore
- express-api/constants/index.ts
- express-api/constants/networking.ts
- express-api/constants/switches.ts
- express-api/controllers/healthController.ts
- express-api/controllers/index.ts
- express-api/express.ts
- express-api/middleware/headerHandler.ts
- express-api/middleware/index.ts
- express-api/package.json
- express-api/routes/health-router.ts
- express-api/routes/index.ts
- express-api/server.ts
- express-api/tsconfig.json
[PIMS-381](https://citz-imb.atlassian.net/browse/PIMS-381?atlOrigin=eyJpIjoiOTIxNDEyODVhZDAyNGUxYTkzMmRjNzhjNjJkNjYyZTgiLCJwIjoiaiJ9)
Initial Express setup.
It uses the same `.env` in the root folder that the frontend uses.
Run using `npm run dev` in the `express-api` folder. 
We can change the name of this at a later date if desired.
Default port is 5000 when running.
You will likely have to change the port or stop the API container before running to prevent a port collision.
One route included. GET `localhost:5000/api/v2/health` to test it.
Please test it out and look through the files. I tried to separate everything as much as possible, but I would appreciate your opinion on what works for the team.
> - I have commented my code, …
> PIMS-381 Init Express API

- frontend/package.json
[PIMS-396: ](https://citz-imb.atlassian.net/browse/PIMS-396)
Update cypress from version `13.4.0` to `13.5.0`
> PIMS-396 Update cypress from version `13.4.0` to `13.5.0`

- frontend/package.json
[PIMS-397: ](https://citz-imb.atlassian.net/browse/PIMS-397)
Update prettier from version `3.0.3` to `3.1.0`
> PIMS-397 Update prettier from version `3.0.3` to `3.1.0`

- .github/helpers/deploy.sh
- openshift/templates/api-dc-template.yaml
- openshift/templates/app-dc-template.yaml
> quick fix, namespace should be a string

- frontend/Dockerfile.ocp
> Temp Comment added for testing pipeline

- backend/Dockerfile.ocp
> temp comment in backend dockerfile

- frontend/Dockerfile.ocp
> Pipeline test: removed temp comment from dockerfile FE

- frontend/Dockerfile.ocp
> Pipeline test: Update Dockerfile.ocp

- frontend/Dockerfile.ocp
> Removed temp test comment

- .github/workflows/DEV-App-image-deploy.yml
> Pipeline - health check reference fix

- frontend/package.json
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/BuildingForm.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/BuildingForm.test.tsx.snap
- frontend/src/features/mapSideBar/SidebarContents/subforms/IdentificationForm.tsx
- frontend/src/features/mapSideBar/containers/MapSideBarContainer.tsx
- frontend/src/features/properties/components/forms/subforms/LatLongForm.tsx
- frontend/src/features/properties/hooks/useParcelLayerData.tsx
[PIMS-288: ](https://citz-imb.atlassian.net/browse/PIMS-288?atlOrigin=eyJpIjoiZmViZmU3Yzc0MmY3NDJlZWIxMGU1Yzk1NmM4NWQ5ZDYiLCJwIjoiaiJ9)
Added a state variable to track if the pin was picked up. The lat and long should only update if that's the case. 
Shouldn't update unless edit mode is true. Might be a good idea to rework the land select form for parcels to act more like the one for buildings, where you have to pick up the pin in order to change fields with it.
> PIMS-288 Parcel Details Changing Unexpectedly

- .github/workflows/DEV-Api-image-deploy.yml
- .github/workflows/DEV-App-image-build.yml
- .github/workflows/DEV-App-image-deploy.yml
- .github/workflows/DEV-api-image-build.yml
Added a check to post image build info comment once.
Added feature to allow manual trigger to deploy specific image In Dev Environment
added Image Tags wiki page url in the build image comment.
> Dev ops/pipeline feedback

- .github/helpers/migrations.sh
- .github/helpers/update-wiki-table.py
- .github/workflows/DEV-Api-image-deploy.yml
- .github/workflows/DEV-api-image-build.yml
- docker-compose.prod.yml
Added support for Migration image build and deploy if change in Migration folder.
Added new Row for the Migration Image Tag on the Image tag wiki page
Added Timestamp with the Tag on the Image tag wiki page       
> Database migration flow added

- docker-compose.prod.yml
Typo in the reference of the migration docker file
> Bugfix: typo at migrations dockerfile

- backend/dal/Migrations/dummy.txt
> Dummy file to test migration Workflow

- .github/helpers/migrations.sh
quotes problem resulting in Migration image deploy failed.
> Quotes issue with while running migration deployement

- .github/workflows/DEV-Api-image-deploy.yml
DevOPs - Pipeline update
Bugfix: correct column to be updated in wiki page for image tags              
> update correct column on the image tags page

- backend/dal/Migrations/dummy.txt
This is a TEST PR to remove a dummy file added during testing of the DB migration flow   
> Remove dummy file for testing migratio pipeline

- frontend/src/components/maps/FindMorePropertiesButton.scss
- frontend/src/components/maps/FindMorePropertiesButton.tsx
[PIMS-377: ](https://citz-imb.atlassian.net/browse/PIMS-377)
Updating Surplus Properties Overlay to not overlap map controls when open. 
> PIMS-377 surplus properties style update

- frontend/package.json
PIMS-498:   Update react-router-dom from version `6.18.0` to `6.20.0`                                  
[PIMS-498](https://citz-imb.atlassian.net/browse/PIMS-498)
> PIMS-498: Update react-router-dom from version `6.18.0` to `6.20.0`

- frontend/package.json
[PIMS-497: ](https://citz-imb.atlassian.net/browse/PIMS-497)
react-datepicker from version `4.21.0` to `4.23.0`
> PIMS-497: Update react-datepicker from version `4.21.0` to `4.23.0`

- .vscode/settings.json
- backend/api/Areas/Tools/Helpers/ImportPropertiesHelper.cs
- backend/api/Areas/Tools/Models/Import/ImportPropertyModel.cs
- frontend/src/features/properties/upload/Instructions.tsx
- frontend/src/utils/csvToPropertyModel.ts
[PIMS-509](https://citz-imb.atlassian.net/browse/PIMS-509?atlOrigin=eyJpIjoiZmZlZmFlOGE3OTc2NGFmMWIyMjdmNTgzOTkxODYxMTMiLCJwIjoiaiJ9)
- The Location field in the upload is no longer required if a valid Regional District column is provided. 
- IF the Location field is blank or invalid, it will default to use the Regional District for the Administrative Area/City.
Giving the API an empty string resulted in an error where "name" was null. I think this was throw from the Add and Update methods of BuildingService and ParcelService. I added a default of <blank> when no value is given in the CSV. This give the expected error from the API when it can't find a Location called <blank>.
I also added a connection settings for local database connections. I was getting tired of adding it manually all …
> PIMS-509 Property Upload - Use Regional District if Location Invalid

- .github/helpers/migrations.sh
- .github/workflows/DEV-Api-image-deploy.yml
- .github/workflows/PROD-Api-image-deploy.yml
- .github/workflows/TEST-Api-image-deploy.yml
[PIMS-512: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-512)
FIXED: Wrong reference for the migration provided in the workflow file
Bug when manually running the Pipelines
> Bug fix, migration step wrong tag issue

- backend/dal.keycloak/Partials/PimsKeycloakUserService.cs
- backend/dal/Services/Admin/Concrete/UserService.cs
[PIMS-530:](https://citz-imb.atlassian.net/browse/PIMS-530) Error when trying to approve access requests
This ticket is part of https://github.com/bcgov/PIMS/pull/1970 to add more debugging and also adding await to GetUsersPreferredUsername call.
> PIMS-530: Error when trying to approve access requests

- frontend/src/features/splReports/columns.tsx
- frontend/src/features/splReports/components/ReportForm.tsx
PIMS-91:  Click to open project from reports page                                 
[PIMS-91](https://citz-imb.atlassian.net/browse/PIMS-91)
> PIMS-91: Click to open project from reports page

- .github/labeler.yaml
Adding an Express label to the labeler to help organize Express-related PRs.
> Update labeler.yaml to Include Express Label

- .codeclimate.yml
- .github/workflows/api-jest-coverage.yaml
- express-api/jest.config.ts
[PIMS-387](https://citz-imb.atlassian.net/browse/PIMS-387?atlOrigin=eyJpIjoiYThlMzQ5NGE0NTA3NGY3NWI5NWM2ZjdmNjgwNjNjMjQiLCJwIjoiaiJ9)
Adds a testing workflow to the Express API.
Sends coverage to CodeClimate for coverage comments.
> PIMS-387 Express API Testing Workflow

- docker-compose.yml
- express-api/.dockerignore
- express-api/Dockerfile
**PIMS-390:** Dockerize Express API      
**Changes:**
Created Dockerfile that starts production-ready version of API.
Amended the docker-compose file to start the express-api container.
**Testing:**
Run `docker compose up express-api` to get the container up and running.
[PIMS-390](https://citz-imb.atlassian.net/browse/PIMS-390)
> PIMS-390: Dockerize Express API

- .github/CODEOWNERS
Adding Graham to the CODEOWNERS file so he can review PRs.
> Add Graham to CODEOWNERS

- frontend/package.json
[PIMS-612](https://citz-imb.atlassian.net/browse/PIMS-612)
Update react-router-dom
> PIMS-612 Update react-router-dom

- frontend/package.json
PIMS-611: Update react-datepicker from version `4.24.0` to `4.25.0`                                    
[PIMS-611](https://citz-imb.atlassian.net/browse/PIMS-611)
> PIMS-611: Update react-datepicker from version `4.24.0` to `4.25.0`

- frontend/package.json
[PIMS-640: ](https://citz-imb.atlassian.net/browse/PIMS-640)
Update Moment from version `2.29.4` to `2.30.1`
> PIMS-638 Update Moment from version `2.29.4` to `2.30.1`

- frontend/package.json
[PIMS-639: ](https://citz-imb.atlassian.net/browse/PIMS-639)
Update classnames from version `2.3.2` to `2.5.1`
> PIMS-639 Update classnames

- backend/ches/Pims.Ches.csproj
- backend/core/Pims.Core.csproj
- backend/ltsa/Pims.Ltsa.csproj
- backend/notifications/Pims.Notifications.csproj
- tools/converters/excel/Pims.Tools.Converters.ExcelConverter.csproj
- tools/core/Pims.Tools.Core.csproj
[PIMS-666](https://citz-imb.atlassian.net/browse/PIMS-666?atlOrigin=eyJpIjoiZjBkOGUzMzYxZGE0NGMyYmEwNzY4MzA1YzFlODVlZGEiLCJwIjoiaiJ9)
Updates the IdentityModel.Tokens.Jwt package in the backend and tools to version 6.34.0.
This addresses the vulnerability raised by Dependabot. 
> PIMS-666 Update IdentityModel.Tokens.Jwt to 6.34.0

- express-api/src/controllers/index.ts
- express-api/src/controllers/tools/toolsController.ts
- express-api/src/controllers/tools/toolsSchema.ts
- express-api/src/express.ts
- express-api/src/routes/index.ts
- express-api/src/routes/toolsRouter.ts
- express-api/src/swagger/swagger-output.json
- express-api/tests/integration/tools/tools.test.ts
- express-api/tests/unit/controllers/tools/toolsController.test.ts
[PIMS-416](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-416)
* Added controllers, routes, tests stubs for the 3 different tools.
* This one was pretty straightforward, only minor comments. Did not omit any routes.
> PIMS-416: Tools stubs

- express-api/src/controllers/index.ts
- express-api/src/controllers/reports/reportsController.ts
- express-api/src/express.ts
- express-api/src/routes/index.ts
- express-api/src/routes/reportsRouter.ts
- express-api/src/swagger/swagger-output.json
- express-api/tests/integration/reports/reports.test.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/controllers/reports/reportsController.test.ts
[PIMS-424](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-424)
* Added routes, controllers, tests for reports.
* Left some comments in the router again, but I will also post these to the central issue.
> PIMS-424: Reports stubs

- backend/dal/Pims.Dal.csproj
[PIMS-689: ](https://citz-imb.atlassian.net/browse/PIMS-689) - Update System.Data.SqlClient from 4.8.5 to 4.8.6 
Updated the SqlClient version in .NET for the Dal project, all backend tests are working, no db connection issues found when testing the map, inventory page, and updating a user. 
> PIMS-689: Update System.Data.SqlClient from 4.8.5 to 4.8.6 

- frontend/package.json
[PIMS-677: ](https://citz-imb.atlassian.net/browse/PIMS-677)
Update react-icons from version `4.12.0` to `5.0.1`
> Update react-icons from version `4.12.0` to `5.0.1`

- frontend/package.json
[PIMS-678: ](https://citz-imb.atlassian.net/browse/PIMS-678) - Update react-resize-detector from version `9.1.0` to `10.0.1`
Updated the react-resize-detector package version, no issues found when testing the map zooming in, all the resizing seems to work fine.
> PIMS-678: Update react-resize-detector from version `9.1.0` to `10.0.1`

- frontend/package.json
- frontend/src/features/projects/list/SPLProjectListView.tsx
PIMS-676: Update prettier from version `3.1.0` to `3.2.4`                                   
[PIMS-676 ](https://citz-imb.atlassian.net/browse/PIMS-676)
> PIMS-676: Update prettier from version `3.1.0` to `3.2.4`

- frontend/src/features/mapSideBar/SidebarContents/SubmitPropertySelector.test.tsx
- frontend/src/features/mapSideBar/SidebarContents/SubmitPropertySelector.tsx
- frontend/src/features/mapSideBar/SidebarContents/__snapshots__/SubmitPropertySelector.test.tsx.snap
[PIMS-722](https://citz-imb.atlassian.net/browse/PIMS-722?atlOrigin=eyJpIjoiNjNmMGJmNWUyZGE4NGM3Yjg1NDFmNTIzNmQ3NTFlODAiLCJwIjoiaiJ9)
Temporary measure to hide the option to create subdivisions when submitting new properties.
> PIMS-722-Hide-Subdivision-Feature

- frontend/package.json
[PIMS-1275](https://citz-imb.atlassian.net/browse/PIMS-1275?atlOrigin=eyJpIjoiODUzZDdiYzgyMmU3NDA2NDgwMzJmODU2OWFjODdiN2MiLCJwIjoiaiJ9)
Original ticket was for version 5.1.0. Noticed that 6.1.0 came out last week, so bumped it up to that.
Manual operation of date picker seems ok. Tests passing. 
> PIMS-1275 Update react-datepicker to 6.1.0 (frontend)

- frontend/package.json
[PIMS-1298](https://citz-imb.atlassian.net/browse/PIMS-1298?atlOrigin=eyJpIjoiOGMzOWJlMjMwODcwNDhkODg5OTM3MGU5YWJlMzY3ZWMiLCJwIjoiaiJ9)
No issues noted. Routes appear to work as expected.
> PIMS-1298 Update react-router-dom to 6.22.0 (frontend)

- .github/helpers/jira-api/README.md
[PIMS-90: ](https://citz-imb.atlassian.net/browse/PIMS-90)
No changes to actual workflow or use. Just updating documentation.
> PIMS-90 Update README.md for jira_api

- docker-compose.yml
- react-app/nginx.conf
[PIMS-1309: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1309)
Updated Nginx configuration for support for the Swagger
Bugfix for the container name dependency
> PIMS-1309 Bugfix : Swagger Proxy and docker-compose update

- express-api/src/express.ts
- express-api/src/swagger/swagger-output.json
- express-api/tests/integration/admin/accessRequests/accessRequests.test.ts
- express-api/tests/integration/admin/administrativeAreas/administrativeAreas.test.ts
- express-api/tests/integration/admin/agencies/agencies.test.ts
- express-api/tests/integration/admin/claims/claims.test.ts
- express-api/tests/integration/admin/roles/roles.test.ts
- express-api/tests/integration/admin/users/users.test.ts
- express-api/tests/integration/express/express.test.ts
- express-api/tests/integration/health/getHealth.test.ts
- express-api/tests/integration/lookup/lookup.test.ts
- express-api/tests/integration/ltsa/getLtsa.test.ts
- express-api/tests/integration/middleware/headerHandler.test.ts
- express-api/tests/integration/parcels/parcels.test.ts
- express-api/tests/integration/projects/projects.test.ts
- express-api/tests/integration/properties/properties.test.ts
- express-api/tests/integration/tools/tools.test.ts
- express-api/tests/integration/users/users.test.ts
- openshift/templates/api-v2-dc-template.yaml
- react-app/nginx.conf
- react-app/vite.config.ts
> nginx configuration update

- express-api/src/appDataSource.ts
> run migrations on start

- express-api/src/appDataSource.ts
> Migration test

- express-api/Dockerfile
- express-api/src/appDataSource.ts
- express-api/src/server.ts
[PIMS-1350](https://citz-imb.atlassian.net/browse/PIMS-1350?atlOrigin=eyJpIjoiOWEzNzRhNzY3NzkyNDgzZGJhY2NiMDJlM2RiNTdkMGYiLCJwIjoiaiJ9)
Need migrations to run when the API starts in OpenShift.
- Had to manually copy the SQL files in the Dockerfile. Apparently Typescript doesn't include these during build.
- Removed Seeds folder from migrations options in appDataSource.ts
- Fixed issue where error handler would throw error if server or database connection as not initialized, resulting in infinite loops.
- Fixed issue where Dockerfile could not find curl when trying to install package.
Express API should be stopped before testing.
1. Clear your database by dropping and recreating the schema.
2. Build the container for the API
a. `docker-compose up -d --build pims-api-v2`
3. Check logs in …
> PIMS-1350 Migrations Run in OC

- express-api/src/services/parcels/parcelSchema.ts
- express-api/src/services/parcels/parcelServices.ts
- express-api/tests/unit/services/parcels/parcelsService.test.ts
[PIMS-1336](https://citz-imb.atlassian.net/browse/PIMS-1336?atlOrigin=eyJpIjoiZmMzMWI3YzMxNmY4NGE1Njk5OWEzNjU3YWJmYWUwODQiLCJwIjoiaiJ9)
Adds a function to the parcels service that retrieves a list of parcels based on the provided filter. 
- Added zod schema for the parcels filter
- Added function & tests for the getParcels operation
Easiest thing to do is to use the function in the `/health` endpoint controller. 
Try passing it different filters and get the results back. 
Make sure your database is populated with parcels, or the results will be empty every time.
> - I have tested my changes to the …
> PIMS-1336 Parcels Service: getParcels

- .github/workflows/DEV-Api-V2-image-build.yml
- .github/workflows/DEV-App-V2-image-build.yml
- openshift/templates/api-v2-dc-template.yaml
- openshift/templates/app-v2-dc-template.yaml
[DEVOP-279: ](https://citz-imb.atlassian.net/browse/DEVOP-279)
Update in the GHA workflow to login to Artifactory and push.
Update in Openshift Template for the referencing the Artifactory
> Artifactory Integration

- .github/workflows/DEV-Api-V2-image-build.yml
Fixed typo in the Express api image build and push
> Fix image build and push typo

- express-api/package.json
- react-app/package.json
[PIMS-1398](https://citz-imb.atlassian.net/browse/PIMS-1398?atlOrigin=eyJpIjoiNjYxZDJhNjgzN2JmNGRiYThjYjM3YzI1NzJmMTEwYWUiLCJwIjoiaiJ9)
Changes packages over to npm versions.
> PIMS-1398 Keycloak Packages Update

- openshift/templates/api-v2-dc-template.yaml
[DevOps-264: ](https://citz-imb.atlassian.net/browse/DEVOP-264)
Add Vault integration in the OC template: Secrets will be pulled from the vault storage from now on.
> Vault Implementation into Pipeline

- openshift/templates/api-v2-dc-template.yaml
- openshift/templates/app-v2-dc-template.yaml
> Changing Application Group For V2 API and APP

- openshift/templates/app-dc-template.yaml
Add BCA_LAYER_URL environment variable in the app dc template.
> Add BCA_LAYER_URL env variable to dc template

- express-api/src/typeorm/Migrations/1710351144794-EvaluationFiscalKeys.ts
[PIMS-1431](https://citz-imb.atlassian.net/browse/PIMS-1431?atlOrigin=eyJpIjoiMzY2ODJiZjAwMzUyNGZiMGI0YjRmMjY0OWNiNjhiNDIiLCJwIjoiaiJ9)
Evaluation and Fiscal keys are populated from 1 to 3, but original PIMS started at 0. 
Need to adjust the keys to allow for easier ETL.
> PIMS-1431 Evaluation/Fiscal Key Migration

- express-api/src/controllers/parcels/parcelsController.ts
- express-api/src/routes/parcelsRouter.ts
- express-api/src/services/parcels/parcelSchema.ts
- express-api/src/services/parcels/parcelServices.ts
- express-api/tests/unit/controllers/parcels/parcelsController.test.ts
- express-api/tests/unit/services/parcels/parcelsService.test.ts
[PIMS-1434 ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1434)
Implements endpoints for managing parcels. I left some endpoints that I am not sure we need for moving forward with the current MVP goal unimplemented.
I also made some small adjustments to the services behavior:
* Services will try to obtain a unique row by primary key instead of by PID, which I feel is appropriate given PID has no unique constraint. There is still a function to get a single row by PID though.
* Removed some error throwing from the services where it did not seem appropriate to me and instead let the controllers handle it.
> - I have made corresponding changes to the documentation where …
> PIMS-1434: Parcel Controller

- .github/helpers/jira-api/README.md
[PIMS-1250: ](https://citz-imb.atlassian.net/browse/PIMS-1250)
Now that the service account is only accessible through outlook online documentation should reflect that. 
> PIMS-1250 update summer to outlook online

- tools/dbeaver/tasks.json
Adds a dbeaver task that will take data from Prod MS SQL Server and populate your local Postgres database.
> Prod-to-Local ETL Task

- express-api/src/services/agencies/agencySchema.ts
- express-api/tests/unit/controllers/agencies/agencyController.test.ts
- react-app/src/hooks/api/useAgencyApi.ts
- react-app/src/hooks/api/useGroupedAgenciesApi.ts
[PIMS-1353](https://citz-imb.atlassian.net/browse/PIMS-1353?atlOrigin=eyJpIjoiYjc3NTlkYjRjZjQxNGFmNzgwZDQyODc2MGI3ZWYwZWQiLCJwIjoiaiJ9)
- Added hook option to only get non-disabled agencies
- Tried using just this to solve issue, but then it broke the useGroupedAgenciesApi hook.
- Updated filter schema (original one was expecting all fields)
- Added check to agency grouping function to exclude disabled agencies
> PIMS-1353 No Disabled Agencies

- express-api/src/controllers/agencies/agenciesController.ts
- express-api/src/services/agencies/agencySchema.ts
- express-api/tests/unit/controllers/agencies/agencyController.test.ts
When user was not an admin or had no roles, the schema was removing the parent id, making the grouping fail for the dropdown.
> Bug Fix: Expand Agency Public Schema

- express-api/src/middleware/keycloak/keycloakOptions.ts
- express-api/tests/unit/middleware/keycloak/keycloakOptions.test.ts
[PIMS-1441](https://citz-imb.atlassian.net/browse/PIMS-1441?atlOrigin=eyJpIjoiZjdhOGRhZGViNWM1NDJmZTkwZDIyZThlZDA1MWMxYWQiLCJwIjoiaiJ9)
- Added update for user's last login date if they already exist in database
- Specific warning error now for failing to sync keycloak user after login
> PIMS-1441 Update LastLogin

- react-app/package.json
[PIMS-1450: ](https://citz-imb.atlassian.net/browse/PIMS-1450)
Updated the following NPM dependencies:
- @babel/preset-react@7.24.1 
- @typescript-eslint/eslint-plugin@7.4.0 
- @typescript-eslint/parser@7.4.0 
- vite@5.2.6
holding off on the major updates as they seem to cause issues. 
> PIMS-1450 react-app updates

- express-api/package.json
[PIMS-1451: ](https://citz-imb.atlassian.net/browse/PIMS-1451)
Updates to express-api npm dependencies:
- express@4.19.2
- winston@3.13.0
- @typescript-eslint/eslint-plugin@7.4.0
- @typescript-eslint/parser@7.4.0
> PIMS-1451-express-api-updates

- tools/keycloakRoleMapping/src/roleMappingConversion.ts
Found one additional role that needed to be mapped when moving Keycloak roles in TEST. 
> Update Role Mapper

- express-api/src/controllers/tools/toolsController.ts
- express-api/src/services/geocoder/geocoderService.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/controllers/tools/toolsController.test.ts
- express-api/tests/unit/services/geocoder/geocoderService.test.ts
[PIMS-1507](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1507)
Implemented geocoder controller and geocoder controller tests.
> PIMS-1507: Geocoder Controller

- frontend/package.json
[PIMS-1449: ](https://citz-imb.atlassian.net/browse/PIMS-1449)
Updated the following packages: 
- typescript
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
> PIMS-1449 frontend updates

- express-api/src/controllers/users/usersController.ts
- express-api/src/services/users/usersServices.ts
- express-api/src/utilities/authorizationCheck.ts
- express-api/src/utilities/authorizationChecks.ts
- express-api/tests/unit/controllers/users/usersController.test.ts
- express-api/tests/unit/utilities/authorizationChecks.test.ts
[PIMS-1438: ](https://citz-imb.atlassian.net/browse/PIMS-1438)
Creating some functions to check for various use roles and statuses.
> PIMS-1438: Checking for User Roles

- .github/helpers/deploy.sh
- .github/workflows/DEV-Api-V2-image-build.yml
- .github/workflows/DEV-App-V2-image-build.yml
- .github/workflows/PROD-Api-V2-image-deploy.yml
- openshift/templates/api-v2-dc-template.yaml
- openshift/templates/app-v2-dc-template.yaml
DEVOPS - 342
[DEVOPS-342: ](https://apps.itsm.gov.bc.ca/jira/browse/DEVOPS-342)
Rollback to Image Stream, AS arifactory has a storage limit with no automatic pruning. Changes:
Updated the github Actions to push image to image stream
Updated deployment config to pull from image stream
add vault environment variable for the PROD v2.
> Devops 342 image registry update

- .github/helpers/deploy.sh
[DEVOPS-342: ](https://apps.itsm.gov.bc.ca/jira/browse/DEVOPS-342)
if statement fix
> add missing close statement

- react-app/src/components/map/ParcelMap.tsx
- react-app/src/components/property/PropertyDetail.tsx
[PIMS-1648: ](https://citz-imb.atlassian.net/browse/PIMS-1648)
Displaying the small map at the bottom of the property details form when not in "edit" mode.
> PIMS-1648: Small map on Parcel and Building details forms

- react-app/src/components/adminAreas/AdministrativeAreaDetail.tsx
- react-app/src/components/agencies/AgencyDetails.tsx
- react-app/src/components/display/DataCard.tsx
- react-app/src/components/projects/ProjectDetail.tsx
- react-app/src/components/property/PropertyDetail.tsx
- react-app/src/components/users/UserDetail.tsx
[PIMS-1676 ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1676)
* Added skeleton component and loading logic to DataCard, since this is definitely the component that needs it the most.
* Added loading prop wired to the relevant data loader hook in each of the main data cards.
Testing this is kind of annoying since it relies on the async calls being delayed, but you should be able to see it working pretty easily moving between tables/detail pages.
> PIMS-1676: Skeleton Loading

- react-app/package.json
- react-app/src/components/adminAreas/AddAdministrativeArea.tsx
- react-app/src/components/adminAreas/AdministrativeAreaDetail.tsx
- react-app/src/components/agencies/AddAgency.tsx
- react-app/src/components/agencies/AgencyDetails.tsx
- react-app/src/components/dialog/ConfirmDialog.tsx
- react-app/src/components/dialog/DualActionButtons.tsx
- react-app/src/components/projects/AddProject.tsx
- react-app/src/components/projects/ProjectDialog.tsx
- react-app/src/components/property/AddProperty.tsx
- react-app/src/components/property/PropertyDialog.tsx
- react-app/src/components/users/UserDetail.tsx
- react-app/src/hooks/api/useAdministrativeAreaApi.ts
- react-app/src/hooks/api/useAgencyApi.ts
- react-app/src/hooks/api/useBuildingsApi.ts
- react-app/src/hooks/api/useParcelsApi.ts
- react-app/src/hooks/api/useProjectsApi.ts
- react-app/src/hooks/api/useUsersApi.ts
- react-app/src/hooks/useDataLoader.ts
- react-app/src/hooks/useDataSubmitter.ts
- react-app/src/hooks/usePimsUser.ts
[PIMS-1700](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1700)
* This adds a useDataSubmitter hook that is basically just a wrapper around useDataLoader with different verbs in the return object and automatic calling of the snackbar context to give feedback about submissions.
* Modified all the places where submission api calls were triggered to use this new hook and modified their return types to yield the entire response object. 
* Replaced all submission <Button>s with the MUI lab <LoadingButton> component for use with the "submitting" property of the useDataSubmitter hook. This gives additional feedback to users while their request is in progress after submitting the form and before getting the snackbar popup. It also automatically disables the button during this time, preventing any …
> PIMS-1700: Submit Handler

- express-api/src/services/notifications/notificationServices.ts
- express-api/src/services/projects/projectsServices.ts
- express-api/tests/unit/services/notifications/notificationServices.test.ts
- express-api/tests/unit/services/projects/projectsServices.test.ts
[PIMS-1701 ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1701)
Made entity managing statements inside of transaction blocks all use the transactional context queryRunner instead of the global one, thus ensuring that the operations rollback and commit as expected.
> PIMS-1701: Fixing incorrect transaction behavior 

- express-api/src/services/buildings/buildingServices.ts
[PIMS-1568](https://citz-imb.atlassian.net/browse/PIMS-1568?atlOrigin=eyJpIjoiYjBiZWYzNDdkODFlNDJkMjk5NGFkNjJiNDVlZDUwYTAiLCJwIjoiaiJ9)
Not sure if we still need this column, but made a change that will update the JSON stored there, not just overwrite the whole object.
> PIMS-1568 Leased Land Metadata

- react-app/src/components/property/PropertyTable.tsx
- react-app/src/components/users/UserDetail.tsx
- react-app/src/components/users/UsersTable.tsx
- react-app/src/utilities/formatters.tsx
[PIMS-1599](https://citz-imb.atlassian.net/browse/PIMS-1599?atlOrigin=eyJpIjoiM2Q4MzZmMDU1Yjc0NGNjOTg3ODZkOWU1NDg5NzFiMWQiLCJwIjoiaiJ9)
[PIMS-1603](https://citz-imb.atlassian.net/browse/PIMS-1603?atlOrigin=eyJpIjoiYTQ5ZmUzMDE5M2VkNDU3Mjg1MjYzZmM1ODY0YjMxZWYiLCJwIjoiaiJ9)
- Make Classification a searchable field in properties
- Make PID a searchable field with and without hyphens
- Fix preset filter options so they work again. Also changed Parcel to Land to match the value on the properties
- Fixed an issue when updating a user and their role wasn't being updated
- Updated the preset select for users table, removing Pending and adding Denied.
- Update the statusChipFormatter so OnHold => On Hold
> - I have commented my code, particularly in …
> PIMS-1603 Column Filtering Fixes & PIMS-1599 Status Chip

- express-api/src/controllers/properties/propertiesController.ts
- react-app/src/components/projects/AgencyResponseSearchTable.tsx
- react-app/src/components/projects/DisposalPropertiesSearchTable.tsx
- react-app/src/components/projects/DisposalPropertiesSimpleTable.tsx
- react-app/src/components/property/PropertyAssessedValueTable.tsx
- react-app/src/components/property/PropertyNetValueTable.tsx
- react-app/src/components/table/DataTable.tsx
[PIMS-1598 ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1598)
DataGrid will now show pointer cursor and hover highlight when over a row. Made sure to disable this feature on the tables embedded in datacards and dialogs.
> PIMS-1598: Data Grid Hover

- openshift/templates/api-v2-dc-template.yaml
Updates deployment config template with new-ish Vault envs.
Regarding CHES, CHES_EMAIL_ENABLED is currently set to `false`, and I set CHES_OVERRIDE_TO to my own email just in case someone enables it without adding the override.
> Vault ENVs - Template Update

- express-api/src/services/ches/chesServices.ts
- express-api/src/services/notifications/notificationServices.ts
Added more explicit handling for the expected case of a null email response from ches when email is not enabled.
> Handle null email response

- react-app/src/constants/jsxSnippets.tsx
- react-app/src/pages/AccessRequest.tsx
[PIMS-1619](https://citz-imb.atlassian.net/browse/PIMS-1619?atlOrigin=eyJpIjoiMDc3NzQ3ZjAwNDkyNDRlOGE2Mzk1OTVmNjIwZjA2YjkiLCJwIjoiaiJ9)
- Reworked the content selection for the Access-Request page
- Added a blurb for Disabled/Denied users
- Didn't really want to say "Your account is denied or disabled" because users might not be flattered by that language. Settled on Inactive.
Use this SQL to affect your status (assuming your last name is unique):
``` sql
update "user" set status = 'Disabled' where last_name = 'your last name here';
```
> - My …
> PIMS-1619 Status Pages for Denied/Disabled Users

- react-app/src/components/users/UserDetail.tsx
[PIMS-1546: ](https://citz-imb.atlassian.net/browse/PIMS-1546)
Added line to get users keycloak role, if the user is an admin the edit button is enabled, if the user is not an admin the edit button is disabled. 
> PIMS-1546 Disable Edit Button on User Detail Page for Non-Admins

- .github/workflows/DEV-Api-V2-image-deploy.yml
- .github/workflows/DEV-App-V2-image-deploy.yml
[DEVOP-341: ](https://apps.itsm.gov.bc.ca/jira/browse/DEVOP-341)
This will update the CD,
1. PR merges will update the TAG on the gitOps repo
2. Argo CD listens to the gitOPs repo and update the deployment in Openshift 
> Argo CD deployment pattern

- express-api/src/services/ltsa/interfaces/ILtsaOrder.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/controllers/ltsa/ltsaController.test.ts
- express-api/tests/unit/services/ltsa/ltsaService.test.ts
Trying to solve the issue with some of these tests working intermittently. Mocked the implementation of the ltsaService so it's not calling the LTSA on every test run. Updated the ILtsaOrder interface in the backend to add missing parameters from the response.
> Update LTSA Tests

- express-api/src/services/projects/projectsServices.ts
- express-api/src/typeorm/Entities/ProjectNote.ts
- express-api/src/typeorm/Migrations/1716854270095-ProjectNoteUniqueIndex.ts
- express-api/tests/testUtils/factories.ts
- express-api/tests/unit/services/projects/projectsServices.test.ts
- react-app/src/components/projects/ProjectDetail.tsx
[PIMS-1708](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1708)
* Notes are now included when getting a project by ID
* There's an additional handler for updating project notes while updating a project. Notes are only upserted and not deleted (I figure notes will just update to an empty string rather than have the row itself deleted)
* Added a migration that makes the index on the column pair (project_id, note_type) unique to make the conflict condition in the upsert possible. 
> PIMS-1708: Notes Backend

- react-app/src/components/layout/Header.tsx
[PIMS-1717](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1717)
Changed Link components out for RouterLink components and Typography. Try clicking the various header links and see if the page just re-renders now instead of refreshing. Should feel a lot smoother. 
> PIMS-1717: Avoid refreshing the page on header navigation

- react-app/src/App.tsx
- react-app/src/components/map/InventoryLayer.tsx
[PIMS-1652](https://citz-imb.atlassian.net/browse/PIMS-1652)
[PIMS-1739](https://citz-imb.atlassian.net/browse/PIMS-1739)
Just starting the rework for the map area. This does not include any new additions, it only removes some unneeded elements from the first iteration and makes some small adjustments.
I haven't removed the now-unused spiderfier or map marker code. Will do that at a later time once we're sure we don't need them.
- Removed spidering behaviour and old marker designs
- Adjusted clusters to look like design images
- Updated clustering click behaviour
- Added map as reroute for the '/' route. Should now appear in place of the home page when user is authenticated and active.
> - I have commented my code, particularly in …
> PIMS-1652 Clusters Rework

- express-api/src/services/properties/propertiesServices.ts
- react-app/src/App.tsx
- react-app/src/components/layout/BaseLayout.tsx
- react-app/src/components/layout/Header.tsx
- react-app/src/components/map/InventoryLayer.tsx
- react-app/src/components/map/ParcelMap.tsx
- react-app/src/components/map/propertyRow/PropertyRow.tsx
- react-app/src/components/map/sidebar/MapSidebar.tsx
- react-app/src/components/property/ClassificationIcon.tsx
- react-app/src/components/property/PropertyDetail.tsx
- react-app/src/components/property/PropertyForms.tsx
- react-app/src/hooks/api/usePropertiesApi.ts
- react-app/src/utilities/formatters.tsx
[PIMS-1745](https://citz-imb.atlassian.net/browse/PIMS-1745?atlOrigin=eyJpIjoiMmY5N2QyOGVlNzlkNGMwM2E2OWY3NjYzN2VmNWE1ZjYiLCJwIjoiaiJ9)
Still adding some documentation.
- Adds a sidebar to the map that displays all the properties that are in the bounds of the map.
- Promotes the properties call out of the old InventoryLayer to do this.
- Fixed some CSS issues where the map was underneath the Header
- Visit home page. Scroll about. Use sidebar controls.
**Does not include moving the filter controls. I just hid them for now.**
> - My changes …
> PIMS-1745 Map Sidebar Property List

- express-api/src/controllers/properties/mapFilterSchema.ts
- express-api/src/controllers/properties/propertiesController.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/src/typeorm/Entities/views/MapPropertiesView.ts
- express-api/src/typeorm/Migrations/1717797668919-ExpandMapPropertiesView.ts
- react-app/src/components/map/ParcelMap.tsx
- react-app/src/components/map/controls/FilterControl.tsx
- react-app/src/components/map/propertyRow/PropertyRow.tsx
- react-app/src/components/map/sidebar/MapSidebar.tsx
- react-app/src/components/property/ClassificationIcon.tsx
- react-app/src/hooks/api/usePropertiesApi.ts
[PIMS-1753](https://citz-imb.atlassian.net/browse/PIMS-1753?atlOrigin=eyJpIjoiMWE3N2FiODRmOWRmNGE0MWFlZjlkMjU1ZmFlZWMyODAiLCJwIjoiaiJ9)
- Updated database view that gets properties for the map. Includes Regional District now
- Added Regional District to the filter fields
- Moved the Inventory Filter to extend from the map sidebar
- Clicking anywhere on a property row in the sidebar now opens that property. Was previously just the title or icon. Aiden's request.
> PIMS-1753 Sidebar Filter

- react-app/src/components/property/PropertyTable.tsx
[PIMS-1595](https://citz-imb.atlassian.net/browse/PIMS-1595?atlOrigin=eyJpIjoiYTUyMmQ0M2VhNmFlNGJiYmEyOThhNzhjODEwYjBkNmMiLCJwIjoiaiJ9)
Was requested during PO review that the Sensitive column be replaced with Land Area.
Also added view width parameters to some columns to keep the the table looking nice when resizing.
> PIMS-1595 Land Area in Table

- react-app/src/components/map/sidebar/MapSidebar.tsx
When navigating away from the map, it would try and remove the event listeners, but then the map was already null, resulting in an error. 
Wrapped that portion with a check to see that map.current is still defined.
> Map Bug Fix

- .github/ISSUE_TEMPLATE/bug_report.yml
Testing out the use of GitHub forms as an issue submitting option.
There doesn't appear to be a way to preview this that I can tell.
> Add Issue Template

- react-app/src/components/layout/BaseLayout.tsx
- react-app/src/components/layout/Header.tsx
[PIMS-1797: ](https://citz-imb.atlassian.net/browse/PIMS-1797)
- Removed an overflow style from baselayout which prevented the sidebar links from scrolling to each section.
- Removing this style seems like it's not affecting anything on the map or other pages.
> PIMS-1797: Sidebar links not working

- .github/workflows/DEV-Api-V2-image-deploy.yml
- .github/workflows/DEV-App-V2-image-deploy.yml
Bugfix for deploy GHA fail.
Update::Pull 'main' before pushing the new tag 
> Add pull command in dev deployment GHA

- react-app/src/components/map/clusterPopup/ClusterPopup.tsx
- react-app/src/components/map/propertyRow/PropertyRow.tsx
- react-app/src/components/map/sidebar/MapSidebar.tsx
[PIMS-1798](https://citz-imb.atlassian.net/browse/PIMS-1798?atlOrigin=eyJpIjoiZDhjNTg2ODEwMjU3NGY0NzhiMGM4ZTMyOWUxMTJjM2IiLCJwIjoiaiJ9)
- Address now the first line under the PID in PropertyRow component. See this on the map in the sidebar or cluster popup.
> PIMS-1798 Add Address to Property Row

- express-api/src/services/properties/propertiesServices.ts
- express-api/src/utilities/helperFunctions.ts
- react-app/src/components/property/PropertyTable.tsx
- react-app/src/components/table/DataTable.tsx
- react-app/src/hooks/api/usePropertiesApi.ts
- react-app/src/pages/ActiveInventory.tsx
[PIMS-1804](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1804)
* Added the api hook for server side table pagination for the active inventory page.
* Improved filtering handling for PID/PIN case so that you can search with padded zeroes and hyphens and still have it work out.
> PIMS-1804: Server side pagination for active inventory

- react-app/src/components/map/parcelPopup/ParcelPopup.tsx
[PIMS-1751](https://citz-imb.atlassian.net/browse/PIMS-1751?atlOrigin=eyJpIjoiY2NiZjE0NGQ3MzBjNDU3Y2EwY2IwNDhkNzBmMmUyNzUiLCJwIjoiaiJ9)
- CSS changes to some parts of the parcel layer popup. LTSA should now scroll instead of overflowing if there's both a PID and PIN on a parcel.
Example problem location:
> PIMS-1751 Popup Overflow

- react-app/src/assets/icons/SidebarLeft-Linear-White.svg
- react-app/src/components/map/sidebar/MapSidebar.tsx
[PIMS-1796: ](https://citz-imb.atlassian.net/browse/PIMS-1796)
Fix for the side bar icon not showing.
> PIMS-1796: Map Sidebar icon issue

- .github/config/dep-report.json5
- .github/helpers/create-npm-dep-report.js
- .github/helpers/parse-npm-deps.js
[PIMS-1824: ](https://citz-imb.atlassian.net/browse/PIMS-1824)
Attempting to remove all mentions of frontend from the dependency update reports such that no issues (on Github) or tickets (in Jira) are created for the frontend. 
> PIMS-1824 Remove frontend from NPM Dependency Updates

- react-app/src/components/map/controls/FilterControl.tsx
[PIMS-1820: ](https://citz-imb.atlassian.net/browse/PIMS-1820)
There was an error logging in as a general user related to the FilterControl.tsx component.
To test, change your user to a General user and try logging in.
> PIMS-1820: Fix for general user login

- .github/workflows/PROD-Api-V2-image-deploy.yml
- .github/workflows/PROD-App-V2-image-deploy.yml
- .github/workflows/TEST-Api-V2-image-deploy.yml
- .github/workflows/TEST-App-V2-image-deploy.yml
[PIMS-1677: ](https://citz-imb.atlassian.net/browse/PIMS-1677)
These changes will enable the argo CD workflows for TEST and PROD environment
> DevOps Argo cd workflows for TEST and PROD

- react-app/package.json
Pinning the versio of mui/lab so that it doesn't unexpectedly break things
> Pin @mui/lab version in package list

- react-app/src/components/ltsa/TitleOwnership.tsx
[PIMS-1833: ](https://citz-imb.atlassian.net/browse/PIMS-1833)
Used dateformatter on the dates we present on the parcel detail page. 
see comment for testing information
> PIMS-1833 Format LTSA Date on Parcel Detail Page

- express-api/Dockerfile
Fixed Permission issue when creating new upload directory
> Fix Dockerfile permissions for express-api

- express-api/src/controllers/properties/propertiesController.ts
- express-api/src/controllers/properties/propertiesSchema.ts
- express-api/src/routes/propertiesRouter.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/tests/unit/controllers/properties/propertiesController.test.ts
- express-api/tests/unit/services/properties/propertyServices.test.ts
[PIMS-1860: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1860)
Adds an endpoint that you can use to retrieve import results. Results are limited to rows created by the same user as the one making the request. 
> PIMS-1860: Import Result API

- react-app/src/components/layout/Header.tsx
[PIMS-1829: ](https://citz-imb.atlassian.net/browse/PIMS-1829)
Added a check for the users status before showing headers. 
Updated my own status on my local postgres table between "Active", "OnHold", "Denied", and "Disabled" to see if headers were still visible. 
> PIMS-1829 Only Active Users can see Headers

- react-app/src/components/projects/AddProject.tsx
[PIMS-1844: ](https://citz-imb.atlassian.net/browse/PIMS-1844)
Fix for saving the estimated market value when creating a new project.
> PIMS-1844: Estimated Market Value Not Saving

- react-app/src/components/layout/Header.tsx
- react-app/src/components/projects/AddProject.tsx
- react-app/src/components/table/DataTable.tsx
- react-app/src/pages/ErrorFallback.tsx
[PIMS-1845](https://citz-imb.atlassian.net/browse/PIMS-1845)
- Handled case where auth context was undefined in the header
- Model obj items should now be an empty array by default, not undefined
- Fixed issue with default value on AddProject (Market)
- ErrorFallback now removes the stored cookie as well from that path if it errors twice in a row.
> PIMS-1845 Bad Table Filters & Other Fixes

- express-api/tests/unit/services/agencies/agencyServices.test.ts
Removed some mock onces that were not actually being consumed
> Agency services test fix

- express-api/src/services/properties/propertiesServices.ts
- react-app/src/components/table/DataTable.tsx
[PIMS-1888: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1888)
> PIMS-1888 PID Search Formatting

- react-app/package.json
[PIMS-1876: ](https://citz-imb.atlassian.net/browse/PIMS-1876)
> PIMS-1876 react-app updates

- react-app/src/components/layout/Footer.test.tsx.snap
- react-app/src/components/layout/Footer.tsx
[PIMS-1917](https://citz-imb.atlassian.net/browse/PIMS-1917)
- Adds urls for links in the footer
- While logged out, click the links in the footer
> PIMS-1917 Footer Links

- express-api/src/typeorm/Migrations/1721928949171-PubliclySpellingChange.ts
PIMS-1894: Spelling Error (Publically)                                      
Created a new migration file to change the spelling from 'Publically' to 'Publicly".
[PIMS-1894](https://citz-imb.atlassian.net/browse/PIMS-1894)
> PIMS-1894: Spelling Error (Publically)

- react-app/src/components/map/parcelPopup/BCAssessmentDetails.tsx
[PIMS-1923 ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1923)
Corrected spelling error in string
> PIMS-1923: Juristiction -> Jurisdiction 

- react-app/src/components/projects/ProjectDetail.tsx
[PIMS-1931: ](https://citz-imb.atlassian.net/browse/PIMS-1931)
If the note is of type 2 only show to admins or auditors
> PIMS-1931 Make Private Notes More Private

- react-app/src/components/ltsa/LtsaChargeTable.tsx
[PIMS-1950](https://citz-imb.atlassian.net/browse/PIMS-1950)
- Adjusted the condition where the message appeared. It was not appearing if rows was falsey;
> PIMS-1950 No Charge Message

- react-app/src/components/form/AutocompleteFormField.tsx
- react-app/src/components/property/PropertyForms.tsx
[PIMS-1947](https://citz-imb.atlassian.net/browse/PIMS-1947?atlOrigin=eyJpIjoiN2YwNjRjNWZlZTQ4NGM1ODk1Y2QzYTE4ODFjNDA1ODgiLCJwIjoiaiJ9)
- Changed the typing of the AutocompleteFormField a bit to allow for some of the AutocompleteProps
- Added a simple message to the admin areas field if there are no matching options
> PIMS-1947 New Admin Areas

- react-app/src/components/projects/ProjectsTable.tsx
PIMS-1952: Add Reporting notes to Projects Export                                    
[PIMS-1952](https://citz-imb.atlassian.net/browse/PIMS-1952)
> PIMS-1952: Add Reporting notes to projects export

- .github/workflows/DEV-Api-V2-image-deploy.yml
- .github/workflows/DEV-App-V2-image-deploy.yml
- .github/workflows/PROD-Api-V2-image-deploy.yml
- .github/workflows/PROD-App-V2-image-deploy.yml
- .github/workflows/TEST-Api-V2-image-deploy.yml
- .github/workflows/TEST-App-V2-image-deploy.yml
Retry push with rebase to handle conflicts from simultaneous frontend/backend updates
> Retry push with rebase to handle conflicts from simultaneous changes

- react-app/src/App.tsx
[PIMS-1969](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1969)
Added route to router that will navigate back to root if no other route was matched.
To test, try viewing some made up route ie. localhost:3000/login.
Also confirm that all valid routes still work.
> PIMS-1969: Redirect unmatched route

- express-api/src/typeorm/Migrations/1723139478546-TemplatePropertySpellingChange.ts
[PIMS-1756: ](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1756)
Turns out all the other templates already had it reading as "Properties", so only had to update this one.
> PIMS-1756: Fixed a minor spelling error in one of the notification templates

- express-api/src/services/administrativeAreas/administrativeAreasServices.ts
- express-api/src/services/agencies/agencyServices.ts
- express-api/src/services/projects/projectsServices.ts
- express-api/src/services/properties/propertiesServices.ts
- express-api/src/utilities/helperFunctions.ts
- react-app/src/components/adminAreas/AdministrativeAreasTable.tsx
- react-app/src/components/agencies/AgencyTable.tsx
- react-app/src/components/projects/ProjectsTable.tsx
- react-app/src/components/property/PropertyTable.tsx
- react-app/src/components/users/UsersTable.tsx
- react-app/src/hooks/useHistoryAwareNavigate.ts
[PIMS-1956](https://apps.itsm.gov.bc.ca/jira/browse/PIMS-1956)
Added single select style filters where applicable.
This applies to
Properties:
* Agency
* Administrative Areas
* Classification
Projects:
* Agency 
* Status
Administrative Areas:
* Regional District
Agencies:
* Parent Agency
Users:
* Status
* Agency
* Role
For users, I thought it could also make sense to apply it to provider, but I'm not sure we can enumerate the options reliably. 
Please try filtering each of the affected columns to test. Also try filtering using the preset options in the top right and make sure those still work with these changes.
> - I have made corresponding changes to the documentation …
> PIMS-1956: Single select filters

- react-app/package.json
PIMS-1973: Update @turf/turf from version 7.0.0 to 7.1.0 in react-app                                
[PIMS-1973](https://citz-imb.atlassian.net/browse/PIMS-1973)
> PIMS-1973: Update turf from version 7.0.0 to 7.1.0

- react-app/package.json
PIMS-1977 :  Update vite from version 5.3.1 to 5.4.0 in react-app                                  
[PIMS-1977](https://citz-imb.atlassian.net/browse/PIMS-1977)
> PIMS-1977: Update vite from version 5.3.1 to 5.4.0 in react-app

- react-app/package.json
PIMS-1976: Update vite-tsconfig-paths from version 4.3.1 to 5.0.1 in react-app                                      
[PIMS-1976](https://citz-imb.atlassian.net/browse/PIMS-1976)
> PIMS-1976: Update vite-tsconfig-paths from version 4.3.1 to 5.0.1 in react-app

- express-api/package.json
PIMS-1979:  Update winston from version 3.13.0 to 3.14.2 in express-api                                  
[PIMS-1979](https://citz-imb.atlassian.net/browse/PIMS-1979)
> PIMS-1979: Update winston from version 3.13.0 to 3.14.2

- express-api/package.json
PIMS-1982:  Update @types/node from version 22.0.0 to 22.3.0 in express-api                                 
[PIMS-1982](https://citz-imb.atlassian.net/browse/PIMS-1982)
> PIMS-1982: Update @types/node from version 22.0.0 to 22.3.0 in express-api

- express-api/package.json
Moves the swagger-jsdoc dependency out of dev-dependencies. 
Also removes the swagger-autogen from the old implementation.
> Swagger Dependency Move

- express-api/Dockerfile
- express-api/package.json
Another fix to the Swagger page. It wasn't copying over the .swagger.yaml files, so the docs weren't being populated.
This fixes it when building locally. Should fix that issue in OpenShift.
> Swagger Fix #2

- react-app/package.json
PIMS-1992:   Update @mui/x-data-grid from version 7.12.0 to 7.13.0 in react-app                                  
[PIMS-1992](https://citz-imb.atlassian.net/browse/PIMS-1992)
> PIMS-1992: Update @mui/x-data-grid from version 7.12.0 to 7.13.0 in react-app

- express-api/package.json
PIMS-2021:   Update @types/node from version 22.3.0 to 22.5.0 in express-api                                   
[PIMS-2021](https://citz-imb.atlassian.net/browse/PIMS-2021)
> PIMS-2021: Update @types/node from version 22.3.0 to 22.5.0 in express-api

- react-app/package.json
PIMS-2018: Update @testing-library/jest-dom from version 6.4.2 to 6.5.0 in react-app                                         
[PIMS-2018](https://citz-imb.atlassian.net/browse/PIMS-2018)
> PIMS-2018: Update @testing-library/jest-dom from version 6.4.2 to 6.5.0 in react-app

- react-app/package.json
PIMS-2017: Update react-hook-form from version 7.52.0 to 7.53.0 in react-app                                  
[PIMS-2017](https://citz-imb.atlassian.net/browse/PIMS-2017)
> PIMS-2017: Update react-hook-form from version 7.52.0 to 7.53.0 in react-app

- react-app/src/components/form/DateFormField.tsx
[PIMS-2033](https://citz-imb.atlassian.net/browse/PIMS-2033)
- Replaced DateField with DatePicker, and added inline styling for font-size.
> PIMS-2033: Replace DateField with DatePicker

- express-api/package.json
[PIMS-2087](https://citz-imb.atlassian.net/browse/PIMS-2087)
- Updated to latest express version and removed "vulnerable" body parser version as latest express version contains the latest body-parser with no vulnerability.
> PIMS-2087: Update express and remove body-parser

- react-app/package.json
PIMS-2113: Update eslint from version 9.10.0 to 9.11.1 in react-app                                    
[PIMS-2113](https://citz-imb.atlassian.net/browse/PIMS-2113)
> PIMS-2113: Update eslint from version 9.10.0 to 9.11.1 in react-app

- express-api/package.json
- react-app/package.json
PIMS-2115: Update pg from version 8.12.0 to 8.13.0 in express-api                                     
[PIMS-2115](https://citz-imb.atlassian.net/browse/PIMS-2115)
> PIMS-2115: Update pg from version 8.12.0 to 8.13.0 in express-api

- express-api/package.json
[PIMS-2237](https://citz-imb.atlassian.net/browse/PIMS-2237)
Updated linting dependencies as noted in ticket.
Also bumped up express and cookie-parser to address [CVE](https://github.com/advisories/GHSA-pxg6-pf52-xh8x)
> PIMS-2237 Express API Dependency Updates

- react-app/package.json
[PIMS-2238](https://citz-imb.atlassian.net/browse/PIMS-2238)
> PIMS-2238 Update React APP Dependencies

- express-api/package.json
[PIMS-2239](https://citz-imb.atlassian.net/browse/PIMS-2239)
Updates citz-imb-sso-express package to version 1.0.3-beta3 to remove cookie vulnerability
- Run `npm audit` in the `/express-api` folder to see that high vulnerabilities are gone
- Ensure that logging in works as expected 
> PIMS-2239 sso-express 1.0.3-beta3

- react-app/package.json
[PIMS-2251](https://citz-imb.atlassian.net/browse/PIMS-2251)
- Updated minor changes based on the ticket.
- Updated Vite to version 6. The plugin for React didn't accept this, so I've overridden it for now.
- There was an issue where `react-leaflet` was trying to import `@react-leaflet/core`, but it hadn't included that dependency. Added it for now to fix that issue. Not sure why I was running into that issue.
> PIMS-2251 Frontend Dependency Updates

- .github/workflows/DEV-Api-V2-image-build.yml
- .github/workflows/DEV-App-V2-image-build.yml
[PIMS-####](https://citz-imb.atlassian.net/browse/PIMS-####)
The Oc login is not required for the new pipeline to work,, removing unwanted dependency
> remove oc login dependency from GH actions

- express-api/src/constants/config.ts
- express-api/src/typeorm/Migrations/1742330142778-DisableDuplicateAccessRequestTemplate.ts
[PIMS-2279](https://citz-imb.atlassian.net/browse/PIMS-2279)
Addresses the issue of access requests not being sent correctly.
- Commented out the config entry so no one accidentally uses it.
- Added migration to disable the duplicate and add the current email to the correct template.
I've made the email change manually for Christy as a temporary measure. She reported they are getting the access requests now. 
Please test that these migrations work for you locally. 
> PIMS-2279 Duplicate Access Request Template and Fix

- react-app/package.json
[PIMS-2296](https://citz-imb.atlassian.net/browse/PIMS-2296)
List of updates:
Update @mui/x-data-grid from 7.26.0 to 7.27.3
Update @mui/x-date-pickers from 7.26.0 to 7.27.3
Update eslint from 9.20.0 to 9.22.0
Update typescript from 5.7.2 to 5.8.2
Update typescript-eslint from 8.24.0 to 8.26.1
Update vite from 6.0.3 to 6.2.1
> PIMS-2296 Update react-app dependencies

- express-api/package.json
[PIMS-2295](https://citz-imb.atlassian.net/browse/PIMS-2295)
List of updates:
Update @eslint/js from 9.20.0 to 9.22.0
Update @faker-js/faker from 9.4.0 to 9.6.0
Update eslint from 9.20.0 to 9.22.0
Update eslint-config-prettier from 10.0.1 to 10.1.1
Update typescript from 5.7.2 to 5.8.2
Update typescript-eslint from 8.24.0 to 8.26.1
> PIMS-2295 express-api dependency updates

- .env-template
- express-api/src/constants/config.ts
- express-api/src/services/agencies/agencyServices.ts
- express-api/src/services/ches/chesServices.ts
- express-api/src/services/notifications/notificationServices.ts
- express-api/tests/unit/services/notifications/notificationServices.test.ts
[PIMS-2339](https://citz-imb.atlassian.net/browse/PIMS-2339)
Changes from before were working in local and DEV, but not TEST for some reason.
So...
- Adding a logger call to see what exactly is the state of the notification when this seems to fail.
- Passed the user object down to the send notification call. Otherwise, there's a problem where the CHES override To variable needs to be set for this to work.
> Pims 2339b
